unit ursCHAT100;

// =========================================================================
// kbmMW - An advanced and extendable middleware framework.
// by Components4Developers (http://www.components4developers.com)
//
// Service generated by kbmMW service wizard.
//
// INSTRUCTIONS FOR REGISTRATION/USAGE
// -----------------------------------
// Please update the uses clause of the datamodule/form the TkbmMWServer is placed on by adding 
// kbmMWQueryService to it. Eg.
// 
//     uses ...,kbmMWServer,kbmMWQueryService;
// 
// Somewhere in your application, make sure to register the serviceclass to the TkbmMWServer instance. Eg.
// 
// var
//    sd:TkbmMWCustomServiceDefinition;
// ..
//    sd:=kbmMWServer1.RegisterService(yourserviceclassname,false);
// 
// Set the last parameter to true if this is the default service.
// 



{$I kbmMW.inc}

interface

uses
  SysUtils, {$ifdef LEVEL6}Variants,{$endif} Classes, Forms, kbmMWSecurity, kbmMWServer, kbmMWGlobal, kbmMWQueryService,
  DB, nxllTransport, nxptBasePooledTransport, nxtwWinsockTransport,
  nxsdServerEngine, nxreRemoteServerEngine, nxdb, nxllComponent,
  kbmMemTable, kbmMWStreamFormat, 
  Windows,
  kbmMWBinaryStreamFormat, kbmMWCustomMessagingTransport;

type
  TqsCHAT100 = class(TkbmMWQueryService)
    BSF: TkbmMWBinaryStreamFormat;
    tConexao: TnxTable;
    nxSession: TnxSession;
    nxDB: TnxDatabase;
    tConexaoID: TAutoIncField;
    tConexaoAberta: TBooleanField;
    tConexaoTipo: TWordField;
    tConexaoHD: TStringField;
    tConexaoLogin: TDateTimeField;
    tConexaoLogout: TDateTimeField;
    tConexaoLoja: TIntegerField;
    tConexaoUsuario: TStringField;
    tConexaoNome: TStringField;
    tConexaoStatus: TStringField;
    tConexaoIP: TStringField;
    tConexaoThreadID: TIntegerField;
    tUsuario: TnxTable;
    tUsuarioUsername: TStringField;
    tUsuarioSenha: TStringField;
    tUsuarioNome: TStringField;
    tUsuarioAdmin: TBooleanField;
    tUsuarioDireitos: TMemoField;
    tUsuarioNomeCHAT: TStringField;
    tUsuarioStatusCHAT: TStringField;
    tUsuarioCHAT: TBooleanField;
    tCli: TnxTable;
    tCliCodigo: TIntegerField;
    tCliLoja: TStringField;
    procedure kbmMWQueryServiceAuthenticate(Sender: TObject;
      ClientIdent: TkbmMWClientIdentity;
      var Perm: TkbmMWAccessPermissions);
    procedure kbmMWQueryServiceCreate(Sender: TObject);
  private
     { Private declarations }
  protected
     { Private declarations }
     function ThreadID: Cardinal;
     function ObtemUsuarios: String;
     function ObtemLojas: String;
     function ObtemNodes: Variant;
     procedure AlteraStatus(ANovoStatus: String);
     procedure AlteraNome(ANovoNome: String);
     function ProcessRequest(const Func:string; const ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant; override;
  public
     { Public declarations }
{$IFNDEF CPP}class{$ENDIF} function GetPrefServiceName:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetVersion:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetFlags:TkbmMWServiceFlags; override;
  end;

implementation

uses uMWChatConst, uRSDM, chTablesDef, kbmMWCustomTransport, idTcpServer,
  uRSServBD;

{$R *.dfm}


// Service definitions.
//---------------------

{$IFNDEF CPP}class{$ENDIF} function TqsCHAT100.GetPrefServiceName:string;
begin
     Result:='Chat';
end;

{$IFNDEF CPP}class{$ENDIF} function TqsCHAT100.GetVersion:string;
begin
     Result:='100';
end;

{$IFNDEF CPP}class{$ENDIF} function TqsCHAT100.GetFlags:TkbmMWServiceFlags;
begin
     Result:=[mwsfRunRequireAuth, mwsfListed];
end;


procedure TqsCHAT100.kbmMWQueryServiceAuthenticate(Sender: TObject;
  ClientIdent: TkbmMWClientIdentity; var Perm: TkbmMWAccessPermissions);
var
  ThID: Cardinal;
  I   : Integer;
begin
  ThID := ThreadID;
  with ClientIdent do 
  if (Token>'') and (Copy(Token, 5, 20)=IntToStr(ThID)) then
    Perm := [mwapRead,mwapWrite,mwapDelete,mwapExecute]
  else begin
    tConexao.Active := True;
    tUsuario.Active := True;
    tConexao.Refresh;
    tCli.Active := True;
    tCli.IndexName := 'ICodigo';
    tUsuario.IndexName := 'IUsername';
    if Password = SenhaLoja then begin
      InitTran(nxDB, [tConexao, tCli], True);
      try
        tConexao.Insert;
        tConexaoTipo.Value := TipoConexaoLoja;
        tConexaoThreadID.Value := ThID;
        tConexaoIP.Value := RemoteLocation;
        tConexaoHD.Value := ClientLocation;
        tConexaoLogin.Value := Now;
        tConexaoStatus.Value := 'ONLINE';
        tConexaoAberta.Value := True;
        I := StrToIntDef(Username, 0);
        if (I>0) and tCli.FindKey([I]) then begin
          tConexaoLoja.Value := I;
          tConexaoNome.Value := tCliLoja.Value;
        end;  
        tConexao.Post;  
        nxDB.Commit;  
      except
        nxDB.Rollback;
        if tConexao.State in [dsInsert, dsEdit] then tConexao.Cancel;
        Raise;
      end;    
    end else begin
      InitTran(nxDB, [tConexao, tUsuario], True);
      try
        tUsuario.IndexName := 'IUsername';
        if not tUsuario.FindKey([Username]) then 
          Raise Exception.Create('Username inválido');

        if tUsuarioSenha.Value <> Password then 
          Raise Exception.Create('Senha inválida');

        if not tUsuarioCHAT.Value then  
          Raise Exception.Create('Esse usuário não tem permissão de usar o CHAT');
                                     
        tConexao.Insert;
        tConexaoTipo.Value := TipoConexaoUsuario;
        tConexaoThreadID.Value := ThID;
        tConexaoIP.Value := RemoteLocation;
        tConexaoHD.Value := ClientLocation;
        tConexaoLogin.Value := Now;
        tConexaoStatus.Value := 'ONLINE';
        tConexaoAberta.Value := True;
        tConexaoUsuario.Value := Username;
        tConexaoNome.Value := tUsuarioNomeChat.Value;
        if Trim(tConexaoNome.Value)='' then
          tConexaoNome.Value := tUsuarioNome.Value;
        tConexao.Post;  
        nxDB.Commit;
      except
        nxDB.Rollback;
        if tConexao.State in [dsInsert, dsEdit] then tConexao.Cancel;
        Raise;
      end;    
    end;
    Token := 'CHAT'+IntToStr(ThID);
    Perm := [mwapRead,mwapWrite,mwapDelete,mwapExecute];
    DM.TCPIPMsg.SendMessage('MSG.CHAT.TODOS.LOGIN', '', ClientIdentity, nil, 
       [ClientLocation, 
        Username, 
        tConexaoNome.Value,
        tConexaoStatus.Value,
        tConexaoIP.Value,
        tConexaoTipo.Value]);
  end;
end;

procedure TqsCHAT100.kbmMWQueryServiceCreate(Sender: TObject);
begin
  tConexao.Open;
  tUsuario.Open;
  tCli.Open;
end;

function TqsCHAT100.ObtemLojas: String;
var SL: TStrings;
begin
  SL := TStringList.Create;
  try
    tCli.First;
    while not tCli.Eof do begin
      SL.Add(tCliCodigo.AsString+'='+tCliLoja.AsString);
      tCli.Next;
    end;
    Result := SL.Text;
  finally 
    SL.Free;
  end;
end;

function TqsCHAT100.ObtemNodes: Variant;
var MT: TkbmMemTable;
begin
  MT := CreateMemTableAndFields(Self, chNodes);
  try
    tConexao.Active := True;
    tConexao.Refresh;
    tConexao.IndexName := 'IAbertaThreadID';
    tConexao.SetRange([True], [True]);
    try
      tConexao.First;
      while not tConexao.Eof do begin
        if tConexaoThreadID.Value <> ThreadID then begin
          MT.Insert;
          MT.FieldByName('NodeID').AsString := tConexaoHD.Value;
          MT.FieldByName('Tipo').AsInteger := tConexaoTipo.Value;
          if tConexaoTipo.Value = TipoConexaoLoja then
            MT.FieldByName('Username').AsString := tConexaoLoja.AsString
          else  
            MT.FieldByName('Username').AsString := tConexaoUsuario.AsString;
          MT.FieldByName('IP').AsString := tConexaoIP.Value;
          MT.FieldByName('Nome').AsString := tConexaoNome.Value;
          MT.FieldByName('Status').AsString := tConexaoStatus.Value;  
          MT.Post;
        end;  
        tConexao.Next;
      end;      
      Result := MT.AllData;
    finally
      tConexao.CancelRange;
    end;
  finally
    MT.Free;
  end;
end;

function TqsCHAT100.ObtemUsuarios: String;
var 
  SL: TStrings;
  S: String;
begin
  SL := TStringList.Create;
  try
    tUsuario.First;
    while not tUsuario.Eof do begin
      if tUsuarioChat.Value then begin
        S := tUsuarioNomeChat.Value;
        if Trim(S)='' then
          S := tUsuarioNome.Value;
        SL.Add(tUsuarioUsername.AsString+'='+S);
      end;  
      tUsuario.Next;
    end;
    Result := SL.Text;
  finally 
    SL.Free;
  end;
end;

function TqsCHAT100.ProcessRequest(const Func: string;
  const ClientIdent: TkbmMWClientIdentity;
  const Args: array of Variant): Variant;
var AFunc: String;
begin
  AFunc := Trim(UpperCase(Func));
  if AFunc='OBTEMUSUARIOS' then
    Result := ObtemUsuarios
  else 
  if AFunc='OBTEMNODES' then
    Result := ObtemNodes
  else 
  if AFunc='OBTEMLOJAS' then
    Result := ObtemLojas   
  else
  if AFunc='ALTERANOME' then
    AlteraNome(Args[0])   
  else  
  if AFunc='ALTERASTATUS' then
    AlteraStatus(Args[0])
  else 
    Result:= inherited ProcessRequest(Func, ClientIdent, Args);
end;

procedure TqsCHAT100.AlteraNome(ANovoNome: String);
begin
  tConexao.Active := True;
  InitTran(nxDB, [tConexao], True);
  try
    tConexao.IndexName := 'IAbertaThreadID';
    tConexao.Refresh;
    if not tConexao.FindKey([True, ThreadID]) then begin
      nxDB.Rollback;
      Exit;
    end;
    tConexao.Edit;
    tConexaoNome.Value := ANovoNome;
    tConexao.Post;  
    nxDB.Commit;
    DM.TCPIPMsg.SendMessage('MSG.CHAT.TODOS.NOME', '', ClientIdentity, nil, [tConexaoNome.Value]);
  except
    nxDB.Rollback;
    Raise;
  end;
end;

procedure TqsCHAT100.AlteraStatus(ANovoStatus: String);
begin
  tConexao.Active := True;
  InitTran(nxDB, [tConexao], True);
  try
    tConexao.IndexName := 'IAbertaThreadID';
    tConexao.Refresh;
    if not tConexao.FindKey([True, ThreadID]) then begin
      nxDB.Rollback;
      Exit;
    end;
    tConexao.Edit;
    tConexaoStatus.Value := ANovoStatus;
    tConexao.Post;  
    nxDB.Commit;
    DM.TCPIPMsg.SendMessage('MSG.CHAT.TODOS.STATUS', '', ClientIdentity, nil, [tConexaoStatus.Value]);
  except
    nxDB.Rollback;
    Raise;
  end;
end;

function TqsCHAT100.ThreadID: Cardinal;
begin
  Result := TidPeerThread(TkbmMWServerTransportInfo(RequestTransportStream.Info).Client).ThreadID;
end;

end.
