unit uRSQSRegistro200;

// =========================================================================
// kbmMW - An advanced and extendable middleware framework.
// by Components4Developers (http://www.components4developers.com)
//
// Service generated by kbmMW service wizard.
//
// INSTRUCTIONS FOR REGISTRATION/USAGE
// -----------------------------------
// Please update the uses clause of the datamodule/form the TkbmMWServer is placed on by adding 
// kbmMWQueryService to it. Eg.
// 
//     uses ...,kbmMWServer,kbmMWQueryService;
// 
// Somewhere in your application, make sure to register the serviceclass to the TkbmMWServer instance. Eg.
// 
// var
//    sd:TkbmMWCustomServiceDefinition;
// ..
//    sd:=kbmMWServer1.RegisterService(yourserviceclassname,false);
// 
// Set the last parameter to true if this is the default service.
// 



{$I kbmMW.inc}

interface

uses
  SysUtils, {$ifdef LEVEL6}Variants,{$endif} Classes, Forms, kbmMWSecurity, kbmMWServer, kbmMWGlobal, kbmMWQueryService, kbmMWNexusDB, kbmMWBinaryStreamFormat,
  kbmMemTable, kbmMWStreamFormat, DB, kbmMWCustomConnectionPool,
  kbmMWCustomDataset, kbmMWResolvers, nxdb, nxllTransport,
  nxptBasePooledTransport, nxtwWinsockTransport, nxsdServerEngine,
  nxreRemoteServerEngine, nxllComponent, uLicEXECryptor, kbmMemBinaryStreamFormat, uRSLogInfo;

type
  TqsRegistro200 = class(TkbmMWQueryService)
    BSF: TkbmMWBinaryStreamFormat;
    nxDB: TnxDatabase;
    nxSession: TnxSession;
    tCli: TnxTable;
    MT: TkbmMemTable;
    MTCodigo: TIntegerField;
    MTSenha: TStringField;
    MTCadastroEm: TDateTimeField;
    MTCadastroPor: TStringField;
    MTAtualizadoEm: TDateTimeField;
    MTAtualizadoPor: TStringField;
    MTLoja: TStringField;
    MTRazaoSocial: TStringField;
    MTPais: TStringField;
    MTCidade: TStringField;
    MTUF: TStringField;
    MTEndereco: TMemoField;
    MTCEP: TStringField;
    MTBairro: TStringField;
    MTSerieHD: TStringField;
    MTNumMaq: TWordField;
    MTCNPJ: TStringField;
    MTIE: TStringField;
    MTObs: TMemoField;
    MTTelefones: TMemoField;
    MTEmailReg: TMemoField;
    MTFormaPagto: TMemoField;
    MTLicMaq: TWordField;
    MTLicVenc: TDateField;
    MTManInicio: TDateField;
    MTManVenc: TDateField;
    MTProprietarios: TMemoField;
    MTGerente: TStringField;
    MTTipoLoja: TWordField;
    MTEmailTec: TMemoField;
    MTBSF: TkbmBinaryStreamFormat;
    MTLicTipo: TWordField;
    tLog: TnxTable;
    tLogNum: TAutoIncField;
    tLogDataHora: TDateTimeField;
    tLogLoja: TIntegerField;
    tLogDetalhes: TMemoField;
    tLogIP: TStringField;
    tLogOperID: TWordField;
    tLogOK: TBooleanField;
    tLogSerieHD: TStringField;
    tCorpo: TnxTable;
    tCorpoID: TAutoIncField;
    tCorpoCorpo: TMemoField;
    tCorpoAssunto: TStringField;
    tCorpoInclusao: TDateTimeField;
    tCorpoTipo: TWordField;
    tCorpoEnviarEm: TDateTimeField;
    tCorpoProcessou: TBooleanField;
    tCorpoDestino: TMemoField;
    tAut: TnxTable;
    qCli: TnxQuery;
    tEst: TnxTable;
    tEstSearch: TnxTable;
    tEstID: TAutoIncField;
    tEstLoja: TIntegerField;
    tEstData: TDateField;
    tEstCaixa: TIntegerField;
    tEstDataAtu: TDateTimeField;
    tEstSessoesQtd: TIntegerField;
    tEstSessoesTempo: TFloatField;
    tEstURLs: TIntegerField;
    tEstCodEquip: TStringField;
    tEstSearchID: TAutoIncField;
    tEstSearchLoja: TIntegerField;
    tEstSearchData: TDateField;
    tEstSearchCaixa: TIntegerField;
    tEstSearchCodEquip: TStringField;
    tEstSearchDataAtu: TDateTimeField;
    tEstSearchQtd: TIntegerField;
    tEstSearchPag: TIntegerField;
    tEstSearchEst: TIntegerField;
    tEstRes: TnxTable;
    tEstResLoja: TIntegerField;
    tEstResCodEquip: TStringField;
    tEstResRes: TStringField;
    tEstResQtd: TIntegerField;
    tEstSearchEng: TStringField;
    procedure kbmMWQueryServiceCreate(Sender: TObject);
    procedure kbmMWQueryServiceDestroy(Sender: TObject);
  private
    LI : TLogInfo;
    Reg : TRegistro;
     { Private declarations }
  protected
     { Private declarations }
    function LogModoDemo(const Args:array of Variant):Variant; 
    function ObtemLicencaTeste(const Args:array of Variant):Variant; 
    function ObtemLicenca(const Args:array of Variant):Variant; 
    {Loja: Integer; Versao: String; SerieHD: String; EmDemo: Boolean}

    function EnviaEmailRegistros(D: TDataset; aEmail: String = ''): String;
    
    function TrocaHD(const Args:array of Variant):Variant; 
    function TrocaProg(const Args:array of Variant):Variant; 
    
    function AtualizaCadastro(const Args:array of Variant):Variant; 
    function ObtemCadastro(const Args:array of Variant):Variant; 
    function ObtemCodLojaPorEmail(const Args:array of Variant):Variant;
    function ObtemCodLojaPorEquip(const Args:array of Variant):Variant;
    function ObtemSenha(const Args:array of Variant):Variant;
    function SalvaEstInt(
      aCodLoja: Integer; aCodEquip: String;
      aData: TDateTime; aCaixa, aURLs, aQtdSessoes: Integer; aTempoSessoes: Double; aRes,
      aSearch: String): Boolean;
      
    function SalvaEst(const Args:array of Variant):Variant;
    function ProcessRequest(const Func:string; const ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant; override;
  public
     { Public declarations }
{$IFNDEF CPP}class{$ENDIF} function GetPrefServiceName:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetVersion:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetAuthor:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetAssistance:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetDescriptionAbstract:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetFlags:TkbmMWServiceFlags; override;
  end;

const
  CamposReadOnly =
    '|CODIGO|CADASTROEM|CADASTROPOR|LICMAQ|LICVENC|LICTIPO|MANINICIO|MANVENC|MESSENGER|ICQ|';

  opObtemLicenca = 1;
  opObtemCadastro = 2;
  opModoDemo = 3;
  opTrocaHD = 4;
  opTesteGratis = 5;
  opAtualizaCadastro = 6;
  opPirata = 7;
  opUpgradeNex = 8;
  opObtemCodLojaPorEmail = 9;
  opObtemCodLojaPorEquip = 10;
  opObtemSenha = 11;
  opSalvaEst = 12;
  

  OpString : Array[opObtemLicenca..opSalvaEst] of String = (
    'ObtemLicenca    ',
    'ObtemCadastro   ',
    'ModoDemo        ',
    'TrocaHD         ',
    'TesteGratis     ',
    'AtualizaCadastro',
    'Pirata',
    'Upgrade para Nex',
    'CodLojaPorEmail ',
    'CodLojaPorEquip ',
    'ObtemSenha      ',
    'Salva Estat.    ');

implementation

uses uRSDM, nrAutorizacao, uRSServBD;

{$R *.dfm}


// Service definitions.
//---------------------

{$IFNDEF CPP}class{$ENDIF} function TqsRegistro200.GetPrefServiceName:string;
begin
     Result:='REGISTRO';
end;

{$IFNDEF CPP}class{$ENDIF} function TqsRegistro200.GetVersion:string;
begin
     Result:='2.00';
end;

{$IFNDEF CPP}class{$ENDIF} function TqsRegistro200.GetAuthor:string;
begin
     Result:='joao@nextar.com.br';
end;

function TqsRegistro200.EnviaEmailRegistros(D: TDataset; aEmail: String = ''): String;
var
  aReg : TStrings;
  aCorpo : String;
  Venc : Variant;
  i2: Integer;
  aRes, aDest : TStrings;

function VariantToDateStr(V: Variant): String;
begin
  if V=null then
    Result := '' else
    Result := FormatDateTime('dd/mm/yyyy', V);
end;

function Expirou(V: Variant): Boolean;
begin
  Result := (V=null) or (Date<V);
end;
  
function NextEmail(var S: String): String;
var P: Integer;
begin
  S := Trim(S);
  Result := '';
  if S>'' then begin
    for P := 1 to Length(S) do
      if Pos(S[P], ' ,;')>0 then begin
        Result := Copy(S, 1, P-1);
        Delete(S, 1, P);
        Exit;
      end;
    Result := S;
    S := '';  
  end;
  if (Pos('@', Result)<1) or (Pos('.', Result)<1) then
    Result := '';
  if (aEmail>'') and  (not SameText(aEmail, Result)) then
    Result := '';
end;

function EmailsValidos: String;
var 
  SL: TStrings;
  S, S2 : String;
  I : Integer;
begin
  Result := '';
  SL := TStringList.Create;
  try
    SL.Text := D.FieldByName('EmailReg').AsString;
    for I := 0 to SL.Count - 1 do begin
      S := SL[I];
      while S>'' do begin 
        S2 := NextEmail(S);
        if S2>'' then begin
          if Result>'' then
            Result := Result+sLineBreak;
          Result := Result + S2;  
        end;
      end;
    end;
  finally
    SL.Free;
  end;
end;  

procedure AddCorpo(S: String);
begin
  aCorpo := aCorpo+S+sLineBreak;
end;

begin
  Result := '';
  aEmail := Trim(aEmail);
  aRes := TStringList.Create;
  aDest := TStringList.Create;
  
  tAut.Active := True;
  tCorpo.Active := True;
  try
    tAut.IndexName := 'ILoja';
    while not D.Eof do begin
      aDest.Text := EmailsValidos;
      if (aDest.Text>'') and tAut.FindKey([D.FieldByName('Codigo').AsInteger, True]) then 
      begin
        for i2 := 0 to aDest.Count-1 do
          if aRes.IndexOf(aDest[i2])=-1 then
            aRes.Add(aDest[i2]);
          
        tCorpo.Insert;
        tCorpoEnviarEm.Value := EncodeDate(2004, 1, 1);
        tCorpoInclusao.Value := Now;
        tCorpoProcessou.Value := False;
        tCorpoDestino.Value := aDest.Text;
        tCorpoAssunto.Value := 'NexCafé - Informações de Registro';
        aCorpo := '';
        AddCorpo('Registro realizado em ' + D.FieldByName('CadastroEm').AsString +':');
        AddCorpo('');
        AddCorpo('Nome da Loja: ' + D.FieldByName('Loja').AsString);
        AddCorpo('Qtd.Máquinas: ' + tAut.FieldByName('Maquinas').AsString);
        AddCorpo('');
        AddCorpo('Cidade: ' + D.FieldByName('Cidade').AsString);
        AddCorpo('Bairro: ' + D.FieldByName('Bairro').AsString);
        AddCorpo('');
        AddCorpo('Codigo de Loja: ' + CodLojaToStr(D.FieldByName('Codigo').AsInteger));
        AddCorpo('Senha de Registro: ' + D.FieldByName('Senha').AsString);
        AddCorpo('');
        Venc := tAut.FieldByName('Vencimento').AsVariant;
        case tAut.FieldByName('Tipo').AsInteger of
          taDefinitiva : AddCorpo('Licença Definitiva: Nunca Expira');
          taLocacao : 
            if Expirou(Venc) then 
              AddCorpo('Locação expirou em: ' + VariantToDateStr(Venc)) else
              AddCorpo('Locação vence em: ' + VariantToDateStr(Venc));

          taTesteGratuito :    
            if Expirou(Venc) then 
              AddCorpo('Licença de Teste Gratuito Expirou em: ' + VariantToDateStr(Venc)) else
              AddCorpo('Licença de Teste Gratuito Expira em: ' + VariantToDateStr(Venc));

          taTemporaria :    
            if Expirou(Venc) then 
              AddCorpo('Licença Temporária Expirou em: ' + VariantToDateStr(Venc)) else
              AddCorpo('Licença Temporária Expira em: ' + VariantToDateStr(Venc));
        end;
        tCorpoCorpo.Value := aCorpo;
        
        tCorpo.Post;
      end;
      D.Next;
    end;
    Result := aRes.Text;
  finally
    aRes.Free;
    aDest.Free;
  end;
end;

{$IFNDEF CPP}class{$ENDIF} function TqsRegistro200.GetAssistance:string;
begin
     Result:='joao@nextar.com.br';
end;

{$IFNDEF CPP}class{$ENDIF} function TqsRegistro200.GetDescriptionAbstract:string;
begin
     Result:='CADASTRO DE CLIENTES';
end;

{$IFNDEF CPP}class{$ENDIF} function TqsRegistro200.GetFlags:TkbmMWServiceFlags;
begin
     Result:=[mwsfListed];
end;

function TqsRegistro200.ProcessRequest(const Func: string;
  const ClientIdent: TkbmMWClientIdentity;
  const Args: array of Variant): Variant;
var 
  uFunc : String;  
begin
  Inc(nRequests[1]);

  uFunc := UpperCase(Func);
  try
    try
      tLog.Active := True;
    except
    end;  
    if uFunc='OBTEMLICENCATESTE' then begin
      LI.Inicia(opTesteGratis, ClientIdent.RemoteLocation);
      Result := ObtemLicencaTeste(Args);
    end else
    if uFunc='MODODEMO' then begin
      LI.Inicia(opModoDemo, ClientIdent.RemoteLocation);
      Result := LogModoDemo(Args);
    end else
    if uFunc='OBTEMREGISTRO' then begin
      LI.Inicia(opObtemLicenca, ClientIdent.RemoteLocation);
      Result := ObtemLicenca(Args);
    end else  
    if uFunc='TROCAHD' then begin
      LI.Inicia(opTrocaHD, ClientIdent.RemoteLocation);
      Result := TrocaHD(Args)
    end else  
    if uFunc='UPGRADENEX' then begin
      LI.Inicia(opUpgradeNex, ClientIdent.RemoteLocation);
      Result := TrocaProg(Args)
    end else  
    if uFunc='ATUALIZACADASTRO' then begin
      LI.Inicia(opAtualizaCadastro, ClientIdent.RemoteLocation);
      Result := AtualizaCadastro(Args);
    end else  
    if uFunc='OBTEMCADASTRO' then begin
      LI.Inicia(opObtemCadastro, ClientIdent.RemoteLocation);
      Result := ObtemCadastro(Args);
    end else 
    if uFunc='OBTEMCODLOJAPOREMAIL' then begin
      LI.Inicia(opObtemCodLojaPorEmail, ClientIdent.RemoteLocation);
      Result := ObtemCodLojaPorEmail(Args);
    end else
    if uFunc='OBTEMCODLOJAPOREQUIP' then begin
      LI.Inicia(opObtemCodLojaPorEquip, ClientIdent.RemoteLocation);
      Result := ObtemCodLojaPorEquip(Args);
    end else
    if uFunc='OBTEMSENHA' then begin
      LI.Inicia(opObtemSenha, ClientIdent.RemoteLocation);
      Result := ObtemSenha(Args);
    end else
    if uFunc='SALVAEST' then begin
      LI.Inicia(opSalvaEst, ClientIdent.RemoteLocation);
      Result := SalvaEst(Args);
    end else
      Result := inherited ProcessRequest(Func, ClientIdent, Args)
  except
    On E: Exception do
      Result := VarArrayOf(['Erro não esperado no servidor de registro: ' + E.Message]);
  end;  
  try 
    if Result[0] = 'OK' then
      LI.liOK := True
    else begin 
      LI.liOK := False;
      LI.liDetalhes.Add('RESULTADO = ' + Result[0]);
    end;  
  except
  end;
  
  if not (LI.liOper in [opModoDemo, opObtemLicenca]) then
    LI.SaveToDataset(tLog);  
end;

function TqsRegistro200.SalvaEst(const Args: array of Variant): Variant;
begin
  Result := SalvaEstInt(Args[0], Args[1], Args[2], Args[3], Args[4], Args[5], Args[6], Args[7], Args[8]);
end;

function TqsRegistro200.SalvaEstInt(aCodLoja: Integer; aCodEquip: String;
  aData: TDateTime; aCaixa, aURLs, aQtdSessoes: Integer; aTempoSessoes: Double;
  aRes, aSearch: String): Boolean;
var 
  Achou : Boolean; 
  SL : TStrings; 
  I: Integer;
  cTipo : Char;
  sEng: String;
begin
  InitTran(nxDB, [tEst, tEstSearch, tEstRes], True);
  try
    tEstSearch.IndexName := 'IEstEng';
    if aCodLoja>0 then begin
      tEst.IndexName := 'ILojaCaixa';
      Achou := tEst.FindKey([aCodLoja, aCaixa]);
    end else begin
      tEst.IndexName := 'ICodEquipCaixa';
      Achou := tEst.FindKey([aCodEquip, aCaixa]);
    end;
    if Achou then begin
      while tEstSearch.FindKey([tEstID.Value]) do tEstSearch.Delete;
      if aCodLoja>0 then begin
        tEstRes.IndexName := 'ILojaRes';
        while tEstRes.FindKey([aCodLoja]) do tEstRes.Delete;
      end else begin
        tEstRes.IndexName := 'ICodEquipRes';
        while tEstRes.FindKey([aCodEquip]) do tEstRes.Delete;
      end;
      tEst.Edit;
    end else 
      tEst.Insert;
    tEstLoja.Value := aCodLoja;
    tEstCodEquip.Value := aCodEquip;
    tEstData.Value := aData;
    tEstCaixa.Value := aCaixa;
    tEstURLs.Value := aURLs;
    tEstSessoesQtd.Value := aQtdSessoes;
    tEstSessoesTempo.Value := aTempoSessoes;  
    tEstDataAtu.Value := Now;
    tEst.Post;
    SL := TStringList.Create;
    try
      SL.Text := aRes;
      for I := 0 to SL.Count - 1 do begin
        tEstRes.Insert;
        tEstResLoja.Value := aCodLoja;
        tEstResCodEquip.Value := aCodEquip;
        tEstResRes.Value := SL.Names[I];
        tEstResQtd.Value := StrToIntDef(SL.ValueFromIndex[I], 0);
        tEstRes.Post;
      end;
  
      SL.Text := aSearch;
      for I := 0 to SL.Count - 1 do begin
        sEng := SL.Names[I];
        if sEng>'' then
          cTipo := sEng[1] else
          cTipo := #0;
        Delete(sEng, 1, 2);
        
        if (sEng>'') and (cTipo<>#0) then begin
          if tEstSearch.FindKey([tEstID.Value, sEng]) then
            tEstSearch.Edit else
            tEstSearch.Insert;
          tEstSearchEng.Value := sEng;
          tEstSearchLoja.Value := aCodLoja;
          tEstSearchCodEquip.Value := aCodEquip;
          tEstSearchData.Value := aData;
          tEstSearchCaixa.Value := aCaixa;
          tEstSearchEst.Value := tEstID.Value;
          tEstSearchDataAtu.Value := tEstDataAtu.Value;
          case cTipo of
            'q' : tEstSearchQtd.Value := StrToIntDef(SL.ValueFromIndex[I], 0);
            'p' : tEstSearchPag.Value := StrToIntDef(SL.ValueFromIndex[I], 0);
          end;
          tEstSearch.Post;
        end;
      end;
    finally
      SL.Free;
    end;
    nxDB.Commit;
  except
    nxDB.Rollback;
    Raise;
  end;
  Result := True;
end;

procedure TransfDados(O, D: TDataset; Tudo: Boolean);
var 
  I : Integer;
  F : TField;
begin
  for I := 0 to D.FieldCount-1 do with D.Fields[I] do 
  if Tudo or ((DataType<>ftAutoInc) and (Pos('|'+UpperCase(FieldName)+'|', CamposReadOnly)=0)) then 
  begin
    F := O.FindField(FieldName);
    if F<>nil then
      Value := F.Value;
  end;  
end;

function TqsRegistro200.ObtemLicencaTeste(
  const Args: array of Variant): Variant;
var 
  SIndex : String;
  SLE : TStrings;
  S : String;
  Dia : TDateTime;
  A, B: TCabAutorizacao;
  I: Integer;
  SL: TStringList;
begin
  Result := VarArrayOf(['Para testar o NexCafé você deve baixar o NexCafé 4.0 do nosso site: www.nexcafe.com.br. O NexCafé 4.0 é grátis!']);
  Exit;
  
  A := TCabAutorizacao.Create;
  B := TCabAutorizacao.Create;
  SL := TStringList.Create;
  try
    SL.Text := Args[0];
    if tAut.Locate('CodigoEquip; Tipo', VarArrayOf([SL.Values['CodEquip'], taTesteGratuito]), []) then begin
      Result := VarArrayOf(['Já foi concedido anteriormente uma licença para teste para esse mesmo disco rígido. '+
                'Envie E-mail para vendas@nextar.com.br solicitando uma prorrogação do seu período de teste gratuito.']);
      Exit;
    end;     
      
    tCli.Active := False;
    tCli.Active := True;
    tCli.Insert;
    tCli.FieldByName('Loja').AsString := Sl.Values['Nome'];
    tCli.FieldByname('Proprietarios').AsString := Sl.Values['Prop'];
    tCli.FieldByName('Telefones').AsString := Sl.Values['Tel'];
    tCli.FieldByName('Pais').AsString := Sl.Values['Pais'];
    tCli.FieldByName('Cidade').AsString := sl.Values['Cidade'];
    tCli.FieldByName('UF').AsString := sl.Values['Estado'];
    tCli.FieldByName('CEP').AsString := sl.Values['CEP'];
    tCli.FieldByName('Endereco').AsString := SL.Values['Endereco'];
    tCli.FieldByName('CodEquip').AsString := SL.Values['CodEquip'];
    tCli.FieldByName('EmailReg').AsString := SL.Values['Email'];
    tCli.FieldByName('Senha').AsString := sl.Values['Senha'];
    tCli.FieldByName('LicMaq').AsString := sl.Values['QtdMaq'];
    tCli.FieldByName('LicTipo').AsString := sl.Values['Tipo'];
    Dia := Date + 7;
    while DayOfWeek(Dia) in [1, 7] do Dia := Dia + 1;
    tCli.FieldByName('LicVenc').AsDateTime := Dia;
    tCli.FieldByName('CadastroEm').AsDateTime := Now;
    tCli.FieldByName('CadastroPor').AsString := 'Cliente';
    tCli.FieldByName('AtualizadoEm').AsDateTime := Now;
    tCli.FieldByName('AtualizadoPor').AsString := 'Cliente';
    if DayOfWeek(tCli.FieldByName('LicVenc').AsDateTime) = 1 then
      tCli.FieldByName('LicVenc').AsDateTime := tCli.FieldByName('LicVenc').Value + 1;
      
    if DayOfWeek(tCli.FieldByName('LicVenc').AsDateTime) = 7 then
      tCli.FieldByName('LicVenc').AsDateTime := tCli.FieldByName('LicVenc').AsDateTime + 2;
    tCli.FieldByName('Programa').AsInteger := 1;
    tCli.Post;
    LI.liLoja := tCli.FieldByName('Codigo').AsInteger;
    Reg.CodLoja := LI.liLoja;
    A.Load(tCli.FieldByName('Codigo').AsInteger, tCli, tAut);
    B.AssignFrom(A);
    with A.NewItem do begin
      auTipo := taTesteGratuito;
      auMaquinas := tCli.FieldByName('LicMaq').AsInteger;
      auVencimento := Dia;
    end;
    A.Save('cliente', B, tCli, tAut);
    LI.liLoja := tCli.FieldByName('Codigo').AsInteger;
    LI.liHD := A.caCodEquip;
    tAut.IndexName := 'ILoja';
    if not tAut.FindKey([ LI.liLoja, True]) then
      Result := VarArrayOf(['Falha no servidor de registro']) else
      Result := VarArrayOf(['OK', LI.liLoja, tAut.FieldByName('Autorizacao').AsString]);
    SLE := TStringList.Create;
    try
      tCorpo.Active := True;
      tCorpo.Insert;
      tCorpoEnviarEm.Value := EncodeDate(2004, 1, 1);
      tCorpoInclusao.Value := Now;
      tCorpoProcessou.Value := False;
      tCorpoDestino.Value := Email_Cybermgr;
      tCorpoAssunto.Value := 'NexCafé - Novo Cadastro';
      SLE.Add('Nova loja testando o Nexcafé em ' + FormatDateTime('dd/mm/yyyy hh:mm', Now));
      SLE.Add('');
      SLE.Add('Loja = ' + tCli.FieldByName('Loja').AsString);
      SLE.Add('Código = ' + CodLojaToStr(tCli.FieldByName('Codigo').AsInteger));
      SLE.Add('Senha = ' + tCli.FieldByName('Senha').AsString);
      SLE.Add('Código de Equipamento = ' + tCli.FieldByName('CodEquip').AsString);
      SLE.Add('Maquinas = ' + tCli.FieldByName('LicMaq').AsString);
      SLE.Add('Proprietario = ' + tCli.FieldByName('Proprietarios').AsString);
      SLE.Add('Gerente = ' + tCli.FieldByName('Gerente').AsString);
      SLE.Add('Cidade = ' + tCli.FieldByName('Cidade').AsString + '/' + tCli.FieldByName('UF').AsString);
      SLE.Add('Telefones = ' + tCli.FieldByName('Telefones').AsString);
      SLE.Add('');
      SLE.Add('Email Registro = ' + tCli.FieldByname('EmailReg').AsString);
      SLE.Add('');
      SLE.Add('Email Técnico = ' + tCli.FieldByname('EmailTec').AsString);
      tCorpoCorpo.Value := SLE.Text;
      tCorpo.Post;

      S := ExtractFilePath(ParamStr(0)) + 'emailregnex.txt';
      if FileExists(S) then begin
        SLE.LoadFromFile(S);
        S := SLE.Text;

        repeat
          I := Pos('%CODLOJA', S);
          if I>0 then
            S := Copy(S, 1, I-1) + Reg.CodLojaAsString + Copy(S, I+8, Length(S));
        until (I<1);

        repeat
          I := Pos('%SENHAREG', S);
          if I>0 then
            S := Copy(S, 1, I-1) + tCli.FieldByName('Senha').AsString + Copy(S, I+9, Length(S));
        until (I<1);

        repeat
          I := Pos('%AUTORIZACAO', S);
          if I>0 then
          if Reg.NumChaves>0 then
            S := Copy(S, 1, I-1) + tAut.FieldByName('Autorizacao').AsString + Copy(S, I+12, Length(S)) else
            Delete(S, I, 12);
        until (I>1);
        
        tCorpo.Insert;
        tCorpoEnviarEm.Value := EncodeDate(2004, 1, 1);
        tCorpoInclusao.Value := Now;
        tCorpoProcessou.Value := False;
        tCorpoDestino.Value := Trim(MT.FieldByName('EmailReg').AsString);
        tCorpoAssunto.Value := 'Registro NexCafé';
        tCorpoCorpo.Value := SLE.Text;
        tCorpo.Post;
      end;
    except
    end;
    SLE.Free;
    tCorpo.Active := False;
  finally
    SL.Free;
    A.Free;
    B.Free;
  end;    
end;

function TqsRegistro200.ObtemSenha(const Args: array of Variant): Variant;
begin
  tCli.Active := False;
  tCli.Active := True;
  tCli.IndexName := 'ICodigo';
  tCli.SetRange([Args[0]], [Args[0]]);
  try
    if not tCli.IsEmpty then
      Result := EnviaEmailRegistros(tCli);
    if Result='' then
      Result := VarArrayOf(['']) else
      Result := VarArrayOf(['OK', Result]); 
  finally
    tCli.CancelRange;
  end;
end;

function TqsRegistro200.ObtemLicenca(
  const Args: array of Variant): Variant;
    {Loja: Integer; Versao: String; SerieHD: String; EmDemo: Boolean}
var S: String;  
begin
  tCli.Active := False;
  tCli.Active := True;
  LI.liLoja :=   Args[0];
  
  LI.liHD := Args[2];
  if Args[3]=0 then 
    LI.liOper := opModoDemo
  else  
    LI.liOper := opObtemLicenca;
    
  LI.liDetalhes.Add('Versão NexServ = ' + Args[1]);  
  
  if LI.liLoja>0 then begin
    if (not tCli.FindKey([LI.liLoja])) or 
       (tCli.FieldByName('Bloqueado').AsBoolean=True) or
       (not tAut.FindKey([LI.liLoja, True])) 
    then  
      Result := VarArrayOf(['OK', LI.liLoja, ChaveBloqueado, ''])
    else
    if tCli.FieldByName('Programa').AsInteger=0 then
      Result := VarArrayOf(['OK', LI.liLoja, ChaveCybermgr, ''])
    else begin
      S := '';
      tAut.IndexName := 'ILoja';
      tAut.SetRange([LI.liLoja, True], [LI.liLoja, True]);
      try
        while not tAut.Eof do begin
          if S>'' then S := S + ';';
          if Venceu7Dias(tAut) then
            S := S + ChaveBloqueado else
            S := S + tAut.FieldByName('Autorizacao').AsString;
          if not tAut.FieldByName('EnviouCli').AsBoolean then begin
            tAut.Edit;
            tAut.FieldByName('EnviouCli').AsBoolean := True;
            tAut.Post;
          end;
          tAut.Next;
        end;
      finally
        tAut.CancelRange;
      end;
      
      tCli.Edit;
      tCli.FieldByName('UObtemLic').AsDateTime := Now;
      tCli.FieldByName('UVersao').AsString := Args[1];
      tCli.Post;
      Result := VarArrayOf(['OK', LI.liLoja, S, tCli.FieldByName('CodEquip').AsString]);
    end ;
  end else
    Result := VarArrayOf(['OK', 0, ChaveBloqueado, '']);
end;

function TqsRegistro200.TrocaHD(const Args: array of Variant): Variant;
var 
  A, B : TCabAutorizacao;
  S: String;
begin
  tCli.Active := False;
  tCli.Active := True;
  LI.liLoja :=   Args[0];
  LI.liDetalhes.Add('Senha = ' + Args[1]);
  if (not tCli.FindKey([Args[0]])) then 
    Result := VarArrayOf(['Loja não cadastrada na Nextar'])
  else
  if tCli.FieldByName('Senha').AsString<>Args[1] then
    Result := VarArrayOf(['A senha de registro da loja não está correta'])
  else 
  if tCli.FieldByName('Programa').AsInteger<>1 then
    Result := VarArrayOf(['Software não licenciado'])
  else begin
    LI.liDetalhes.Add('Serial HD anterior = ' + tCli.FieldByName('SerieHD').AsString);
    LI.liHD := Args[2];
    A := TCabAutorizacao.Create;
    B := TCabAutorizacao.Create;
    try
      A.Load(LI.liLoja, tCli , tAut);
      B.AssignFrom(A);
      A.caCodEquip := LI.liHD;
      A.Save('cliente', B, tCli, tAut);
      S := '';
      tAut.IndexName := 'ILoja';
      tAut.SetRange([LI.liLoja, True], [LI.liLoja, True]);
      try
        while not tAut.Eof do begin
          if S>'' then S := S + ';';
          S := S + tAut.FieldByName('Autorizacao').AsString;
          if not tAut.FieldByName('EnviouCli').AsBoolean then begin
            tAut.Edit;
            tAut.FieldByName('EnviouCli').AsBoolean := True;
            tAut.Post;
          end;
          tAut.Next;
        end;
      finally
        tAut.CancelRange;
      end;
      Result := VarArrayOf(['OK', LI.liLoja, S, A.caCodEquip]);
    finally
      A.Free;
      B.Free;
    end;
  end;  
end;

function TqsRegistro200.TrocaProg(const Args: array of Variant): Variant;
var 
  A, B : TCabAutorizacao;
  S: String;
begin
  tCli.Active := False;
  tCli.Active := True;
  LI.liLoja :=   Args[0];
  LI.liDetalhes.Add('Senha = ' + Args[1]);
  if (not tCli.FindKey([Args[0]])) then 
    Result := VarArrayOf(['Loja não cadastrada na Nextar'])
  else
  if tCli.FieldByName('Senha').AsString<>Args[1] then
    Result := VarArrayOf(['A senha de registro da loja não está correta'])
  else 
  if tCli.FieldByName('Programa').AsInteger=1 then
    Result := VarArrayOf(['Licença já foi transferida para o NexCafé'])
  else begin
    LI.liDetalhes.Add('Serial HD anterior = ' + tCli.FieldByName('SerieHD').AsString);
    LI.liHD := Args[2];
    A := TCabAutorizacao.Create;
    B := TCabAutorizacao.Create;
    try
      A.Load(LI.liLoja, tCli , tAut);
      B.AssignFrom(A);
      A.caCodEquip := LI.liHD;
      A.caPrograma := 1;
      A.Save('cliente', B, tCli, tAut);
      S := '';
      tAut.IndexName := 'ILoja';
      tAut.SetRange([LI.liLoja, True], [LI.liLoja, True]);
      try
        while not tAut.Eof do begin
          if S>'' then S := S + ';';
          S := S + tAut.FieldByName('Autorizacao').AsString;
          if not tAut.FieldByName('EnviouCli').AsBoolean then begin
            tAut.Edit;
            tAut.FieldByName('EnviouCli').AsBoolean := True;
            tAut.Post;
          end;
          tAut.Next;
        end;
      finally
        tAut.CancelRange;
      end;
      Result := VarArrayOf(['OK', LI.liLoja, S, A.caCodEquip]);
    finally
      A.Free;
      B.Free;
    end;
  end;  
end;

function TqsRegistro200.AtualizaCadastro(
  const Args: array of Variant): Variant;
begin
  MT.Active := False;
  MT.Active := True;
  MT.AllData := Args[2];
  tCli.Active := False;
  tCli.Active := True;
  LI.liLoja := Args[0];
  LI.liDetalhes.Add('Senha = ' + Args[1]);
  if (not tCli.FindKey([Args[0]])) then 
    Result := VarArrayOf(['Loja não cadastrada na Nextar'])
  else
  if tCli.FieldByName('Senha').AsString<>Args[1] then
    Result := VarArrayOf(['A senha da loja não está correta'])
  else begin
    tCli.Edit;
    TransfDados(MT, tCli, False);
    tCli.FieldByName('AtualizadoEm').AsDateTime := Now;
    tCli.FieldByName('AtualizadoPor').AsString := 'Cliente';
    
    tCli.Post;
    LI.liHD := tCli.FieldByName('SerieHD').AsString;
    Result := VarArrayOf(['OK']);
  end;  
end;

function TqsRegistro200.ObtemCadastro(
  const Args: array of Variant): Variant;
begin
  tCli.Active := True;
  LI.liLoja := Args[0];
  LI.liDetalhes.Add('Senha = ' + Args[1]);
  if (not tCli.FindKey([Args[0]])) then 
    Result := VarArrayOf(['Loja não cadastrada na Nextar'])
  else
  if tCli.FieldByName('Senha').AsString<>Args[1] then
    Result := VarArrayOf(['A senha da loja não está correta'])
  else begin
    MT.Active := True;
    MT.Insert;
    TransfDados(tCli, MT, True);
    MT.Post;
    LI.liHD := tCli.FieldByName('SerieHD').AsString;
    Result := VarArrayOf(['OK', MT.AllData]);
  end;  
end;

function TqsRegistro200.ObtemCodLojaPorEquip(
  const Args: array of Variant): Variant;
begin
  tCli.Active := False;
  tCli.Active := True;
  tCli.IndexName := 'ICodEquip';
  try
    tCli.SetRange([Args[0]], [Args[0]]);
    try
      if tCli.IsEmpty then
        Result := '' else
        Result := EnviaEmailRegistros(tCli);
      if Result='' then
        Result := VarArrayOf(['']) else
        Result := VarArrayOf(['OK', Result]);
    finally
      tCli.CancelRange;
    end;
  finally
    tCli.IndexName := 'ICodigo';
  end;
  
end;

function TqsRegistro200.ObtemCodLojaPorEmail(
  const Args: array of Variant): Variant;
begin
  Result := VarArrayOf(['']);
  if (Args[0]=null) or (Trim(Args[0])='') then Exit;

  qCli.Active := False;
  qCli.SQL.Text := 'select * from cliente where emailreg like ' + QuotedStr('%'+Args[0]+'%');
  qCli.Open;
  try
    if qCli.IsEmpty then
      Result := '' else
      Result := EnviaEmailRegistros(qCli, Args[0]);
    if Result='' then
      Result := VarArrayOf(['']) else
      Result := VarArrayOf(['OK', Result]); 
  finally
    qCli.Active := False;
  end;
end;

procedure TqsRegistro200.kbmMWQueryServiceCreate(Sender: TObject);
begin
  nxDB.AliasPath := '';
  nxDB.AliasName := 'Registro';
  Reg := TRegistro.Create;
  LI := TLogInfo.Create;
  tLog.Open;
  tAut.Open;
  tEst.Open;
  tEstSearch.Open;
  tEstRes.Open;
end;

procedure TqsRegistro200.kbmMWQueryServiceDestroy(Sender: TObject);
begin
  LI.Free;
  Reg.Free;
end;

function TqsRegistro200.LogModoDemo(const Args: array of Variant): Variant;
var S : String;
begin
  S := Args[0];
  LI.liHD := S;
  Result := VarArrayOf(['OK']);
end;


end.






                                            
