unit uRSQSRegistro300;

// =========================================================================
// kbmMW - An advanced and extendable middleware framework.
// by Components4Developers (http://www.components4developers.com)
//
// Service generated by kbmMW service wizard.
//
// INSTRUCTIONS FOR REGISTRATION/USAGE
// -----------------------------------
// Please update the uses clause of the datamodule/form the TkbmMWServer is placed on by adding 
// kbmMWQueryService to it. Eg.
// 
//     uses ...,kbmMWServer,kbmMWQueryService;
// 
// Somewhere in your application, make sure to register the serviceclass to the TkbmMWServer instance. Eg.
// 
// var
//    sd:TkbmMWCustomServiceDefinition;
// ..
//    sd:=kbmMWServer1.RegisterService(yourserviceclassname,false);
// 
// Set the last parameter to true if this is the default service.
// 



{$I kbmMW.inc}

interface

uses
  SysUtils, {$ifdef LEVEL6}Variants,{$endif} Classes, Forms, kbmMWSecurity, kbmMWServer, kbmMWGlobal, kbmMWQueryService, kbmMWNexusDB, kbmMWBinaryStreamFormat,
  kbmMemTable, kbmMWStreamFormat, DB, kbmMWCustomConnectionPool,
  kbmMWCustomDataset, kbmMWResolvers, nxdb, nxllTransport,
  nxptBasePooledTransport, nxtwWinsockTransport, nxsdServerEngine,
  nxreRemoteServerEngine, nxllComponent, uLicEXECryptor, kbmMemBinaryStreamFormat, uRSLogInfo,
  uFreeBoleto, uFreeBoletoImage;

type
  TqsRegistro300 = class(TkbmMWQueryService)
    BSF: TkbmMWBinaryStreamFormat;
    nxDB: TnxDatabase;
    nxSession: TnxSession;
    tCli: TnxTable;
    MT: TkbmMemTable;
    MTCodigo: TIntegerField;
    MTSenha: TStringField;
    MTCadastroEm: TDateTimeField;
    MTCadastroPor: TStringField;
    MTAtualizadoEm: TDateTimeField;
    MTAtualizadoPor: TStringField;
    MTLoja: TStringField;
    MTRazaoSocial: TStringField;
    MTPais: TStringField;
    MTCidade: TStringField;
    MTUF: TStringField;
    MTEndereco: TMemoField;
    MTCEP: TStringField;
    MTBairro: TStringField;
    MTSerieHD: TStringField;
    MTNumMaq: TWordField;
    MTCNPJ: TStringField;
    MTIE: TStringField;
    MTObs: TMemoField;
    MTTelefones: TMemoField;
    MTEmailReg: TMemoField;
    MTFormaPagto: TMemoField;
    MTLicMaq: TWordField;
    MTLicVenc: TDateField;
    MTManInicio: TDateField;
    MTManVenc: TDateField;
    MTProprietarios: TMemoField;
    MTGerente: TStringField;
    MTTipoLoja: TWordField;
    MTEmailTec: TMemoField;
    MTBSF: TkbmBinaryStreamFormat;
    MTLicTipo: TWordField;
    tLog: TnxTable;
    tLogNum: TAutoIncField;
    tLogDataHora: TDateTimeField;
    tLogLoja: TIntegerField;
    tLogDetalhes: TMemoField;
    tLogIP: TStringField;
    tLogOperID: TWordField;
    tLogOK: TBooleanField;
    tLogSerieHD: TStringField;
    tCorpo: TnxTable;
    tAut: TnxTable;
    qCli: TnxQuery;
    tEst: TnxTable;
    tEstSearch: TnxTable;
    tEstID: TAutoIncField;
    tEstLoja: TIntegerField;
    tEstData: TDateField;
    tEstCaixa: TIntegerField;
    tEstDataAtu: TDateTimeField;
    tEstSessoesQtd: TIntegerField;
    tEstSessoesTempo: TFloatField;
    tEstURLs: TIntegerField;
    tEstCodEquip: TStringField;
    tEstSearchID: TAutoIncField;
    tEstSearchLoja: TIntegerField;
    tEstSearchData: TDateField;
    tEstSearchCaixa: TIntegerField;
    tEstSearchCodEquip: TStringField;
    tEstSearchDataAtu: TDateTimeField;
    tEstSearchQtd: TIntegerField;
    tEstSearchPag: TIntegerField;
    tEstSearchEst: TIntegerField;
    tEstRes: TnxTable;
    tEstResLoja: TIntegerField;
    tEstResCodEquip: TStringField;
    tEstResRes: TStringField;
    tEstResQtd: TIntegerField;
    tEstSearchEng: TStringField;
    MTCodAtivacao: TStringField;
    MTAtivado: TBooleanField;
    MTEmailConta: TStringField;
    tPrecos: TnxTable;
    tRec: TnxTable;
    FBI: TFreeBoletoImagem;
    FB: TFreeBoleto;
    tCorpoID: TAutoIncField;
    tCorpoCorpo: TnxMemoField;
    tCorpoDestino: TnxMemoField;
    tCorpoAssunto: TStringField;
    tCorpoInclusao: TDateTimeField;
    tCorpoTipo: TWordField;
    tCorpoEnviarEm: TDateTimeField;
    tCorpoProcessou: TBooleanField;
    tCorpoCType: TStringField;
    tCorpoAnexos: TnxMemoField;
    tRecID: TAutoIncField;
    tRecLoja: TIntegerField;
    tRecVencimento: TDateField;
    tRecPagamento: TDateField;
    tRecValor: TCurrencyField;
    tRecValorPago: TCurrencyField;
    tRecObs: TnxMemoField;
    tRecDoc: TStringField;
    tRecDescricao: TStringField;
    tRecLancamento: TDateTimeField;
    tRecClienteLancou: TBooleanField;
    tRecPremium: TBooleanField;
    tRecPremiumDias: TWordField;
    tRecCancelado: TBooleanField;
    tRecCanceladoEm: TDateTimeField;
    tRecCanceladoPor: TStringField;
    tRecBaixou: TBooleanField;
    tCliCodigo: TAutoIncField;
    tCliTipo: TWordField;
    tCliSenha: TStringField;
    tCliCadastroEm: TDateTimeField;
    tCliCadastroPor: TStringField;
    tCliAtualizadoEm: TDateTimeField;
    tCliAtualizadoPor: TStringField;
    tCliLoja: TStringField;
    tCliRazaoSocial: TStringField;
    tCliPais: TStringField;
    tCliCidade: TStringField;
    tCliUF: TStringField;
    tCliEndereco: TnxMemoField;
    tCliCEP: TStringField;
    tCliBairro: TStringField;
    tCliSerieHD: TStringField;
    tCliCodEquip: TStringField;
    tCliNumMaq: TWordField;
    tCliCNPJ: TStringField;
    tCliIE: TStringField;
    tCliObs: TnxMemoField;
    tCliTelefones: TnxMemoField;
    tCliEmailReg: TnxMemoField;
    tCliFormaPagto: TnxMemoField;
    tCliLicMaq: TWordField;
    tCliLicTipo: TWordField;
    tCliLicVenc: TDateField;
    tCliManInicio: TDateField;
    tCliManVenc: TDateField;
    tCliProprietarios: TnxMemoField;
    tCliGerente: TStringField;
    tCliTipoLoja: TWordField;
    tCliEmailTec: TnxMemoField;
    tCliValor: TCurrencyField;
    tCliValorRec: TCurrencyField;
    tCliEmitirNF: TBooleanField;
    tCliMessenger: TnxMemoField;
    tCliICQ: TnxMemoField;
    tCliUObtemLic: TDateTimeField;
    tCliUVersao: TStringField;
    tCliNegociacao: TWordField;
    tCliStatus: TIntegerField;
    tCliContatarEm: TDateTimeField;
    tCliPrograma: TWordField;
    tCliBloqueado: TBooleanField;
    tCliCliente: TBooleanField;
    tCliAtivado: TBooleanField;
    tCliCodAtivacao: TStringField;
    tCliEmailConta: TStringField;
    tCliAtivadoEm: TDateTimeField;
    tCliTipoConta: TWordField;
    tCliPremiumAte: TDateTimeField;
    procedure kbmMWQueryServiceCreate(Sender: TObject);
    procedure kbmMWQueryServiceDestroy(Sender: TObject);
  private
    LI : TLogInfo;
    Reg : TRegistro;
     { Private declarations }
  protected
     { Private declarations }
    function CriarConta(const Args:array of Variant):Variant; 
    function ChecaConta(const Args:array of Variant):Variant; 
    {Loja: Integer; Versao: String; SerieHD: String; EmDemo: Boolean}

    function EnviaEmailRegistros(D: TDataset; aEmail: String = ''): String;
    
    function TrocaHD(const Args:array of Variant):Variant; 
    function TrocaProg(const Args:array of Variant):Variant;

    function ObtemBP(aLoja: Integer): Integer;
    function ObtemJFP(aLoja: Integer): Boolean;
    
    function AtualizaDadosConta(const Args:array of Variant):Variant; 
    function Ativar(const Args:array of Variant): Variant;
    function ObtemDadosConta(const Args:array of Variant):Variant; 
    function ObtemContaPorEmail(const Args:array of Variant):Variant;
    function ObtemContaPorEquip(const Args:array of Variant):Variant;
    function ObtemSenha(const Args:array of Variant):Variant;
    function ObtemParamAss(const Args:array of Variant): Variant;
    function ObtemDadosCobranca(const Args:array of Variant): Variant;
    function Assinar(const Args:array of Variant): Variant;
    function AlterarSenha(const Args:array of Variant): Variant;
    function ObtemBoletos(const Args:array of Variant): Variant;
    function CancelarBoleto(const Args:array of Variant): Variant;
    
    function SalvaEstInt(
      aConta: String; aCodEquip: String;
      aData: TDateTime; aCaixa, aURLs, aQtdSessoes: Integer; aTempoSessoes: Double; aRes,
      aSearch: String): Boolean;
      
    function SalvaEst(const Args:array of Variant):Variant;
    function ProcessRequest(const Func:string; const ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant; override;
  public
     { Public declarations }
{$IFNDEF CPP}class{$ENDIF} function GetPrefServiceName:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetVersion:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetAuthor:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetAssistance:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetDescriptionAbstract:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetFlags:TkbmMWServiceFlags; override;
  end;

const
  CamposReadOnly =
    '|CODIGO|CADASTROEM|CADASTROPOR|LICMAQ|LICVENC|LICTIPO|MANINICIO|MANVENC|MESSENGER|ICQ|';

  opChecaConta         = 1;
  opObtemDadosConta    = 2;
  opModoDemo           = 3;
  opTrocaHD            = 4;
  opCriarConta         = 5;
  opAtualizaDadosConta = 6;
  opPirata             = 7;
  opUpgradeNex         = 8;
  opObtemContaPorEmail = 9;
  opObtemContaPorEquip = 10;
  opObtemSenha         = 11;
  opSalvaEst           = 12;
  opAtivarConta        = 13;
  opObtemParamAss      = 14;
  opObtemDadosCobranca = 15;
  opAssinar            = 16;
  opAlterarSenha       = 17;
  opObtemBoletos       = 18;
  opCancelarBoleto     = 19;
  
  OpString : Array[opChecaConta..opCancelarBoleto] of String = (
    'ChecaConta      ',
    'ObtemDadosConta ',
    'ModoDemo        ',
    'TrocaHD         ',
    'CriarConta      ',
    'AtualizaConta   ',
    'Pirata',
    'Upgrade para Nex',
    'ContaPorEmail   ',
    'ContaPorEquip   ',
    'ObtemSenha      ',
    'Salva Estat.    ',
    'Ativar Conta    ',
    'Param Assinatura',
    'Obtem Dados Cob.',
    'Assinar         ',
    'Alterar Senha   ',
    'ObtemBoletos    ',
    'CancelarBoleto  ');

implementation

uses uRSDM, nrAutorizacao, uRSServBD, uRSAss;

{$R *.dfm}

const
  TodosNextar = 'todos@nexcafe.com.br';


function ApenasDig(S: String): String;
var I: Integer;
begin
  Result := '';
  for I := 1 to Length(S) do
  if (S[I] in  ['0'..'9']) then
    Result := Result + S[I];
end;

// Service definitions.
//---------------------

{$IFNDEF CPP}class{$ENDIF} function TqsRegistro300.GetPrefServiceName:string;
begin
     Result:='CONTAS';
end;

{$IFNDEF CPP}class{$ENDIF} function TqsRegistro300.GetVersion:string;
begin
     Result:='3.00';
end;

{$IFNDEF CPP}class{$ENDIF} function TqsRegistro300.GetAuthor:string;
begin
     Result:='joao@nextar.com.br';
end;

function TqsRegistro300.EnviaEmailRegistros(D: TDataset; aEmail: String = ''): String;
var
  aReg : TStrings;
  aCorpo : String;
  Venc : Variant;
  i2: Integer;
  aRes, aDest : TStrings;

function VariantToDateStr(V: Variant): String;
begin
  if V=null then
    Result := '' else
    Result := FormatDateTime('dd/mm/yyyy', V);
end;

function Expirou(V: Variant): Boolean;
begin
  Result := (V=null) or (Date<V);
end;
  
function NextEmail(var S: String): String;
var P: Integer;
begin
  S := Trim(S);
  Result := '';
  if S>'' then begin
    for P := 1 to Length(S) do
      if Pos(S[P], ' ,;')>0 then begin
        Result := Copy(S, 1, P-1);
        Delete(S, 1, P);
        Exit;
      end;
    Result := S;
    S := '';  
  end;
  if (Pos('@', Result)<1) or (Pos('.', Result)<1) then
    Result := '';
  if (aEmail>'') and  (not SameText(aEmail, Result)) then
    Result := '';
end;

function EmailsValidos: String;
var 
  SL: TStrings;
  S, S2 : String;
  I : Integer;
begin
  Result := '';
  SL := TStringList.Create;
  try
    SL.Text := D.FieldByName('EmailReg').AsString;
    for I := 0 to SL.Count - 1 do begin
      S := SL[I];
      while S>'' do begin 
        S2 := NextEmail(S);
        if S2>'' then begin
          if Result>'' then
            Result := Result+sLineBreak;
          Result := Result + S2;  
        end;
      end;
    end;
  finally
    SL.Free;
  end;
end;  

procedure AddCorpo(S: String);
begin
  aCorpo := aCorpo+S+sLineBreak;
end;

begin
  Result := '';
  aEmail := Trim(aEmail);
  aRes := TStringList.Create;
  aDest := TStringList.Create;
  
  tAut.Active := True;
  tCorpo.Active := True;
  try
    tAut.IndexName := 'ILoja';
    while not D.Eof do begin
      aDest.Text := EmailsValidos;
      if (aDest.Text>'') and tAut.FindKey([D.FieldByName('Codigo').AsInteger, True]) then 
      begin
        for i2 := 0 to aDest.Count-1 do
          if aRes.IndexOf(aDest[i2])=-1 then
            aRes.Add(aDest[i2]);
          
        tCorpo.Insert;
        tCorpoEnviarEm.Value := EncodeDate(2004, 1, 1);
        tCorpoInclusao.Value := Now;
        tCorpoProcessou.Value := False;
        tCorpoDestino.Value := aDest.Text;
        tCorpoAssunto.Value := 'NexCafé - Dados da sua Conta';
        aCorpo := '';
        AddCorpo('Conta criada em ' + D.FieldByName('CadastroEm').AsString +':');
        AddCorpo('');
        AddCorpo('Nome da Loja: ' + D.FieldByName('Loja').AsString);
        AddCorpo('Proprietario: ' + D.FieldByName('Proprietarios').AsString);

        if tAut.FieldByName('Tipo').AsInteger<>ectcFreePremium then
          AddCorpo('Qtd.Máquinas: ' + tAut.FieldByName('Maquinas').AsString);
        AddCorpo('Cidade......: ' + D.FieldByName('Cidade').AsString);
        AddCorpo('');
        if D.FieldByName('EmailConta').AsString>'' then
          AddCorpo('Conta: '+D.FieldByName('EmailConta').AsString) else
          AddCorpo('Conta: ' + CodLojaToStr(D.FieldByName('Codigo').AsInteger));
        AddCorpo('Senha: ' + D.FieldByName('Senha').AsString);
        AddCorpo('');
        Venc := tAut.FieldByName('Vencimento').AsVariant;
        case tAut.FieldByName('Tipo').AsInteger of
          taDefinitiva : AddCorpo('Licença Definitiva: Nunca Expira');
          
          taLocacao : 
            if Expirou(Venc) then 
              AddCorpo('Locação expirou em: ' + VariantToDateStr(Venc)) else
              AddCorpo('Locação vence em: ' + VariantToDateStr(Venc));

          taTesteGratuito :    
            if Expirou(Venc) then 
              AddCorpo('Licença de Teste Gratuito Expirou em: ' + VariantToDateStr(Venc)) else
              AddCorpo('Licença de Teste Gratuito Expira em: ' + VariantToDateStr(Venc));

          taTemporaria :    
            if Expirou(Venc) then 
              AddCorpo('Licença Temporária Expirou em: ' + VariantToDateStr(Venc)) else
              AddCorpo('Licença Temporária Expira em: ' + VariantToDateStr(Venc));

          taFreePremium :
            if Venc>0 then
            if Expirou(Venc) then
              AddCorpo('Assinatura PREMIUM venceu em: ' + VariantToDateStr(Venc)) else
              AddCorpo('Assinatura PREMIUM vence em: ' + VariantToDateStr(Venc));
        end;
        tCorpoCorpo.Value := aCorpo;
        
        tCorpo.Post;
      end;
      D.Next;
    end;
    Result := aRes.Text;
  finally
    aRes.Free;
    aDest.Free;
  end;
end;

{$IFNDEF CPP}class{$ENDIF} function TqsRegistro300.GetAssistance:string;
begin
     Result:='suporte@nextar.com.br';
end;

{$IFNDEF CPP}class{$ENDIF} function TqsRegistro300.GetDescriptionAbstract:string;
begin
     Result:='Servidor de Contas NexCafé';
end;

{$IFNDEF CPP}class{$ENDIF} function TqsRegistro300.GetFlags:TkbmMWServiceFlags;
begin
     Result:=[mwsfListed];
end;

function TqsRegistro300.ProcessRequest(const Func: string;
  const ClientIdent: TkbmMWClientIdentity;
  const Args: array of Variant): Variant;
var 
  uFunc : String;  
begin
  Inc(nRequests[1]);

  uFunc := UpperCase(Func);
  try
    try
      tLog.Active := True;
    except
    end;  
    if uFunc='CRIARCONTA' then begin
      LI.Inicia(opCriarConta, ClientIdent.RemoteLocation);
      Result := CriarConta(Args);
    end else
    if uFunc='CHECACONTA' then begin
      LI.Inicia(opChecaConta, ClientIdent.RemoteLocation);
      Result := ChecaConta(Args);
    end else  
    if uFunc='TROCAHD' then begin
      LI.Inicia(opTrocaHD, ClientIdent.RemoteLocation);
      Result := TrocaHD(Args)
    end else  
    if uFunc='UPGRADENEX' then begin
      LI.Inicia(opUpgradeNex, ClientIdent.RemoteLocation);
      Result := TrocaProg(Args)
    end else  
    if uFunc='ATUALIZADADOSCONTA' then begin
      LI.Inicia(opAtualizaDadosConta, ClientIdent.RemoteLocation);
      Result := AtualizaDadosConta(Args);
    end else  
    if uFunc='OBTEMDADOSCONTA' then begin
      LI.Inicia(opObtemDadosConta, ClientIdent.RemoteLocation);
      Result := ObtemDadosConta(Args);
    end else 
    if uFunc='OBTEMCONTAPOREMAIL' then begin
      LI.Inicia(opObtemContaPorEmail, ClientIdent.RemoteLocation);
      Result := ObtemContaPorEmail(Args);
    end else
    if uFunc='OBTEMCONTAPOREQUIP' then begin
      LI.Inicia(opObtemContaPorEquip, ClientIdent.RemoteLocation);
      Result := ObtemContaPorEquip(Args);
    end else
    if uFunc='OBTEMSENHA' then begin
      LI.Inicia(opObtemSenha, ClientIdent.RemoteLocation);
      Result := ObtemSenha(Args);
    end else
    if uFunc='SALVAEST' then begin
      LI.Inicia(opSalvaEst, ClientIdent.RemoteLocation);
      Result := SalvaEst(Args);
    end else
    if uFunc='ATIVARCONTA' then begin
      LI.Inicia(opAtivarConta, ClientIdent.RemoteLocation);
      Result := Ativar(Args);
    end else
    if uFunc='OBTEMPARAMASS' then begin
      LI.Inicia(opObtemParamAss, ClientIdent.RemoteLocation);
      Result := ObtemParamAss(Args);
    end else
    if uFunc='OBTEMDADOSCOBRANCA' then begin
      LI.Inicia(opObtemDadosCobranca, ClientIdent.RemoteLocation);
      Result := ObtemDadosCobranca(Args);
    end else
    if uFunc='ASSINAR' then begin
      LI.Inicia(opAssinar, ClientIdent.RemoteLocation);
      Result := Assinar(Args);
    end else
    if uFunc='ALTERARSENHA' then begin
      LI.Inicia(opAlterarSenha, ClientIdent.RemoteLocation);
      Result := AlterarSenha(Args);
    end else
    if uFunc='CANCELARBOLETO' then begin
      LI.Inicia(opCancelarBoleto, ClientIdent.RemoteLocation);
      Result := CancelarBoleto(Args);
    end else
    if uFunc='OBTEMBOLETOS' then begin
      LI.Inicia(opObtemBoletos, ClientIdent.RemoteLocation);
      Result := ObtemBoletos(Args);
    end else
      Result := inherited ProcessRequest(Func, ClientIdent, Args)
  except
    On E: Exception do
      Result := VarArrayOf(['Erro não esperado no servidor de contas Nextar: ' + E.Message + 
                            sLineBreak+sLineBreak+
                            '. Por favor entre em contato através da opção de atendimento online do nosso site: www.nexcafe.com.br']);
  end;  
  try 
    if Result[0] = 'OK' then
      LI.liOK := True
    else begin 
      LI.liOK := False;
      LI.liDetalhes.Add('RESULTADO = ' + Result[0]);
    end;  
  except
  end;
  
  if LI.liOper <> opChecaConta then 
    LI.SaveToDataset(tLog);  
end;

function TqsRegistro300.SalvaEst(const Args: array of Variant): Variant;
begin
  Result := SalvaEstInt(Args[0], Args[1], Args[2], Args[3], Args[4], Args[5], Args[6], Args[7], Args[8]);
end;

function TqsRegistro300.SalvaEstInt(aConta: String; aCodEquip: String;
  aData: TDateTime; aCaixa, aURLs, aQtdSessoes: Integer; aTempoSessoes: Double;
  aRes, aSearch: String): Boolean;
var 
  Achou : Boolean; 
  SL : TStrings; 
  I: Integer;
  aCodLoja : Integer;
  cTipo : Char;
  sEng: String;
begin
  InitTran(nxDB, [tCli, tEst, tEstSearch, tEstRes], True);
  try
    tEstSearch.IndexName := 'IEstEng';
    Reg.Conta := aConta;
    if Reg.CodLoja>0 then
      aCodLoja := Reg.CodLoja
    else 
    if (Trim(aConta)>'') and tCli.Locate('EmailConta', aConta, []) then
      aCodLoja := tCli.FieldByName('Codigo').AsInteger else
      aCodLoja := 0;
      
    if aCodLoja>0 then begin
      tEst.IndexName := 'ILojaCaixa';
      Achou := tEst.FindKey([aCodLoja, aCaixa]);
    end else begin
      tEst.IndexName := 'ICodEquipCaixa';
      Achou := tEst.FindKey([aCodEquip, aCaixa]);
    end;
    if Achou then begin
      while tEstSearch.FindKey([tEstID.Value]) do tEstSearch.Delete;
      if aCodLoja>0 then begin
        tEstRes.IndexName := 'ILojaRes';
        while tEstRes.FindKey([aCodLoja]) do tEstRes.Delete;
      end else begin
        tEstRes.IndexName := 'ICodEquipRes';
        while tEstRes.FindKey([aCodEquip]) do tEstRes.Delete;
      end;
      tEst.Edit;
    end else 
      tEst.Insert;
    tEstLoja.Value := aCodLoja;
    tEstCodEquip.Value := aCodEquip;
    tEstData.Value := aData;
    tEstCaixa.Value := aCaixa;
    tEstURLs.Value := aURLs;
    tEstSessoesQtd.Value := aQtdSessoes;
    tEstSessoesTempo.Value := aTempoSessoes;  
    tEstDataAtu.Value := Now;
    tEst.Post;
    SL := TStringList.Create;
    try
      SL.Text := aRes;
      for I := 0 to SL.Count - 1 do begin
        tEstRes.Insert;
        tEstResLoja.Value := aCodLoja;
        tEstResCodEquip.Value := aCodEquip;
        tEstResRes.Value := SL.Names[I];
        tEstResQtd.Value := StrToIntDef(SL.ValueFromIndex[I], 0);
        tEstRes.Post;
      end;
  
      SL.Text := aSearch;
      for I := 0 to SL.Count - 1 do begin
        sEng := SL.Names[I];
        if sEng>'' then
          cTipo := sEng[1] else
          cTipo := #0;
        Delete(sEng, 1, 2);
        
        if (sEng>'') and (cTipo<>#0) then begin
          if tEstSearch.FindKey([tEstID.Value, sEng]) then
            tEstSearch.Edit else
            tEstSearch.Insert;
          tEstSearchEng.Value := sEng;
          tEstSearchLoja.Value := aCodLoja;
          tEstSearchCodEquip.Value := aCodEquip;
          tEstSearchData.Value := aData;
          tEstSearchCaixa.Value := aCaixa;
          tEstSearchEst.Value := tEstID.Value;
          tEstSearchDataAtu.Value := tEstDataAtu.Value;
          case cTipo of
            'q' : tEstSearchQtd.Value := StrToIntDef(SL.ValueFromIndex[I], 0);
            'p' : tEstSearchPag.Value := StrToIntDef(SL.ValueFromIndex[I], 0);
          end;
          tEstSearch.Post;
        end;
      end;
    finally
      SL.Free;
    end;
    nxDB.Commit;
  except
    nxDB.Rollback;
    Raise;
  end;
  Result := True;
end;

procedure TransfDados(O, D: TDataset; Tudo: Boolean);
var 
  I : Integer;
  F : TField;
begin
  for I := 0 to D.FieldCount-1 do with D.Fields[I] do 
  if Tudo or ((DataType<>ftAutoInc) and (Pos('|'+UpperCase(FieldName)+'|', CamposReadOnly)=0)) then 
  begin
    F := O.FindField(FieldName);
    if F<>nil then
      Value := F.Value;
  end;  
end;

function GeraCodAtivacao: String;
var 
  I : Integer;
  S : String;
begin
  S := IntToStr(Random(9999999));
  Result := '';
  for I := 1 to Length(S) do
    Result := S[I] + Result;
  while Length(Result)<7 do
    Result := Result + IntToStr(Random(9)); 
end;

function TqsRegistro300.CriarConta(
  const Args: array of Variant): Variant;
var 
  SIndex : String;
  SLE : TStrings;
  S : String;
  Dia : TDateTime;
  A, B: TCabAutorizacao;
  I: Integer;
  SL: TStringList;
begin
  A := TCabAutorizacao.Create;
  B := TCabAutorizacao.Create;
  SL := TStringList.Create;
  try
    SL.Text := Args[0];
    if tCli.Locate('EmailConta', SL.Values['Email'], []) then begin
      Result := VarArrayOf(['Já existe uma conta com o e-mail "' + SL.Values['Email'] + 
                            '". É necessário um e-mail diferente para cada loja.']);         
      Exit;
    end;     
      
    tCli.Active := False;
    tCli.Active := True;
    tCli.Insert;
    tCli.FieldByName('Loja').AsString := Sl.Values['Nome'];
    tCli.FieldByname('Proprietarios').AsString := Sl.Values['Prop'];
    tCli.FieldByName('Pais').AsString := Sl.Values['Pais'];
    tCli.FieldByName('Cidade').AsString := sl.Values['Cidade'];
    tCli.FieldByName('UF').AsString := sl.Values['UF'];
    tCli.FieldByName('CodEquip').AsString := SL.Values['CodEquip'];
    tCli.FieldByName('EmailReg').AsString := SL.Values['Email'];
    tCli.FieldByName('EmailConta').AsString := SL.Values['Email'];
    tCli.FieldByName('LicMaq').AsInteger := 1;
    tCli.FieldByName('Senha').AsString := sl.Values['Senha'];
    tCli.FieldByName('CadastroEm').AsDateTime := Now;
    tCli.FieldByName('CadastroPor').AsString := 'Cliente';
    tCli.FieldByName('AtualizadoEm').AsDateTime := Now;
    tCli.FieldByName('AtualizadoPor').AsString := 'Cliente';
    tCli.FieldByName('Programa').AsInteger := 1;
    tCli.FieldByName('Ativado').AsBoolean := False;
    tCli.FieldByName('CodAtivacao').AsString := GeraCodAtivacao;
    tCli.Post;
    LI.liLoja := tCli.FieldByName('Codigo').AsInteger;
    Reg.CodLoja := LI.liLoja;
    A.Load(tCli.FieldByName('Codigo').AsInteger, tCli, tAut);
    B.AssignFrom(A);
    with A.NewItem do begin
      auTipo := taFreePremium;
      auMaquinas := 1;
      auVencimento := 0;
    end;
    A.Save('cliente', B, tCli, tAut);
    LI.liLoja := tCli.FieldByName('Codigo').AsInteger;
    LI.liHD := A.caCodEquip;
    tAut.IndexName := 'ILoja';
    if not tAut.FindKey([ LI.liLoja, True]) then
      Result := VarArrayOf(['Falha no servidor de contas Nextar. Por favor faça contato através da opção de atendimento online do nosso site: www.nexcafe.com.br']) else
      Result := VarArrayOf(['OK', SL.Values['Email'], ChaveAtivar]);
    SLE := TStringList.Create;
    try
      tCorpo.Active := True;
      S := ExtractFilePath(ParamStr(0)) + 'emailativacao.txt';
      if FileExists(S) then begin
        SLE.LoadFromFile(S);
        S := SLE.Text;

        repeat
          I := Pos('%EMAIL', S);
          if I>0 then
            S := Copy(S, 1, I-1) + tCli.FieldByName('EmailConta').AsString + Copy(S, I+6, Length(S));
        until (I<1);

        repeat
          I := Pos('%CODATIVACAO', S);
          if I>0 then
            S := Copy(S, 1, I-1) + tCli.FieldByName('CodAtivacao').AsString + Copy(S, I+12, Length(S));
        until (I<1);
        
        tCorpo.Insert;
        tCorpoEnviarEm.Value := EncodeDate(2004, 1, 1);
        tCorpoInclusao.Value := Now;
        tCorpoProcessou.Value := False;
        tCorpoDestino.Value := tCli.FieldByName('EmailConta').AsString;
        tCorpoAssunto.Value := 'NexCafé: Código de Ativação';
        tCorpoCorpo.Value := S;
        tCorpo.Post;
        SLE.Clear;
      end;
      
      tCorpo.Insert;
      tCorpoEnviarEm.Value := EncodeDate(2004, 1, 1);
      tCorpoInclusao.Value := Now;
      tCorpoProcessou.Value := False;
      tCorpoDestino.Value := TodosNextar;
      tCorpoAssunto.Value := 'NexCafé - Nova Conta!';
      SLE.Add('Conta criada em ' + FormatDateTime('dd/mm/yyyy hh:mm', Now));
      SLE.Add('');
      SLE.Add('Loja = ' + tCli.FieldByName('Loja').AsString);
      SLE.Add('Código = ' + CodLojaToStr(tCli.FieldByName('Codigo').AsInteger));
      SLE.Add('Código de Equipamento = ' + tCli.FieldByName('CodEquip').AsString);
      SLE.Add('Proprietario = ' + tCli.FieldByName('Proprietarios').AsString);
      SLE.Add('Cidade = ' + tCli.FieldByName('Cidade').AsString + '/' + tCli.FieldByName('UF').AsString);
      SLE.Add('');
      SLE.Add('Email = ' + tCli.FieldByname('EmailConta').AsString);
      SLE.Add('Senha = ' + tCli.FieldByName('Senha').AsString);
      SLE.Add('Código de Ativação = ' + tCli.FieldByName('CodAtivacao').AsString);
      tCorpoCorpo.Value := SLE.Text;
      tCorpo.Post;
    except
    end;
    SLE.Free;
    tCorpo.Active := False;
  finally
    SL.Free;
    A.Free;
    B.Free;
  end;    
end;

function TqsRegistro300.ObtemSenha(const Args: array of Variant): Variant;
begin
  Reg.Conta := Args[0];

  tCli.Active := False;
  tCli.Active := True;
  if Reg.CodLoja>0 then begin
    tCli.IndexName := 'ICodigo';
    tCli.SetRange([Args[0]], [Args[0]]);
  end else begin
    tCli.IndexName := 'IEmailConta';
    tCli.SetRange([Reg.Conta], [Reg.Conta]);
  end;
  try
    try
      if not tCli.IsEmpty then
        Result := EnviaEmailRegistros(tCli);
        
      if Result='' then
        Result := VarArrayOf(['']) else
        Result := VarArrayOf(['OK', Result]); 
    finally
      tCli.CancelRange;
    end;
  finally
    tCli.IndexName := 'ICodigo';
  end;
end;

function TqsRegistro300.CancelarBoleto(const Args: array of Variant): Variant;
var N: TDateTime;
begin  
  tCli.Active := False;
  tCli.Active := True;
  tRec.Active := False;
  tRec.Active := True;
  Reg.Conta := Args[0];
  LI.liDetalhes.Add('Conta = ' + Args[0]);
  LI.liDetalhes.Add('Senha = '  +Args[1]);
  LI.liLoja := 0;
  if (Reg.CodLoja=0) and not tCli.Locate('EmailConta', Reg.Conta, []) then
  begin
    Result := VarArrayOf(['Conta inexistente']);
    Exit;
  end;

  if (Reg.CodLoja>0) and not tCli.Locate('Codigo', Reg.CodLoja, []) then
  begin
    Result := VarArrayOf(['Conta inexistente']);
    Exit;
  end;

  LI.liLoja := tCli.FieldByName('Codigo').AsInteger;
  
  if (not SameText(tCli.FieldByName('Senha').AsString, Args[1])) then
  begin
    Result := VarArrayOf(['Senha incorreta']);
    Exit;
  end;

  if not tRec.Locate('ID', Args[2], []) then begin
    Result := VarArrayOf(['Boleto não encontrado']);
    Exit;
  end;

  if tRecCancelado.Value then begin
    Result := VarArrayOf(['Esse boleto já foi cancelado em ' + FormatDateTime('dd/mm/yyyy', tRecCanceladoEm.Value)]);
    Exit;
  end;

  if tRecLoja.Value <> LI.liLoja then begin
    Result := VarArrayOf(['Esse boleto é de outra loja']);
    Exit;
  end;

  N := Now;
  
  tRec.Edit;
  tRecCancelado.Value := True;
  tRecCanceladoEm.Value := N;
  tRecCanceladoPor.Value := 'cliente';
  tRecPagamento.Value := N;
  tRecBaixou.Value := True;
  tRec.Post;

  Result := VarArrayOf(['OK', N]);
end;

function TqsRegistro300.ChecaConta(
  const Args: array of Variant): Variant;
    {Conta: String; Versao: String; SerieHD: String; EmDemo: Boolean}
var S: String;  
begin
  tCli.Active := False;
  tCli.Active := True;
  Reg.Conta := Args[0];

  if Reg.CodLoja>0 then
    LI.liLoja := Reg.CodLoja
  else 
  if tCli.Locate('EmailConta', Reg.Conta, []) then
    LI.liLoja := tCli.FieldByName('Codigo').AsInteger
  else
    LI.liLoja := 0;    
  
  LI.liOper := opChecaConta;
    
  LI.liDetalhes.Add('Versão NexServ = ' + Args[1]); 

  tAut.IndexName := 'ILoja'; 
  
  if LI.liLoja>0 then begin
    if (not tCli.FindKey([LI.liLoja])) then
      Result := VarArrayOf(['OK', Reg.Conta, ChaveInexistente, ''])
    else
    if (tCli.FieldByName('Bloqueado').AsBoolean=True) or
       (not tAut.FindKey([LI.liLoja, True])) 
    then  
      Result := VarArrayOf(['OK', Reg.Conta, ChaveBloqueado, ''])
    else
    if tCli.FieldByName('Programa').AsInteger=0 then
      Result := VarArrayOf(['OK', Args[0], ChaveCybermgr, ''])
    else
    if not tCli.FieldByname('Ativado').AsBoolean then
      Result := VarArrayOf(['OK', Reg.Conta, ChaveAtivar, ''])
    else begin
      S := '';
      tAut.IndexName := 'ILoja';
      tAut.SetRange([LI.liLoja, True], [LI.liLoja, True]);
      try
        while not tAut.Eof do begin
          if S>'' then S := S + ';';
          S := S + tAut.FieldByName('Autorizacao').AsString;
          if not tAut.FieldByName('EnviouCli').AsBoolean then begin
            tAut.Edit;
            tAut.FieldByName('EnviouCli').AsBoolean := True;
            tAut.Post;
          end;
          tAut.Next;
        end;
      finally
        tAut.CancelRange;
      end;
      
      tCli.Edit;
      tCli.FieldByName('UObtemLic').AsDateTime := Now;
      tCli.FieldByName('UVersao').AsString := Args[1];
      tCli.Post;
      Result := VarArrayOf(['OK', Args[0], S, ObtemBP(LI.liLoja), ObtemJFP(LI.liLoja)]);
    end ;
  end else
    Result := VarArrayOf(['OK', 0, ChaveInexistente, 0, False]);
end;

function TqsRegistro300.TrocaHD(const Args: array of Variant): Variant;
var 
  A, B : TCabAutorizacao;
  S: String;
  aLoja: Integer;
begin
  tCli.Active := False;
  tCli.Active := True;
  Reg.Conta := Args[0];
  LI.liLoja := Reg.CodLoja;

  if (Reg.CodLoja=0) and not tCli.Locate('EmailConta', Reg.Conta, []) then
    Result := 'Conta inexistente'
  else
  if (Reg.CodLoja>0) and not tCli.Locate('Codigo', Reg.CodLoja, []) then
    Result := VarArrayOf(['Conta inexistente'])
  else
  if tCli.FieldByName('Senha').AsString<>Args[1] then
    Result := VarArrayOf(['Senha incorreta'])
  else 
  if tCli.FieldByName('Programa').AsInteger<>1 then
    Result := VarArrayOf(['Conta inválida para uso no NexCafé'])
  else begin
    LI.liLoja :=   tCli.FieldByName('Codigo').AsInteger;
    LI.liDetalhes.Add('Senha = ' + Args[1]);
    LI.liDetalhes.Add('Serial HD anterior = ' + tCli.FieldByName('SerieHD').AsString);
    LI.liHD := Args[2];
    A := TCabAutorizacao.Create;
    B := TCabAutorizacao.Create;
    try
      A.Load(LI.liLoja, tCli , tAut);
      B.AssignFrom(A);
      A.caCodEquip := LI.liHD;
      A.Save('cliente', B, tCli, tAut);
      S := '';
      tAut.IndexName := 'ILoja';
      tAut.SetRange([LI.liLoja, True], [LI.liLoja, True]);
      try
        while not tAut.Eof do begin
          if S>'' then S := S + ';';
          S := S + tAut.FieldByName('Autorizacao').AsString;
          if not tAut.FieldByName('EnviouCli').AsBoolean then begin
            tAut.Edit;
            tAut.FieldByName('EnviouCli').AsBoolean := True;
            tAut.Post;
          end;
          tAut.Next;
        end;
      finally
        tAut.CancelRange;
      end;
      Result := VarArrayOf(['OK', Args[0], S, ObtemBP(LI.liLoja), ObtemJFP(LI.liLoja)]);
    finally
      A.Free;
      B.Free;
    end;
  end;  
end;

function TqsRegistro300.TrocaProg(const Args: array of Variant): Variant;
var 
  A, B : TCabAutorizacao;
  S: String;
begin
  tCli.Active := False;
  tCli.Active := True;
  LI.liLoja :=   Args[0];
  LI.liDetalhes.Add('Senha = ' + Args[1]);
  tCli.IndexName := 'ICodigo';
  if (not tCli.FindKey([Args[0]])) then 
    Result := VarArrayOf(['Loja não cadastrada na Nextar'])
  else
  if tCli.FieldByName('Senha').AsString<>Args[1] then
    Result := VarArrayOf(['A senha de registro da loja não está correta'])
  else 
  if tCli.FieldByName('Programa').AsInteger=1 then
    Result := VarArrayOf(['Licença já foi transferida para o NexCafé'])
  else begin
    LI.liDetalhes.Add('Serial HD anterior = ' + tCli.FieldByName('SerieHD').AsString);
    LI.liHD := Args[2];
    A := TCabAutorizacao.Create;
    B := TCabAutorizacao.Create;
    try
      A.Load(LI.liLoja, tCli , tAut);
      B.AssignFrom(A);
      A.caCodEquip := LI.liHD;
      A.caPrograma := 1;
      A.Save('cliente', B, tCli, tAut);
      S := '';
      tAut.IndexName := 'ILoja';
      tAut.SetRange([LI.liLoja, True], [LI.liLoja, True]);
      try
        while not tAut.Eof do begin
          if S>'' then S := S + ';';
          S := S + tAut.FieldByName('Autorizacao').AsString;
          if not tAut.FieldByName('EnviouCli').AsBoolean then begin
            tAut.Edit;
            tAut.FieldByName('EnviouCli').AsBoolean := True;
            tAut.Post;
          end;
          tAut.Next;
        end;
      finally
        tAut.CancelRange;
      end;
      Result := VarArrayOf(['OK', LI.liLoja, S, 0, False]);
    finally
      A.Free;
      B.Free;
    end;
  end;  
end;

function TqsRegistro300.AlterarSenha(const Args: array of Variant): Variant;
begin
  tCli.Active := False;
  tCli.Active := True;
  Reg.Conta := Args[0];
  LI.liLoja := Reg.CodLoja;
  LI.liDetalhes.Add('Conta = ' + Args[0]);
  LI.liDetalhes.Add('Senha = ' + Args[1]);
  LI.liDetalhes.Add('Nova Senha = ' + Args[2]);
  

  if (Reg.CodLoja=0) and not tCli.Locate('EmailConta', Reg.Conta, []) then
  begin
    Result := VarArrayOf(['Conta inexistente']);
    Exit;
  end;

  if (Reg.CodLoja>0) and not tCli.Locate('Codigo', Reg.CodLoja, []) then
  begin
    Result := VarArrayOf(['Conta inexistente']);
    Exit;
  end;

  LI.liLoja := tCli.FieldByName('Codigo').AsInteger;
  
  if (not SameText(tCli.FieldByName('Senha').AsString, Args[1])) then
  begin
    Result := VarArrayOf(['Senha atual está incorreta']);
    Exit;
  end;
  
  tCli.Edit;
  tCli.FieldByName('Senha').AsString := Args[2];
  tCli.Post;

  Result := VarArrayOf(['OK']);
end;

function TqsRegistro300.Assinar(const Args: array of Variant): Variant;
var 
  SL, SL2 : TStringList;
  S, ArqBol : String;
  B : TDadosBoleto;
  D : TDadosEmissaoBol;
  I : Integer;
begin
  tCli.Active := False;
  tCli.Active := True;
  Reg.Conta := Args[0];
  LI.liLoja := 0;
  LI.liOper := opAssinar;
  LI.liDetalhes.Add('Conta = ' + Reg.Conta);
  LI.liDetalhes.Add('Senha = ' + Args[1]);
  if not tCli.Locate('EmailConta', Reg.Conta, []) then begin
    Result := VarArrayOf(['Conta inexistente']);
    Exit;
  end;
  LI.liLoja := tCli.FieldByName('Codigo').AsInteger;
  if not SameText(tCli.FieldByName('Senha').AsString, Args[1]) then begin
    Result := VarArrayOf(['Senha Incorreta']);
    Exit;
  end;
  if not tPrecos.Locate('Meses', Args[2], []) then begin
    Result := VarArrayOf(['Tipo de assinatura inválido']);
    Exit;
  end;
  
  SL := TStringList.Create;  SL2 := TStringList.Create;
  try
    InitTran(nxDB, [tCli, tRec], True);
    try
      SL.Text := Args[3];
      tCli.Edit;
      tCli.FieldByName('RazaoSocial').AsString := SL.Values['RazaoSocial'];
      tCli.FieldByName('CNPJ').AsString := SL.Values['CNPJ'];
      tCli.FieldByName('IE').AsString := SL.Values['IE'];
      tCli.FieldByName('Endereco').AsString := SL.Values['Endereco'];
      tCli.FieldByName('Cidade').AsString := SL.Values['Cidade'];
      tCli.FieldByName('UF').AsString := SL.Values['UF'];
      tCli.FieldByName('CEP').AsString := SL.Values['CEP'];
      tCli.FieldByName('Bairro').AsString := SL.Values['Bairro'];
      
      if Trim(SL.Values['Tel1'])>'' then
        sl2.Add(SL.Values['Tel1']);
      if Trim(SL.Values['Tel2'])>'' then
        sl2.Add(SL.Values['Tel2']);
      if Trim(SL.Values['Tel3'])>'' then
        sl2.Add(SL.Values['Tel3']);
      if Trim(SL.Values['Tel4'])>'' then
        sl2.Add(SL.Values['Tel4']);
      tCli.FieldByName('Telefones').AsString := sl2.Text;
      tCli.Post;

      tRec.Append;
      tRec.FieldByName('Premium').AsBoolean := True;
      tRec.FieldByName('Loja').AsInteger := LI.liLoja;
      tRec.FieldByName('Vencimento').AsDateTime := Date + 7;
      tRec.FieldByName('Lancamento').AsDateTime := Now;
      tRec.FieldByName('Valor').AsCurrency := tPrecos.FieldByName('Valor').AsCurrency;
      tRec.FieldByName('Premium').AsBoolean := True;
      tRec.FieldByName('ClienteLancou').AsBoolean := True;
      tRec.FieldByName('PremiumDias').AsInteger := tPrecos.FieldByName('Meses').AsInteger * 30;
      tRec.FieldByName('Descricao').AsString := tPrecos.FieldByName('Descr').AsString;
      tRec.Post;

      tRec.Edit;
      FB.Vencimento := tRec.FieldByName('Vencimento').AsDateTime;
      FB.DataDocumento := tRec.FieldByName('Lancamento').AsDateTime;
      FB.Valor := tRec.FieldByName('Valor').AsCurrency;
      FB.NossoNumero := tRec.FieldByName('ID').AsString;
      FB.Documento := tRec.FieldByName('ID').AsString;
      FB.Instrucoes.Text := tPrecos.FieldByName('Descr').AsString;

      FB.Sacado.Nome := SL.Values['RazaoSocial'];
      if Length(ApenasDig(SL.Values['CNPJ']))>11 then
        FB.Sacado.Pessoa := pJuridica else
        FB.Sacado.Pessoa := pFisica;
      FB.Sacado.CNPJ_CPF := ApenasDig(SL.Values['CNPJ']);  
      FB.Sacado.Endereco := SL.Values['Endereco'];
      FB.Sacado.Estado := SL.Values['UF'];
      FB.Sacado.Cidade := SL.Values['Cidade'];
      FB.Sacado.Cep  := SL.Values['CEP'];
      FB.Sacado.Bairro := SL.Values['Bairro'];
      FB.Preparar;

      ArqBol := 'Boleto'+tRec.FieldByName('ID').AsString+'.jpg';
      
      FBI.SaveBoletoImagem(ArqBol, 0);
      tRec.FieldByName('Doc').Value := FB.DadosGerados.LinhaDigitavel;
      tRec.Post;

      B.dbVenc := FB.Vencimento;
      B.dbLanc := FB.DataDocumento;
      B.dbNum := tRecID.AsInteger;
      B.dbValor := FB.Valor;
      B.dbDescr := FB.Instrucoes.Text;
      B.dbPagoEm := 0;
      B.dbCanceladoEm := 0;
      
      D.deNome := SL.Values['RazaoSocial'];
      D.deCNPJ  := SL.Values['CNPJ'];
      D.deEnd := SL.Values['Endereco'];
      D.deCidade := SL.Values['Cidade'];
      D.deUF := SL.Values['UF'];
      D.deCedente := FB.Cedente.Nome;

      nxDB.Commit;

      try
        tCorpo.Active := True;
        S := ExtractFilePath(ParamStr(0)) + 'email_assinatura.txt';
        if FileExists(S) then begin
          SL.LoadFromFile(S);
          S := SL.Text;
  
          repeat
            I := Pos('%NOMEASS', S);
            if I>0 then
              S := Copy(S, 1, I-1) + tPrecos.FieldByName('Descr').AsString + Copy(S, I+8, Length(S));
          until (I<1);
  
          repeat
            I := Pos('%VENCIMENTO', S);
            if I>0 then
              S := Copy(S, 1, I-1) + FormatDateTime('dd/mm/yyyy', B.dbVenc) + Copy(S, I+11, Length(S));
          until (I<1);
  
          repeat
            I := Pos('%ID', S);
            if I>0 then
              S := Copy(S, 1, I-1) + tRec.FieldByName('ID').AsString + Copy(S, I+3, Length(S));
          until (I<1);
          
          repeat
            I := Pos('%NUMBOLETO', S);
            if I>0 then
              S := Copy(S, 1, I-1) + tRec.FieldByName('Doc').AsString + Copy(S, I+10, Length(S));
          until (I<1);
  
          repeat
            I := Pos('%VALOR', S);
            if I>0 then
              S := Copy(S, 1, I-1) + FloatToStrF(B.dbValor, ffCurrency, 10, 2) + Copy(S, I+6, Length(S));
          until (I<1);
          
          tCorpo.Insert;
          tCorpoEnviarEm.Value := EncodeDate(2004, 1, 1);
          tCorpoInclusao.Value := Now;
          tCorpoProcessou.Value := False;
          tCorpoDestino.Value := tCli.FieldByName('EmailConta').AsString;
          tCorpoAssunto.Value := 'NexCafé - Boleto de Assinatura';
          tCorpoCorpo.Value := S;
          tCorpoAnexos.Value := 'boleto.jpg='+ArqBol;
          tCorpo.Post;
  
        end;
        SL.Text := Args[3];
        
        SL.Insert(0, 'Conta = ' + Args[0]);
        SL.Insert(1, 'Num.Pedido = '  + tRec.FieldByName('ID').AsString);
        SL.Insert(2, 'Valor = ' + tPrecos.FieldByName('Valor').AsString);
        SL.Insert(3, tPrecos.FieldByName('Descr').AsString);
        SL.Insert(4, '');

        tCorpo.Insert;
        tCorpoEnviarEm.Value := EncodeDate(2004, 1, 1);
        tCorpoInclusao.Value := Now;
        tCorpoProcessou.Value := False;
        tCorpoDestino.Value := TodosNextar;
        tCorpoAssunto.Value := 'NexCafé - ' + tPrecos.FieldByName('Descr').AsString;
        tCorpoCorpo.Value := SL.Text;
        tCorpoAnexos.Value := 'boleto.jpg='+ArqBol;
        tCorpo.Post;
      except
      end;
      
      Result := VarArrayOf(['OK', DadosEmissaoBolToVariant(D), BoletoToVariant(B)]);
    except
      nxDB.Rollback;
    end;
  finally
    SL.Free;
    SL2.Free;
  end;
  
end;

function TqsRegistro300.Ativar(const Args: array of Variant): Variant;
var 
  A, B : TCabAutorizacao;
  S: String;
begin
  tCli.Active := False;
  tCli.Active := True;
  Reg.Conta := Args[0];
  LI.liDetalhes.Add('Código de Ativação = ' + Args[1]);
  LI.liLoja := 0;
  LI.liOper := opAtivarConta;
  if not tCli.Locate('EmailConta', Reg.Conta, []) then begin
    Result := VarArrayOf(['Conta inexistente']);
    Exit;
  end;
  LI.liLoja := tCli.FieldByName('Codigo').AsInteger;
  if tCli.FieldByName('Ativado').AsBoolean then
    Result := VarArrayOf(['Essa conta já está ativada']) 
  else
  if not SameText(tCli.FieldByName('CodAtivacao').AsString, Args[1]) then
    Result := VarArrayOf(['Código de Ativação informado está incorreto'])
  else begin
    S := '';
    tCli.Edit;
    tCli.FieldByName('Ativado').AsBoolean := True;
    tCli.FieldByName('AtivadoEm').AsDateTime := Now;
    tCli.Post;
    tAut.IndexName := 'ILoja';
    tAut.SetRange([LI.liLoja, True], [LI.liLoja, True]);
    try
      while not tAut.Eof do begin
        if S>'' then S := S + ';';
        S := S + tAut.FieldByName('Autorizacao').AsString;
        if not tAut.FieldByName('EnviouCli').AsBoolean then begin
          tAut.Edit;
          tAut.FieldByName('EnviouCli').AsBoolean := True;
          tAut.Post;
        end;
        tAut.Next;
      end;
    finally
      tAut.CancelRange;
    end;
    Result := VarArrayOf(['OK', Reg.Conta, S, 0, False]);
  end;  
end;

function TqsRegistro300.AtualizaDadosConta(
  const Args: array of Variant): Variant;
var SL, sl2 : TStrings;  
begin
  tCli.Active := False;
  tCli.Active := True;
  Reg.Conta := Args[0];
  LI.liLoja := Reg.CodLoja;
  LI.liDetalhes.Add('Conta = ' + Args[0]);
  LI.liDetalhes.Add('Senha = ' + Args[1]);
  LI.liDetalhes.Add('');
  LI.liDetalhes.Add(Args[2]);
  
  if (Reg.CodLoja=0) and not tCli.Locate('EmailConta', Reg.Conta, []) then
  begin
    Result := VarArrayOf(['Conta inexistente']);
    Exit;
  end;

  if (Reg.CodLoja>0) and not tCli.Locate('Codigo', Reg.CodLoja, []) then
  begin
    Result := VarArrayOf(['Conta inexistente']);
    Exit;
  end;

  LI.liLoja := tCli.FieldByName('Codigo').AsInteger;
  
  if (not SameText(tCli.FieldByName('Senha').AsString, Args[1])) then
  begin
    Result := VarArrayOf(['Senha incorreta']);
    Exit;
  end;
  
  SL := TStringList.Create;
  sl2 := TStringList.Create;
  try
    SL.Text := Args[2];
    tCli.Edit;
    tCli.FieldByName('Loja').AsString := Sl.Values['Nome'];
    tCli.FieldByname('Proprietarios').AsString := Sl.Values['Prop'];
    tCli.FieldByName('Cidade').AsString := sl.Values['Cidade'];
    tCli.FieldByName('UF').AsString := sl.Values['UF'];
    tCli.FieldByName('AtualizadoEm').AsDateTime := Now;
    tCli.FieldByName('AtualizadoPor').AsString := 'Cliente';

    tCli.FieldByName('Endereco').AsString := SL.Values['Endereco'];
    tCli.FieldByName('Cidade').AsString := SL.Values['Cidade'];
    tCli.FieldByName('UF').AsString := SL.Values['UF'];
    tCli.FieldByName('CEP').AsString := SL.Values['CEP'];
    tCli.FieldByName('Bairro').AsString := SL.Values['Bairro'];
      
    if Trim(SL.Values['Tel1'])>'' then
      sl2.Add(SL.Values['Tel1']);
    if Trim(SL.Values['Tel2'])>'' then
      sl2.Add(SL.Values['Tel2']);
    if Trim(SL.Values['Tel3'])>'' then
      sl2.Add(SL.Values['Tel3']);
    if Trim(SL.Values['Tel4'])>'' then
      sl2.Add(SL.Values['Tel4']);
    tCli.FieldByName('Telefones').AsString := sl2.Text;
    
    tCli.Post;
  finally
    SL.Free;
    sl2.Free;
  end;

  Result := VarArrayOf(['OK']);
end;

function TqsRegistro300.ObtemBoletos(const Args: array of Variant): Variant;
var 
  I : Integer;
  aPend: Boolean;
  SIndex : String;
  A : TArrayBoleto;
  D : TDadosEmissaoBol;
begin  
  tCli.Active := False;
  tCli.Active := True;
  tRec.Active := False;
  tRec.Active := True;
  Reg.Conta := Args[0];
  aPend := Args[2];
  LI.liDetalhes.Add('Conta = ' + Args[0]);
  LI.liDetalhes.Add('Senha = '  +Args[1]);
  if aPend then
    LI.liDetalhes.Add('Boletos = Pendentes') else
    LI.liDetalhes.Add('Boletos = Todos');
    
  LI.liLoja := 0;
  if (Reg.CodLoja=0) and not tCli.Locate('EmailConta', Reg.Conta, []) then
  begin
    Result := VarArrayOf(['Conta inexistente']);
    Exit;
  end;

  if (Reg.CodLoja>0) and not tCli.Locate('Codigo', Reg.CodLoja, []) then
  begin
    Result := VarArrayOf(['Conta inexistente']);
    Exit;
  end;

  LI.liLoja := tCli.FieldByName('Codigo').AsInteger;
  
  if (not SameText(tCli.FieldByName('Senha').AsString, Args[1])) then
  begin
    Result := VarArrayOf(['Senha incorreta']);
    Exit;
  end;

  SetLength(A, 0);   I := 0;

  tRec.IndexName := 'IPremiumLojaBaixou';
  if aPend then
    tRec.SetRange([True, LI.liLoja, False], [True, LI.liLoja, False]) else
    tRec.SetRange([True, LI.liLoja], [True, LI.liLoja]);
  try
    tRec.First;
    while not tRec.Eof do begin
      Inc(I);
      SetLength(A, I);
      A[I-1].dbVenc := tRecVencimento.Value;
      A[I-1].dbLanc := tRecLancamento.Value;
      A[I-1].dbNum := tRecID.Value;
      A[I-1].dbDescr := tRecDescricao.Value;
      A[I-1].dbValor := tRecValor.Value;
      A[I-1].dbPagoEm := tRecPagamento.Value;
      A[I-1].dbCanceladoEm := tRecCanceladoEm.Value;
      A[I-1].dbBaixou := tRecBaixou.Value;
      tRec.Next;
    end;
  finally
    tRec.CancelRange;
  end;

  if I>0 then begin
    D.deNome := tCliRazaoSocial.Value;
    D.deCNPJ := tCliCNPJ.Value;
    D.deEnd := tCliEndereco.Value;
    D.deCidade := tCliCidade.Value;
    D.deUF := tCliUF.Value;
    D.deCedente := FB.Cedente.Nome;
    Result := VarArrayOf(['OK', DadosEmissaoBolToVariant(D), ArrayBoletoToVariant(A)]);
  end else
  if aPend then
    Result := VarArrayOf(['Não há boletos pendentes']) else
    Result := VarArrayOf(['Não há boletos emitidos para sua conta']);
end;

function TqsRegistro300.ObtemBP(aLoja: Integer): Integer;
begin
  try
    tRec.SetRange([True, aLoja, False], [True, aLoja, False]);
    try
      Result := tRec.RecordCount;
    finally
      tRec.CancelRange;
    end;
  except
    Result := 0;
  end;
end;

function TqsRegistro300.ObtemDadosConta(
  const Args: array of Variant): Variant;
var 
  SL, sl2 : TStringList;
  I : Integer;
begin  
  tCli.Active := False;
  tCli.Active := True;
  Reg.Conta := Args[0];
  LI.liDetalhes.Add('Conta = ' + Args[0]);
  LI.liDetalhes.Add('Senha = '  +Args[1]);
  LI.liLoja := 0;
  if (Reg.CodLoja=0) and not tCli.Locate('EmailConta', Reg.Conta, []) then
  begin
    Result := VarArrayOf(['Conta inexistente']);
    Exit;
  end;

  if (Reg.CodLoja>0) and not tCli.Locate('Codigo', Reg.CodLoja, []) then
  begin
    Result := VarArrayOf(['Conta inexistente']);
    Exit;
  end;

  LI.liLoja := tCli.FieldByName('Codigo').AsInteger;
  
  if (not SameText(tCli.FieldByName('Senha').AsString, Args[1])) then
  begin
    Result := VarArrayOf(['Senha incorreta']);
    Exit;
  end;
  
  SL := TStringList.Create;
  try
    SL.Values['Endereco'] := tCli.FieldByName('Endereco').AsString;
    SL.Values['Cidade'] := tCli.FieldByName('Cidade').AsString;
    SL.Values['UF'] := tCli.FieldByName('UF').AsString;
    SL.Values['CEP'] := tCli.FieldByName('CEP').AsString;
    SL.Values['Bairro'] := tCli.FieldByName('Bairro').AsString;
    SL.Values['Nome'] := tCli.FieldByName('Loja').AsString;
    SL.Values['Prop'] := tCli.FieldByname('Proprietarios').AsString;
      
    sl2 := TStringList.Create;
    try
      sl2.Text := tCli.FieldByName('Telefones').AsString;
      for I := sl2.Count - 1 downto 0 do 
        if Trim(sl2[I])='' then sl2.Delete(I);
      for I := 0 to sl2.Count - 1 do
        if I<4 then
          SL.Values['Tel'+IntToStr(I+1)] := sl2[I];
    finally
      sl2.free;
    end;
    Result := VarArrayOf(['OK', SL.Text]);
  finally
    SL.Free;
  end;
end;
  
function TqsRegistro300.ObtemContaPorEquip(
  const Args: array of Variant): Variant;
begin
  tCli.Active := False;
  tCli.Active := True;
  tCli.IndexName := 'ICodEquip';
  try
    tCli.SetRange([Args[0]], [Args[0]]);
    try
      if tCli.IsEmpty then
        Result := '' else
        Result := EnviaEmailRegistros(tCli);
      if Result='' then
        Result := VarArrayOf(['']) else
        Result := VarArrayOf(['OK', Result]);
    finally
      tCli.CancelRange;
    end;
  finally
    tCli.IndexName := 'ICodigo';
  end;
end;

function TqsRegistro300.ObtemDadosCobranca(
  const Args: array of Variant): Variant;
var 
  SL, sl2 : TStringList;
  I : Integer;
begin  
  tCli.Active := False;
  tCli.Active := True;
  Reg.Conta := Args[0];
  LI.liDetalhes.Add('Conta = ' + Args[0]);
  LI.liDetalhes.Add('Senha = '  +Args[1]);
  LI.liLoja := 0;
  LI.liOper := opObtemDadosCobranca;
  if not tCli.Locate('EmailConta', Reg.Conta, []) then begin
    Result := VarArrayOf(['Conta inexistente']);
    Exit;
  end;
  LI.liLoja := tCli.FieldByName('Codigo').AsInteger;
  if not SameText(tCli.FieldByName('Senha').AsString, Args[1]) then
    Result := VarArrayOf(['Senha Incorreta'])
  else begin
    SL := TStringList.Create;
    try
      SL.Values['RazaoSocial'] := tCli.FieldByName('RazaoSocial').AsString;
      SL.Values['CNPJ'] := tCli.FieldByName('CNPJ').AsString;
      SL.Values['IE'] := tCli.FieldByName('IE').AsString;
      SL.Values['Endereco'] := tCli.FieldByName('Endereco').AsString;
      SL.Values['Cidade'] := tCli.FieldByName('Cidade').AsString;
      SL.Values['UF'] := tCli.FieldByName('UF').AsString;
      SL.Values['CEP'] := tCli.FieldByName('CEP').AsString;
      SL.Values['Bairro'] := tCli.FieldByName('Bairro').AsString;
      sl2 := TStringList.Create;
      try
        sl2.Text := tCli.FieldByName('Telefones').AsString;
        for I := sl2.Count - 1 downto 0 do 
          if Trim(sl2[I])='' then sl2.Delete(I);
        for I := 0 to sl2.Count - 1 do
          if I<4 then
            SL.Values['Tel'+IntToStr(I+1)] := sl2[I];
      finally
        sl2.free;
      end;
      Result := VarArrayOf(['OK', SL.Text]);
    finally
      SL.Free;
    end;
  end;  
end;

function TqsRegistro300.ObtemJFP(aLoja: Integer): Boolean;
begin
  tAut.IndexName := 'ILojaTipoVenc';
  try
    tAut.SetRange([aLoja, ectcFreePremium], [aLoja, ectcFreePremium]);
    try
      if tAut.IsEmpty then
        Result := False
      else begin
        tAut.Last;
        Result := not tAut.FieldByName('Vencimento').IsNull;
      end;
    finally
      tAut.CancelRange;  
    end;
  finally
    tAut.IndexName := 'ILoja';
  end;
end;

function TqsRegistro300.ObtemParamAss(const Args: array of Variant): Variant;
var 
  A: TArrayAssinatura;
  I: Integer;
  S, sOqueE : String;
  sTermos : String;
  SL : TStringList;
begin
  tPrecos.Active := True;
  SetLength(A, tPrecos.RecordCount);
  I := 0;
  tPrecos.First;
  while not tPrecos.Eof do begin
    if tPrecos.FieldByName('DispCli').AsBoolean then begin
      A[I].prDescr := tPrecos.FieldByName('Descr').AsString;
      A[I].prValor := tPrecos.FieldByName('Valor').AsCurrency;
      A[I].prMeses := tprecos.FieldByName('Meses').AsInteger;
    end;
    tPrecos.Next;
    Inc(I);
  end;

  sTermos := '';
  sOqueE := '';

  SL := TStringList.Create;
  try
    S := ExtractFilePath(ParamStr(0))+'oqueepremium.txt';
    if FileExists(S) then begin
      SL.LoadFromFile(S);
      sOqueE := SL.Text;
    end;

    S := ExtractFilePath(ParamStr(0))+'termos.txt';
    if FileExists(S) then begin
      SL.LoadFromFile(S);
      sTermos := SL.Text;
    end;
  finally
    SL.Free;
  end;

  Result := VarArrayOf([sOqueE, sTermos, ArrayAssinaturaToVariant(A)]);
end;

function TqsRegistro300.ObtemContaPorEmail(
  const Args: array of Variant): Variant;
begin
  Result := VarArrayOf(['']);
  if (Args[0]=null) or (Trim(Args[0])='') then Exit;

  qCli.Active := False;
  qCli.SQL.Text := 'select * from cliente where emailreg like ' + QuotedStr('%'+Args[0]+'%');
  qCli.Open;
  try
    if qCli.IsEmpty then
      Result := '' else
      Result := EnviaEmailRegistros(qCli, Args[0]);
    if Result='' then
      Result := VarArrayOf(['']) else
      Result := VarArrayOf(['OK', Result]); 
  finally
    qCli.Active := False;
  end;
end;

procedure TqsRegistro300.kbmMWQueryServiceCreate(Sender: TObject);
begin
  FBI.ListaBoletos.Add(FB);
  nxDB.AliasPath := '';
  nxDB.AliasName := 'Registro';
  Reg := TRegistro.Create;
  LI := TLogInfo.Create;
  tCli.Open;
  tLog.Open;
  tAut.Open;
  tEst.Open;
  tEstSearch.Open;
  tEstRes.Open;
  tPrecos.Open;
  tRec.Open;
end;

procedure TqsRegistro300.kbmMWQueryServiceDestroy(Sender: TObject);
begin
  LI.Free;
  Reg.Free;
end;

end.






                                            
