; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Cyber Manager CM-Server
AppVerName=Cyber Manager 1.8.0.5
AppPublisher=cybermgr.com
AppPublisherURL=http://www.cybermgr.com
AppSupportURL=http://www.cybermgr.com
AppUpdatesURL=http://www.cybermgr.com
DefaultDirName=C:\cybermgr
DefaultGroupName=Cyber-Manager
OutputDir=c:\
OutputBaseFilename=setup_cmserver

[Tasks]
; NOTE: The following entry contains English phrases ("Create a desktop icon" and "Additional icons"). You are free to translate them into another language if required.
Name: "desktopicon"; Description: "Criar um ícone no &desktop"; GroupDescription: "Ícones adicionais:"
; NOTE: The following entry contains English phrases ("Create a Quick Launch icon" and "Additional icons"). You are free to translate them into another language if required.
; Name: "quicklaunchicon"; Description: "Create a &Quick Launch icon"; GroupDescription: "Ícones adicionais:"; Flags: unchecked
Name: "autostarticon"; Description: "Executar o CM-Server automaticamente ao iniciar Windows"; GroupDescription: "Ícones adicionais:"

[Files]
Source: "C:\Meus Programas\CyberMgr\CMServer.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Meus Programas\CyberMgr\ImportaArqV1.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Meus Programas\CyberMgr\CorrigeCybermgr.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Meus Programas\CyberMgr\CMGuard.exe"; DestDir: "{app}\Atualiza"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[INI]
Filename: "{app}\CMServer.url"; Section: "InternetShortcut"; Key: "URL"; String: "http://www.cybermgr.com"

[Icons]
Name: "{group}\Cyber Manager CM-Server"; Filename: "{app}\CMServer.exe";  WorkingDir: "{app}"
; NOTE: The following entry contains an English phrase ("on the Web"). You are free to translate it into another language if required.
Name: "{group}\Página do Cyber Manager na Internet"; Filename: "{app}\CMServer.url"
; NOTE: The following entry contains an English phrase ("Uninstall"). You are free to translate it into another language if required.
Name: "{group}\Desinstalar Cyber Manager CM-Server"; Filename: "{uninstallexe}"
Name: "{userdesktop}\Cyber Manager CM-Server"; Filename: "{app}\CMServer.exe"; Tasks: desktopicon; WorkingDir: "{app}"
;Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\Cyber Manager CM-Server"; Filename: "{app}\CMServer.exe"; Tasks: quicklaunchicon
Name: "{commonstartup}\Cyber Manager CM-Server"; Filename: "{app}\CMServer.exe"; Tasks: autostarticon; WorkingDir: "{app}"

[Run]
; NOTE: The following entry contains an English phrase ("Launch"). You are free to translate it into another language if required.
Filename: "{app}\CMServer.exe"; Description: "Executar o Cyber Manager CM-Server"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: files; Name: "{app}\CMServer.url"

