unit NewService_Impl;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ This is where you are supposed to code the implementation of your objects. }
{----------------------------------------------------------------------------}

interface

uses
  {vcl:} Classes, SysUtils, 
  {RemObjects:} uROClientIntf, uROTypes, uROServer, uROServerIntf, uROSessions,
  {Data Abstract:} uDAClasses, uDADataTable, uDABINAdapter, uDAInterfaces,
  {Ancestor Implementation:} DARemoteService_Impl,
  {Used RODLs:} DataAbstract_Intf,
  {Generated:} NewLibrary_Intf;

type
  { TNewService }
  TNewService = class(TDARemoteService, INewService)
    BinAdapter: TDABINAdapter;
    Schema: TDASchema;
    DataDictionary: TDADataDictionary;
  private
  protected
    { INewService methods }
  end;

implementation

{$R *.dfm}
uses
  {Generated:} NewLibrary_Invk, fServerDataModule;

procedure Create_NewService(out anInstance : IUnknown);
begin
  anInstance := TNewService.Create(NIL);
end;

initialization
  TROClassFactory.Create('NewService', Create_NewService, TNewService_Invoker);

finalization

end.
