unit uCRQS100;

// =========================================================================
// kbmMW - An advanced and extendable middleware framework.
// by Components4Developers (http://www.components4developers.com)
//
// Service generated by kbmMW service wizard.
//
// INSTRUCTIONS FOR REGISTRATION/USAGE
// -----------------------------------
// Please update the uses clause of the datamodule/form the TkbmMWServer is placed on by adding 
// kbmMWQueryService to it. Eg.
// 
//     uses ...,kbmMWServer,kbmMWQueryService;
// 
// Somewhere in your application, make sure to register the serviceclass to the TkbmMWServer instance. Eg.
// 
// var
//    sd:TkbmMWCustomServiceDefinition;
// ..
//    sd:=kbmMWServer1.RegisterService(yourserviceclassname,false);
// 
// Set the last parameter to true if this is the default service.
// 



{$I kbmMW.inc}

interface

uses
  SysUtils, {$ifdef LEVEL6}Variants,{$endif} Classes, Forms, kbmMWSecurity, kbmMWServer, kbmMWGlobal, kbmMWQueryService, kbmMWNexusDB, kbmMWBinaryStreamFormat,
  kbmMemTable, kbmMWStreamFormat, DB, kbmMWCustomConnectionPool, Windows,
  kbmMWCustomDataset, kbmMWResolvers, nxdb, nxllTransport,
  nxptBasePooledTransport, nxtwWinsockTransport, nxsdServerEngine,
  nxreRemoteServerEngine, nxllComponent, uLicenca, kbmMemBinaryStreamFormat, uRSLogInfo,
  mySQLDbTables;

type
  TQS100 = class(TkbmMWQueryService)
    BSF: TkbmMWBinaryStreamFormat;
    nxDB: TnxDatabase;
    nxRSE: TnxRemoteServerEngine;
    nxTCPIP: TnxWinsockTransport;
    nxSession: TnxSession;
    MTBSF: TkbmBinaryStreamFormat;
    mySQLDB: TmySQLDatabase;
    qMySql: TmySQLQuery;
    tSessao: TnxTable;
  private
     { Private declarations }
     FMA: String;
     FIP: String;
  protected
    function UserLogin(const Args:array of Variant):Variant; 
    function UserLogout(const Args:array of Variant):Variant;
    function KeepAlive(const Args:array of Variant):Variant;
    function ProcessRequest(const Func:string; const ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant; override;
  public
     { Public declarations }
{$IFNDEF CPP}class{$ENDIF} function GetPrefServiceName:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetVersion:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetAuthor:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetAssistance:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetDescriptionAbstract:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetFlags:TkbmMWServiceFlags; override;
  end;

implementation

uses uCRDM;

{$R *.dfm}


// Service definitions.
//---------------------

{$IFNDEF CPP}class{$ENDIF} function TQS100.GetPrefServiceName:string;
begin
     Result:='CYBERROOM';
end;

{$IFNDEF CPP}class{$ENDIF} function TQS100.GetVersion:string;
begin
     Result:='100';
end;

{$IFNDEF CPP}class{$ENDIF} function TQS100.GetAuthor:string;
begin
     Result:='suporte@cybermgr.com';
end;

{$IFNDEF CPP}class{$ENDIF} function TQS100.GetAssistance:string;
begin
     Result:='suporte@cybermgr.com';
end;

{$IFNDEF CPP}class{$ENDIF} function TQS100.GetDescriptionAbstract:string;
begin
     Result:='VALIDACAO DE USUARIO';
end;

{$IFNDEF CPP}class{$ENDIF} function TQS100.GetFlags:TkbmMWServiceFlags;
begin
     Result:=[mwsfListed];
end;

function TQS100.ProcessRequest(const Func: string;
  const ClientIdent: TkbmMWClientIdentity;
  const Args: array of Variant): Variant;
var 
  uFunc : String;  
begin
  with ClientIdent do begin
    FMA := Copy(ClientLocation, 1, Pos('|', ClientLocation)-1);
    FIP := Copy(ClientLocation, Pos('|', ClientLocation)+1, 50);
  end;  
  
  uFunc := UpperCase(Func);
  if uFunc='KEEPALIVE' then
    Result := KeepAlive(Args)
  else
  if uFunc='USERLOGIN' then
    Result := UserLogin(Args)
  else
  if uFunc='USERLOGOUT' then
    Result := UserLogout(Args)
  else
    Result := inherited ProcessRequest(Func, ClientIdent, Args);
end;

procedure TransfDados(O, D: TDataset; Tudo: Boolean);
var 
  I : Integer;
  F : TField;
begin
  for I := 0 to D.FieldCount-1 do with D.Fields[I] do 
  begin
    F := O.FindField(FieldName);
    if F<>nil then
      Value := F.Value;
  end;  
end;

function TQS100.KeepAlive(const Args: array of Variant): Variant;
begin
  DM.Refresh(GetCurrentThreadID);
end;

function TQS100.UserLogin(const Args: array of Variant): Variant;
var S: String;
begin
  try
    S := Args[0];
    Result := DM.NovaSessao(GetCurrentThreadID, S, qMySql, tSessao, FMA, FIP);
  except
    on E:Exception do 
      Result := E.Message;
  end;      
end;

function TQS100.UserLogout(const Args: array of Variant): Variant;
begin
  try
    DM.FechaSessao(GetCurrentThreadID, qMySql, tSessao, tcUserRequest);
    Result := Null;
  except
    on E:Exception do 
      Result := E.Message;
  end;      
end;

end.






                                            
