unit cmmwsGuard;

// =========================================================================
// kbmMW - An advanced and extendable middleware framework.
// by Components4Developers (http://www.components4developers.com)
//
// Service generated by kbmMW service wizard.
//
// INSTRUCTIONS FOR REGISTRATION/USAGE
// -----------------------------------
// Please update the uses clause of the datamodule/form the TkbmMWServer is placed on by adding 
// kbmMWCustomQueryService to it. Eg.
// 
//     uses ...,kbmMWServer,kbmMWCustomQueryService;
// 
// Somewhere in your application, make sure to register the serviceclass to the TkbmMWServer instance. Eg.
// 
// var
//    sd:TkbmMWCustomServiceDefinition;
// ..
//    sd:=kbmMWServer1.RegisterService(yourserviceclassname,false);
// 
// Set the last parameter to true if this is the default service.
// 



{$I kbmMW.inc}

interface

uses
  SysUtils, {$ifdef LEVEL6}Variants{$else}Forms{$endif}, Classes, kbmMWSecurity, kbmMWServer, kbmMWGlobal, kbmMWCustomQueryService;

type
  TmwsGuard = class(TkbmMWCustomQueryService)
  private
     { Private declarations }
  protected
     { Private declarations }
     function ProcessRequest(const Func:string; const ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant; override;
     function PerformOBTEMVERSAOMIN(ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant; virtual;
  public
     { Public declarations }
{$IFNDEF CPP}class{$ENDIF} function GetPrefServiceName:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetFlags:TkbmMWServiceFlags; override;
  end;

implementation

uses cmDMServ, cmsConst;

{$R *.dfm}


// Service definitions.
//---------------------

{$IFNDEF CPP}class{$ENDIF} function TmwsGuard.GetPrefServiceName:string;
begin
     Result:='GUARD';
end;

{$IFNDEF CPP}class{$ENDIF} function TmwsGuard.GetFlags:TkbmMWServiceFlags;
begin
     Result:=[mwsfListed];
end;


// Master request processor.
//--------------------------

function TmwsGuard.ProcessRequest(const Func:string; const ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant;
var
   AFunc:string;
begin
     AFunc:=UpperCase(Func);
     if AFunc='OBTEMVERSAOMIN' then
       Result:=PerformOBTEMVERSAOMIN(ClientIdent,Args)
     else 
       Result:=inherited ProcessRequest(Func,ClientIdent,Args);
end;


// Functions published by the service.
//------------------------------------

function TmwsGuard.PerformOBTEMVERSAOMIN(ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant;
begin
     // Enter code here to perform function OBTEMVERSAOMINGUARD
     Result:= VersaoMinGuard;
end;


end.