; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=NexCafé NexServ
AppVerName=NexServ 3.0.0.91
AppPublisherURL=http://www.nexcafe.com.br
AppSupportURL=http://www.nexcafe.com.br
AppUpdatesURL=http://www.nexcafe.com.br
DefaultDirName=C:\nexcafe
DefaultGroupName=NexCafé
OutputDir=c:\meus programas\nexcafe
OutputBaseFilename=setup_nexserv2

[Tasks]
; NOTE: The following entry contains English phrases ("Create a desktop icon" and "Additional icons"). You are free to translate them into another language if required.
Name: desktopicon; Description: Criar um ícone no &desktop; GroupDescription: Ícones adicionais:
; NOTE: The following entry contains English phrases ("Create a Quick Launch icon" and "Additional icons"). You are free to translate them into another language if required.
; Name: "quicklaunchicon"; Description: "Create a &Quick Launch icon"; GroupDescription: "Ícones adicionais:"; Flags: unchecked
Name: autostarticon; Description: Executar o NexServ automaticamente ao iniciar Windows; GroupDescription: Ícones adicionais:

[Files]
Source: C:\Meus Programas\nexcafe\NexServ.exe; DestDir: {app}; Flags: ignoreversion
Source: C:\meus programas\nexcafe\nexguard.exe; DestDir: {app}\Atualiza; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files


[INI]
Filename: {app}\NexServ.url; Section: InternetShortcut; Key: URL; String: http://www.nexcafe.com.br

[Icons]
Name: {group}\NexCafé NexServ; Filename: {app}\NexServ.exe; WorkingDir: {app}
Name: {group}\Suporte Técnico NexCafé; Filename: {app}\suporte\CallingCard.exe; WorkingDir: {app}\suporte; IconIndex: 0
Name: {userdesktop}\Suporte Técnico NexCafé; Filename: {app}\suporte\CallingCard.exe; WorkingDir: {app}\suporte; IconIndex: 0
Name: {group}\Desinstalar NexCafé NexServ; Filename: {uninstallexe}
Name: {userdesktop}\NexCafé NexServ; Filename: {app}\NexServ.exe; Tasks: desktopicon; WorkingDir: {app}
;Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\NexCafé NexServ"; Filename: "{app}\NexServ.exe"; Tasks: quicklaunchicon
Name: {commonstartup}\NexCafé NexServ; Filename: {app}\NexServ.exe; Tasks: autostarticon; WorkingDir: {app}
Name: {group}\{cm:UninstallProgram, NexCafé NexServ}; Filename: {uninstallexe}

[Run]
; NOTE: The following entry contains an English phrase ("Launch"). You are free to translate it into another language if required.
Filename: {app}\NexServ.exe; Description: Executar o NexCafé NexServ; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: files; Name: {app}\NexServ.url

[Languages]
Name: Portugues; MessagesFile: compiler:Languages\BrazilianPortuguese.isl

