unit nxcSkbmArqs;

// =========================================================================
// kbmMW - An advanced and extendable middleware framework.
// by Components4Developers (http://www.components4developers.com)
//
// Service generated by kbmMW service wizard.
//
// INSTRUCTIONS FOR REGISTRATION/USAGE
// -----------------------------------
// Please update the uses clause of the datamodule/form the TkbmMWServer is placed on by adding kbmMWFileService 
// to it. Eg.
// 
//     uses ...,kbmMWServer,kbmMWFileService;
// 
// Somewhere in your application, make sure to register the serviceclass to the TkbmMWServer instance. Eg.
// 
// var
//    sd:TkbmMWCustomServiceDefinition;
// ..
//    sd:=kbmMWServer1.RegisterService(yourserviceclassname,false);
// 
// Set the last parameter to true if this is the default service.
// 
// 
// SPECIFIC FILE SERVICE REGISTRATION INSTRUCTIONS
// -----------------------------------------------
// Cast the returned service definition object (sd) to a TkbmMWFileServiceDefinition. eg:
// 
// var
//    fsd:TkbmMWFileServiceDefinition;
// ..
//    fsd:=TkbmMWFileServiceDefinition(sd)
//    fsd.RootPath:='.';
//    fsd.BlockSize:=8192;
//    fsd.ListAttributesOptional:=false;
//    fsd.ListAttributes:=faReadOnly+faDirectory+faArchive;
//    fsd.StorageAttributes:=faArchive;
// -----------------------------------------------



{$I kbmMW.inc}

interface

uses
  SysUtils, {$ifdef LEVEL6}Variants{$else}Forms{$endif}, Classes, kbmMWSecurity, kbmMWServer, kbmMWGlobal, kbmMWFileService;

type
  TmwServArq = class(TkbmMWFileService)
    procedure kbmMWFileServiceFileAccess(Sender: TObject; Path: string;
      var AccessPermissions: TkbmMWFileAccessPermissions);
    procedure kbmMWFileServiceAuthenticate(Sender: TObject;
      ClientIdent: TkbmMWClientIdentity; var Perm: TkbmMWAccessPermissions);
  private
     { Private declarations }
  protected
     { Private declarations }
  public
     { Public declarations }
{$IFNDEF CPP}class{$ENDIF} function GetPrefServiceName:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetFlags:TkbmMWServiceFlags; override;
  end;

implementation

uses nxcServidor;

{$R *.dfm}


// Service definitions.
//---------------------

{$IFNDEF CPP}class{$ENDIF} function TmwServArq.GetPrefServiceName:string;
begin
     Result:='servidor_arquivos';
end;

procedure TmwServArq.kbmMWFileServiceAuthenticate(Sender: TObject;
  ClientIdent: TkbmMWClientIdentity; var Perm: TkbmMWAccessPermissions);
begin
  Perm := [mwapRead,mwapWrite,mwapDelete,mwapExecute];
end;

procedure TmwServArq.kbmMWFileServiceFileAccess(Sender: TObject; Path: string;
  var AccessPermissions: TkbmMWFileAccessPermissions);
begin
  AccessPermissions := [mwfapList,mwfapGet,mwfapPut,mwfapDelete,mwfapOverwrite,mwfapSubDirs,mwfapStatus,mwfapRename,
                        mwfapSetStatusCreationTime,mwfapSetStatusModificationTime,mwfapSetStatusAccessTime,mwfapSetStatusAttributes];
end;

{$IFNDEF CPP}class{$ENDIF} function TmwServArq.GetFlags:TkbmMWServiceFlags;
begin
     Result:=[mwsfListed];
end;


end.