unit nxcSkbmProcs;

// =========================================================================
// kbmMW - An advanced and extendable middleware framework.
// by Components4Developers (http://www.components4developers.com)
//
// Service generated by kbmMW service wizard.
//
// INSTRUCTIONS FOR REGISTRATION/USAGE
// -----------------------------------
// Please update the uses clause of the datamodule/form the TkbmMWServer is placed on by adding 
// YourServiceUnitName to it. Eg.
// 
//     uses ...,kbmMWServer,YourServiceUnitName;
// 
// Somewhere in your application, make sure to register the serviceclass to the TkbmMWServer instance. Eg.
// 
// var
//    sd:TkbmMWCustomServiceDefinition;
// ..
//    sd:=kbmMWServer1.RegisterService(yourserviceclassname,false);
// 
// Set the last parameter to true if this is the default service.
// 



{$I kbmMW.inc}

interface

uses
  SysUtils, {$ifdef LEVEL6}Variants{$else}Forms{$endif}, Classes, kbmMWSecurity, kbmMWServer, kbmMWGlobal,
  DB, nxdb, nxllComponent;

type
  TkbmProcs = class(TkbmMWCustomService)
    nxSession: TnxSession;
    nxDB: TnxDatabase;
    tCli: TnxTable;
    tCliCodigo: TAutoIncField;
    tCliNome: TStringField;
    tCliSenha: TStringField;
    tConfig: TnxTable;
    tConfigNumSeq: TAutoIncField;
    tConfigModulos: TMemoField;
    tConfigTiposLancExtra: TMemoField;
    tConfigProgramasPermitidos: TMemoField;
    tConfigCMGuard: TMemoField;
    tConfigJanelasExplorer: TMemoField;
    tConfigFecharProgramas: TBooleanField;
    tConfigAutoExecutar: TStringField;
    tConfigLimiteTempoPadrao: TDateTimeField;
    tConfigPacoteTempoReal: TBooleanField;
    tConfigPermiteLoginSemCred: TBooleanField;
    tConfigEncerramentoPrePago: TWordField;
    tConfigProdutoImpressao: TStringField;
    tConfigPermiteCapturaTela: TBooleanField;
    tConfigAlertaFimTempo: TDateTimeField;
    tConfigVariosTiposAcesso: TBooleanField;
    tConfigModoPagtoAcesso: TWordField;
    tConfigMostraPrePagoDec: TBooleanField;
    tConfigTempoMaxAlerta: TDateTimeField;
    tConfigMostraCliCadAntesAvulso: TBooleanField;
    tConfigAbre1: TDateTimeField;
    tConfigAbre2: TDateTimeField;
    tConfigAbre3: TDateTimeField;
    tConfigAbre4: TDateTimeField;
    tConfigAbre5: TDateTimeField;
    tConfigAbre6: TDateTimeField;
    tConfigAbre7: TDateTimeField;
    tConfigFecha1: TDateTimeField;
    tConfigFecha2: TDateTimeField;
    tConfigFecha3: TDateTimeField;
    tConfigFecha4: TDateTimeField;
    tConfigFecha5: TDateTimeField;
    tConfigFecha6: TDateTimeField;
    tConfigFecha7: TDateTimeField;
    tConfigCorLivre: TIntegerField;
    tConfigCorFLivre: TIntegerField;
    tConfigCorUsoPrePago: TIntegerField;
    tConfigCorFUsoPrePago: TIntegerField;
    tConfigCorUsoPosPago: TIntegerField;
    tConfigCorFUsoPosPago: TIntegerField;
    tConfigCorAguardaPagto: TIntegerField;
    tConfigCorFAguardaPagto: TIntegerField;
    tConfigCorManutencao: TIntegerField;
    tConfigCorFManutencao: TIntegerField;
    tConfigCorPausado: TIntegerField;
    tConfigCorFPausado: TIntegerField;
    tConfigCorDesktop: TIntegerField;
    tConfigCorFDesktop: TIntegerField;
    tConfigCampoLocalizaCli: TWordField;
    tConfigManterSaldoCaixa: TBooleanField;
    tConfigNaoMostrarMsgDebito: TBooleanField;
    tConfigTolerancia: TDateTimeField;
    tConfigRegImp98: TBooleanField;
    tConfigLimitePadraoDebito: TCurrencyField;
    tConfigPortaImpRec: TStringField;
    tConfigSaltoImpRec: TWordField;
    tConfigLargImpRec: TWordField;
    tConfigCabecalhoImpRec: TMemoField;
    tConfigRodapeImpRec: TMemoField;
    tConfigImprimirImpRec: TBooleanField;
    tConfigMostraProgAtual: TBooleanField;
    tConfigMostraObs: TBooleanField;
    tConfigEscondeTextoBotoes: TBooleanField;
    tConfigEscondeTipoAcesso: TBooleanField;
    tConfigExigirRG: TBooleanField;
    tConfigDesativaRegAutImp: TBooleanField;
    tConfigTipoFDesktop: TStringField;
    tConfigTipoFLogin: TStringField;
    tConfigNumFDesktop: TIntegerField;
    tConfigNumFLogin: TIntegerField;
    procedure kbmMWCustomServiceCreate(Sender: TObject);
  private
     { Private declarations }
    function NomeArqDesktop(aChecarExist: Boolean): String;
    function NomeArqLogin(aChecarExist: Boolean): String;

    procedure MudouFundo;
  protected
    function ProcessRequest(const Func:string; const ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant; override;
    procedure TrocaSenha(aContato: Integer; aNovaSenha: String);
    function ObtemSenha(aContato: Integer): String;
    procedure NovoFundo(aDesktop: Boolean; aNomeArq: String);
    procedure LimpaFundo(aDesktop: Boolean);
    function NomeArqFundo: Variant;
    
     { Private declarations }
  public
     { Public declarations }
{$IFNDEF CPP}class{$ENDIF} function GetPrefServiceName:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetFlags:TkbmMWServiceFlags; override;
  end;

implementation

uses cmServBase, cmServBD, nxcServidor;

{$R *.dfm}


// Service definitions.
//---------------------

{$IFNDEF CPP}class{$ENDIF} function TkbmProcs.GetPrefServiceName:string;
begin
     Result:='procsbase';
end;

procedure TkbmProcs.kbmMWCustomServiceCreate(Sender: TObject);
begin
  nxSession.ServerEngine := dmServidorBD.ServerEngine;
end;

procedure TkbmProcs.LimpaFundo(aDesktop: Boolean);
var S: String;
begin
  if aDesktop then 
    S := NomeArqDesktop(False) else
    S := NomeArqLogin(False);

  if S='' then Exit;
   
  InitTran(nxDB, [tConfig], True);
  try  
    tConfig.Edit;
    if aDesktop then
      tConfigTipoFDesktop.Value := '' else
      tConfigTipoFLogin.Value := '';
    tConfig.Post;
    if FileExists(S) then 
      TThreadRename.Create(S, '');
    nxDB.Commit;  
    MudouFundo;
  except
    nxDB.Rollback;
    Raise;
  end;
end;

procedure TkbmProcs.MudouFundo;
begin
  dmKbmServ.mwTCPIP.SendMessage('MSG.TODOS.MUDOUFUNDO', '', dmKbmServ.FCI, nil,
                                [ExtractFileName(NomeArqDesktop(True)),
                                 ExtractFileName(NomeArqLogin(True))]);
end;

function TkbmProcs.NomeArqDesktop(aChecarExist: Boolean): String;
var NewTran: Boolean;
begin
  if SameText(tConfigTipoFDesktop.Value, 'JPG') then begin
    Result := ExtractFilePath(ParamStr(0)) + 'DADOS\DESKTOP' + tConfigNumFDesktop.AsString + '.JPG';
{    if aChecarExist and (not FileExists(Result)) then begin
      Result := '';
      NewTran := not nxDB.InTransaction;
      if NewTran then
        InitTran(nxDB, [tConfig], True);
      try
        tConfig.Edit;
        tConfigTipoFDesktop.Value := '';
        tConfig.Post;
        if NewTran then
          nxDB.Commit;
      except
        if NewTran then
          nxDB.Rollback;
        Raise;  
      end;  
    end; }
  end else
    Result := '';
end;

function TkbmProcs.NomeArqFundo: Variant;
begin
  Result := VarArrayOf([ExtractFileName(NomeArqDesktop(True)), ExtractFileName(NomeArqLogin(True))]);
end;

function TkbmProcs.NomeArqLogin(aChecarExist: Boolean): String;
var NewTran : Boolean;
begin
  if tConfigTipoFLogin.Value>'' then begin
    Result := ExtractFilePath(ParamStr(0)) + 'DADOS\LOGIN'+tConfigNumFLogin.AsString+'.'+tConfigTipoFLogin.Value;
{    if aChecarExist and (not FileExists(Result)) then begin
      Result := '';
      NewTran := not nxDB.InTransaction;
      if NewTran then
        InitTran(nxDB, [tConfig], True);
      try
        tConfig.Edit;
        tConfigTipoFLogin.Value := '';
        tConfig.Post;
        if NewTran then
          nxDB.Commit;
      except
        if NewTran then
          nxDB.Rollback;
        Raise;  
      end;  
    end;   }
  end else
    Result := '';
end;

procedure TkbmProcs.NovoFundo(aDesktop: Boolean; aNomeArq: String);
var S, SAnt: String;
begin
  aNomeArq := UpperCase(ExtractFilePath(ParamStr(0))+'DADOS\'+aNomeArq);
  if not FileExists(aNomeArq) then
    Raise Exception.Create('Arquivo ' + aNomeArq + ' não encontrado');
  if aDesktop then begin
    S := ExtractFileExt(aNomeArq);
    if not SameText(S, '.JPG') then
      Raise Exception.Create('O arquivo de fundo para área de trabalho tem que ser do tipo JPG');
    InitTran(nxDB, [tConfig], True);
    try  
      tConfig.Refresh;
      SAnt := NomeArqDesktop(False);
      tConfig.Edit;
      tConfigNumFDesktop.Value := tConfigNumFDesktop.Value + 1;
      tConfigTipoFDesktop.Value := 'JPG';
      tConfig.Post;
      S := NomeArqDesktop(False);
      TThreadRename.Create(S, aNomeArq);
      if SAnt<>'' then
        TThreadRename.Create(SAnt, '');
      nxDB.Commit;
      MudouFundo;
    except
      nxDB.Rollback;
      Raise;
    end;
  end else begin
    S := ExtractFileExt(aNomeArq);
    if (not SameText(S, '.JPG')) and (not SameText(S, '.GIF')) then
      Raise Exception.Create('O arquivo de fundo para a tela de login tem que ser do tipo JPG ou GIF');
    InitTran(nxDB, [tConfig], True);
    try  
      tConfig.Refresh;
      SAnt := NomeArqLogin(False);
      tConfig.Edit;
      tConfigNumFLogin.Value := tConfigNumFLogin.Value + 1;
      tConfigTipoFLogin.Value := Copy(S, 2, 3);
      tConfig.Post;
      S := NomeArqLogin(False);  
      TThreadRename.Create(S, aNomeArq);
      if SAnt<>'' then
        TThreadRename.Create(SAnt, '');
      nxDB.Commit;
      MudouFundo;
    except
      nxDB.Rollback;
      Raise;
    end;
  end;
end;

function TkbmProcs.ObtemSenha(aContato: Integer): String;
begin
  tCli.Refresh;
  if tCli.FindKey([aContato]) then
    Result := tCliSenha.Value
  else
    Raise Exception.Create('Cliente com código '+IntToStr(aContato)+' não  foi encontrado no banco de dados!');
end;

function TkbmProcs.ProcessRequest(const Func: string;
  const ClientIdent: TkbmMWClientIdentity;
  const Args: array of Variant): Variant;
var S: String;  
begin
  nxSession.Active := True;
  nxDB.Active := True;
  tConfig.Active := True;
  tCli.Active := True;
  
  S := UpperCase(Func);
  try
    if S='TROCASENHA' then
      TrocaSenha(Args[0], Args[1])
    else
    if S='NOVOFUNDO' then
      NovoFundo(Args[0], Args[1])
    else  
    if S='LIMPAFUNDO' then
      LimpaFundo(Args[0])
    else  
    if S='NOMEARQFUNDO' then
      Result := NomeArqFundo
    else  
    if S='OBTEMSENHA' then
      Result := ObtemSenha(Args[0])
    else  
      raise Exception.Create('Função ' + Func + ' inexistente no servidor'); 
  except
    On E: Exception do
      kbmMWRaiseException(E.Message);
  end;
end;

procedure TkbmProcs.TrocaSenha(aContato: Integer; aNovaSenha: String);
begin
  nxSession.Active := True;
  nxDB.Active := True;
  tCli.Active := True;
  if not tCli.FindKey([aContato]) then
    kbmmwRaiseException('Erro ao trocar senha. O cliente código ' + IntToStr(aContato) + ' não foi encontrado no banco de dados!');
  InitTran(nxDB, [tCli], True);
  try    
    tCli.Edit;
    tCliSenha.Value := aNovaSenha;
    tCli.Post;
    nxDB.Commit;
  except
    nxDB.Rollback;
    Raise;
  end;
end;

{$IFNDEF CPP}class{$ENDIF} function TkbmProcs.GetFlags:TkbmMWServiceFlags;
begin
     Result:=[mwsfListed];
end;


end.