unit uDTSUp;

// =========================================================================
// kbmMW - An advanced and extendable middleware framework.
// by Components4Developers (http://www.components4developers.com)
//
// Service generated by kbmMW service wizard.
//


{$I kbmMW.inc}

interface

uses
  SysUtils, {$ifdef LEVEL6}Variants,{$endif} Classes, Forms, kbmMWSecurity, kbmMWServer, kbmMWGlobal,
  nxdb, nxdbbase, Db, kbmMemTable, kbmMWStreamFormat, kbmMWBinaryStreamFormat, Windows, nxsdTypes,
  kbmMWCustomConnectionPool, kbmMWNexusDB, nxllComponent, uDTSrvBDServ;

type
  TkbmUp = class(TkbmMWCustomService)
    dbUpload: TnxDatabase;
    nxSession: TnxSession;
    BSF: TkbmMWBinaryStreamFormat;
    MT: TkbmMemTable;
    tTec: TnxTable;
    tTecID: TStringField;
    tTecNome: TStringField;
    tTecSenha: TStringField;
    Tab: TnxTable;
    dbDown: TnxDatabase;
    mtLog: TkbmMemTable;
    mtLogID: TAutoIncField;
    mtLogTecnico: TStringField;
    mtLogData: TDateTimeField;
    mtLogDetalhes: TMemoField;
    mtLogOper: TWordField;
    mtLogOK: TBooleanField;
    mtLogDuracao: TDateTimeField;
    mtLogUUpload: TIntegerField;
    tOS: TnxTable;
    dbPar: TnxDatabase;
    tParametro: TnxTable;
    tParametroMaxDiasUpload: TWordField;
    tParametroMaxDiasDown: TWordField;
    tParametroDataDown: TDateTimeField;
    tParametroNomeFranquia: TStringField;
    tParametroBitMap: TGraphicField;
    tParametroObedeceListaProj: TBooleanField;
    tParametroListaProjDefault: TStringField;
    tParametroRestringeDiurno: TBooleanField;
    tParametroTravarTranslado: TBooleanField;
    tParametroCampoLocalOS: TBooleanField;
    tParametroInicioDiurno: TDateTimeField;
    tParametroFimDiurno: TDateTimeField;
    tParametroUploadApontamentoSemOS: TBooleanField;
    tParametroPermitirRateio: TBooleanField;
    tParametroConflitoHoraTodosCli: TBooleanField;
    tParametroExigeAutorizadoPor: TBooleanField;
    tParametroMostraReemb: TBooleanField;
    tParametroForcaTransladoProj: TBooleanField;
    tParametroTransladoUnicoPorCliente: TBooleanField;
    tRAOS: TnxTable;
    tRAF: TnxTable;
    tProj: TnxTable;
    tParametroChecarVersaoProj: TBooleanField;
    tParametroPermiteApagarOSSincronizada: TBooleanField;
    Q: TnxQuery;
    tUOS: TnxTable;
    tParametroTodaHorasNoFeriado: TBooleanField;
    procedure kbmMWCustomServiceCreate(Sender: TObject);
    procedure kbmMWCustomServiceDestroy(Sender: TObject);

    procedure ProcessaFlagApagarOS(F: TDataset);
    procedure ProcessaFlagApagarOSFase(F: TDataset);
    procedure ProcessaFlagApagarOSFaseDesc(F: TDataset);
  private
     LI : TLogInfo;
     FImportou : Integer;
     { Private declarations }
     FUsuario,
     FSenha    : String;
     procedure ChecaLogin;
     procedure Debug(S: String);
     procedure ValidaRA(D: TDateTime);
     procedure TransfTable(F: TDataSet; D: TnxTable; idTab: Integer);
     function TemTranslado(Cliente, IDTecnico: String; Dia: TDateTime; ID: Word): Boolean;
     function ConflitoOSID(Cliente, IDTecnico: String;
                           Dia, Inicio, Termino: TDateTime;
                           ID: Word): Boolean;
     procedure ChecaOSRA(Cliente, IDTec: String; DataOS: TDateTime; IDOS: Word);
     function TemTransladoEx(T: TnxTable; Cliente, IDTecnico: String; Dia: TDateTime; ID: Word): Boolean;
     function ConflitoOSIDEx(T: TnxTable; Cliente, IDTecnico: String;
                             Dia, Inicio, Termino: TDateTime;
                             ID: Word): Boolean;
    procedure ValidDespesa(var D: TnxTable; var Oper: Byte; F: TDataSet);
    procedure ValidaOS(F: TDataSet);
  protected
     FAlerta: String;
     { Private declarations }
     function Upload(const Args: array of Variant): Variant;
     function ProcessRequest(const Func:string; const ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant; override;
  public
     { Public declarations }
{$IFNDEF CPP}class{$ENDIF} function GetPrefServiceName:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetSyntaxAbstract:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetDescriptionAbstract:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetFlags:TkbmMWServiceFlags; override;
  end;

implementation

uses licClasses, uDTSyncDef, uDTTabelas;

{$R *.dfm}

const
  opupImportar = 1;
  opupEditar   = 2;

// Service definitions.
//---------------------

function VariantToSN(V: Variant): String;
begin
  if (V<>null) and SameText('S', V) then
    Result := 'S' else
    Result := 'N';
end;

{$IFNDEF CPP}class{$ENDIF} function TkbmUp.GetPrefServiceName:string;
begin
     Result:='UPLOADSVC';
end;

{$IFNDEF CPP}class{$ENDIF} function TkbmUp.GetSyntaxAbstract:string;
begin
     Result:='Upload (Tecnico, Senha: String; Arq1, Arq2, Arq3, Arq4: Variant)';
end;

{$IFNDEF CPP}class{$ENDIF} function TkbmUp.GetDescriptionAbstract:string;
begin
     Result:='Upload de OS e Apontamento';
end;

{$IFNDEF CPP}class{$ENDIF} function TkbmUp.GetFlags:TkbmMWServiceFlags;
begin
     Result:=[mwsfListed];
end;

function Pad(S: String; Len: Integer): String;
begin
  Result := S;
  while Length(Result)<Len do Result := Result +  ' ';
end;

procedure TkbmUp.ValidaOS(F: TDataSet);
begin
  if not SameText(F.FieldByName('Apagar').AsString, 'S') then begin
    if tParametroChecarVersaoProj.Value then begin
      if not tProj.FindKey([F.FieldByName('Cliente').AsString, F.FieldByName('Projeto').AsString]) then
        Raise Exception.Create('Projeto do Cliente ' + F.FieldByName('Cliente').AsString + ' com ID ' +
                               F.FieldByName('Projeto').AsString + ' não existe na base de download mais recente.');
      if not SameText(tProj.FieldByName('VersaoProj').AsString, F.FieldByName('VersaoProj').AsString) then
        Raise Exception.Create('Já existe uma nova versão de projeto. Será necessário fazer novo download');
    end;
    
    if ConflitoOSID(F.FieldByName('Cliente').AsString, F.FieldByName('Tecnico').AsString, F.FieldByName('Data').AsDateTime, F.FieldByName('Inicio').AsDateTime, F.FieldByName('Termino').AsDateTime, F.FieldByName('ID').AsInteger) then
      raise Exception.Create('Já existe OS na mesma faixa de horário da OS ' + F.FieldByName('ID').AsString + '. É necessário fazer um novo download e refazer a(s) OS(s)');
    if FormatDateTime('hhmm', F.FieldByName('Translado').AsDateTime) > '0000' then
      if TemTranslado(F.FieldByName('Cliente').AsString, F.FieldByName('Tecnico').AsString, F.FieldByName('Data').AsDateTime, F.FieldByName('ID').AsInteger) then
        raise Exception.Create('Já existe translado para esse cliente/dia. ' + 'É necessário fazer um novo download e refazer a(s) OS(s)');
  end;
  
  if F.Bof then
  begin
    LI.liDetalhes.Add('========================================================================');
    LI.liDetalhes.Add(' Cliente Data       ID-OS Inicio Termino Transl Abono Num.Atend Apagar');
    LI.liDetalhes.Add('========================================================================');
  end;
  LI.liDetalhes.Add(' ' + 
                    Pad(F.FieldByName('Cliente').AsString, 8) + 
                    FormatDateTime('dd/mm/yyyy', F.FieldByName('Data').AsDateTime) + ' ' + 
                    Pad(F.FieldByName('ID').AsString, 6) + 
                    FormatDateTime('hh:mm', F.FieldByName('Inicio').AsDateTime) + '  ' + 
                    FormatDateTime('hh:mm', F.FieldByName('Termino').AsDateTime) + '   ' + 
                    FormatDateTime('hh:mm', F.FieldByName('Translado').AsDateTime) + '  ' + 
                    FormatDateTime('hh:mm', F.FieldByName('Abono').AsDateTime) + ' ' + 
                    Pad(F.FieldByName('NumAtend').AsString, 10) +
                    VariantToSN(F.FieldByName('Apagar').Value));
end;

procedure TkbmUp.ValidaRA(D: TDateTime);
begin
  if FAlerta<>'' then Exit;
  tRAF.Refresh;
  if tRAF.IsEmpty then Exit; 
  tRAF.FindNearest([D]);
  if (tRAF.FieldByName('DataF').AsDateTime >= D) then
    FAlerta := 'ATENÇÃO: Já existe uma consolidação em andamento. É provavel que as despesas apontadas sejam consolidadas somente no próximo mês';
end;

procedure TkbmUp.ValidDespesa(var D: TnxTable; var Oper: Byte; F: TDataSet);
var
  Achou: Boolean;
begin
  D.IndexName := 'IID';
  Achou := D.FindKey([F.FieldByName('Tecnico').AsString, F.FieldByName('Cliente').AsString, F.FieldByName('ID').AsInteger]);
  if F.FieldByName('ExcluirServ').AsBoolean then
  begin
    Oper := 0;
    if Achou then
      D.Delete;
  end else
  begin
    if Achou then begin
      if F.FieldByName('OnServ').AsBoolean then
        Oper := opupEditar
      else
        raise Exception.Create('Já existe uma despesa com número ' + F.FieldByName('ID').AsString + ' do técnico ' + F.FieldByName('Tecnico').AsString + ' e cliente ' + F.FieldByName('Cliente').AsString + '. Será necessário fazer novo download');
    end else begin
      if F.FieldByName('OnServ').AsBoolean then
        raise Exception.Create('Despesa não encontrada para atualização. Número ' + F.FieldByName('ID').AsString + ' do técnico ' + F.FieldByName('Tecnico').AsString + ' e cliente ' + F.FieldByName('Cliente').AsString + '. Será necessário fazer novo download')
      else
        Oper := opupImportar;        
    end;
  end;
end;


// Master request processor.
//--------------------------

procedure TkbmUp.ProcessaFlagApagarOS(F: TDataset);
begin
  if not SameText(F.FieldByName('Apagar').AsString, 'S') then Exit;
  if not tParametroPermiteApagarOSSincronizada.Value then
    Raise Exception.Create('Não é permitido apagar OS que já foi sincronizada');

  Q.SQL.Text := 'update UOS set Apagar = ' + QuotedStr('S');
  Q.SQL.Add(
    Format(' where (cliente = %s) and (tecnico = %s) and (data = :Data) and (ID = %d)',
    [QuotedStr(F.FieldByName('Cliente').AsString), 
     QuotedStr(F.FieldByName('Tecnico').AsString),
     F.FieldByName('ID').AsInteger]));
  Q.ParamByName('Data').AsDateTime := F.FieldByName('Data').AsDateTime;   
  Q.ExecSQL;    
end;

procedure TkbmUp.ProcessaFlagApagarOSFase(F: TDataset);
begin
  if not SameText(F.FieldByName('Apagar').AsString, 'S') then Exit;
  Q.SQL.Text := 'update UOSFase set Apagar = ' + QuotedStr('S');
  Q.SQL.Add(
    Format(' where (cliente = %s) and (projeto = %s) and (fase = %s) and (tecnico = %s) and (item = %d)',
    [QuotedStr(F.FieldByName('Cliente').AsString), 
     QuotedStr(F.FieldByName('Projeto').AsString),
     QuotedStr(F.FieldByName('Fase').AsString),
     QuotedStr(F.FieldByName('Tecnico').AsString),
     F.FieldByName('Item').AsInteger]));
  Q.ExecSQL;   
end;

procedure TkbmUp.ProcessaFlagApagarOSFaseDesc(F: TDataset);
begin
  if not SameText(F.FieldByName('Apagar').AsString, 'S') then Exit;
  Q.SQL.Text := 'update UOSFaseDesc set Apagar = ' + QuotedStr('S');
  Q.SQL.Add(
    Format(' where (cliente = %s) and (projeto = %s) and (fase = %s) and (tecnico = %s) and (item = %d)',
    [QuotedStr(F.FieldByName('Cliente').AsString), 
     QuotedStr(F.FieldByName('Projeto').AsString),
     QuotedStr(F.FieldByName('Fase').AsString),
     QuotedStr(F.FieldByName('Tecnico').AsString),
     F.FieldByName('Item').AsInteger]));
  Q.ExecSQL;   
end;

function TkbmUp.ProcessRequest(const Func:string; const ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant;
var
   AFunc:string;
begin
  LI.Inicia(iolUpload);
  try
    FAlerta := '';
    dbDown.Active := False;
    dbDown.AliasPath := DownDir(dmbdServ.UltimoImp);
    dbDown.Active := True;
    tTec.Open;
    tOS.Open;
    tUOS.Open;
    tParametro.Open;
    tProj.Open;

     try
       AFunc:=UpperCase(Func);
       if AFunc='UPLOAD' then
          Result:=Upload(Args)
       else Result:=inherited ProcessRequest(Func,ClientIdent,Args);

       LI.liSucesso := True;
       dmBDServ.UltimoUp := LI.liLogID;
     except
       on E: Exception do begin
         LI.liSucesso := False;
         Result := 'Erro = '+E.Message;
         LI.liDetalhes.Add(Result);
       end;
     end;
  finally
    try
      if LI.liSucesso then begin
        mtLog.EmptyTable;
        mtLog.Active := True;
        LI.SalvaEsp(mtLog);
        Result := mtLog.AllData;
      end;
    except
    end;

    if FAlerta<>'' then begin
      LI.liDetalhes.Add('');
      LI.liDetalhes.Add(FAlerta);
    end;
    
    LI.Salva(nil, nil, nxSession);
  end;

  if (FAlerta>'') then
    Result := VarArrayOf([Result, FAlerta]);
end;


// Functions published by the service.
//------------------------------------

procedure TkbmUp.TransfTable(F: TDataSet; D: TnxTable; idTab: Integer);
var 
  I, Cnt : Integer;
  C : TField;
  Oper: Byte;
begin
  F.First;
  Cnt := 0;
  while not F.Eof do begin
    Inc(FImportou);

    Oper := opupImportar;
    
    case idTab of
      idtbOS : begin
        ValidaOS(F);
        ProcessaFlagApagarOS(F);
      end;

      idtbOSFase : ProcessaFlagApagarOSFase(F);
      idtbOSFaseDesc : ProcessaFlagApagarOSFaseDesc(F);
      
      
      idtbRA : ValidaRA(F.FieldByName('DataF').AsDateTime);
      idtbRAItem : ValidDespesa(D, Oper, F);
      idtbRAOS : ChecaOSRA(F.FieldByName('Cliente').AsString,
                           F.FieldByName('Tecnico').AsString, 
                           F.FieldByName('DataOS').AsDateTime,
                           F.FieldByName('IDOS').AsInteger);
    end;  

    if Oper in [opupImportar, opupEditar] then begin
      if Oper=opupImportar then
        D.Insert
      else
        D.Edit;  
  
      for I := 0 to D.FieldCount-1 do with D.Fields[I] do
      if (UpperCase(FieldName)<>'IDDIATEC') then begin
        C := F.FindField(FieldName);
        if C <> nil then
          Value := C.Value;
      end;
      D.FieldByName('Sync').AsBoolean := True;
      C := D.FindField('DownOK');
      if C<>nil then C.AsBoolean := False;

      C := D.FindField('OnServ');
      if C<>nil then C.AsBoolean := True;
      
      D.FieldByName('LogID').AsInteger := LI.liLogID;
      D.Post;
    end;
      
    Sleep(0);
    Inc(Cnt);
    if Cnt>1000 then begin
      Debug('Loop infinito KbmUp.TransfTable');
      Break;
    end;
    F.Next;
  end;
  if idTab=idtbOS then LI.liDetalhes.Add('');
end;

function TkbmUp.Upload(const Args: Array of Variant): Variant;
var 
  Tentar, I, N : Integer;
  Usuario, Senha, VersaoCli: String; 


procedure Transf(V : Variant; idTab: Integer);
begin
  if V=null then Exit;
  MT.Active := False;
  Tab.Active := False;
  MT.AllData := V;
  MT.Active := True;
  if idTab in [idtbRA..idtbRAFTec] then
    Tab.TableName := NomeTab[idTab]
  else  
    Tab.TableName := 'U'+NomeTab[idTab];
    
  Tab.IndexName := '';
  Tab.Open;
  LI.liDetalhes.Add('Tabela '+NomeTab[idTab]+' - '+IntToStr(MT.RecordCount)+' registro(s)');
  TransfTable(MT, Tab, idTab);
end;

begin
  Usuario := Args[0];
  Senha := Args[1];
  VersaoCli := Args[2];
  if VersaoCli <> cfgVersao then
    Raise Exception.Create(
      'Versão do seu Diatec Cliente ('+VersaoCli+
      ') é diferente da versão do servidor Diatec ('+cfgVersao+'). ' +
      'É necessário atualizar seu Diatec Cliente.');

  Result := '';
  FUsuario := Usuario;
  FSenha := Senha;
  ChecaLogin;
  Tentar := 20;
  tRAF.Active := True;
  tRAF.IndexName := 'IDataF';
  tParametro.Active := True;
  tParametro.Refresh;
  while Tentar>0 do begin
    InitTran(dbUpload, [], False);
    try
      FImportou := 0;
      N := 2;
      for I := 1 to NumTabs do
      if UploadTab[I] then begin
        Inc(N);
        Transf(Args[N], I);
      end;  
      if FImportou=0 then
        Raise Exception.Create('Não há registros a serem importados!');
      dbUpload.Commit;
      Tentar := 0;
    except
      dbUpload.Rollback;
      if Tab.State in [dsEdit, dsInsert] then Tab.Cancel;
      Dec(Tentar);
      if Tentar=0 then Raise;
      Sleep(Random(500));
    end;
  end;
end;

procedure TkbmUp.ChecaLogin;
begin
  LI.liTecnico := FUsuario;
  if not LicencaGlobal.SenhaOk then
    Raise Exception.Create('Diatec não licenciado');

  if (not tTec.FindKey([FUsuario])) or (UpperCase(tTecSenha.Value) <> UpperCase(FSenha)) then
  begin
    LI.liDetalhes.Add('Técnico = '+FUsuario);
    LI.liDetalhes.Add('Senha   = '+FSenha);
    Raise
      Exception.Create('Usuário ou Senha inválida');
  end;
end;


procedure TkbmUp.kbmMWCustomServiceCreate(Sender: TObject);
begin
  dbPar.AliasName := NomeAlias(cDiatecPar);
  dbPar.Active := True;

  dbUpload.Enabled := False;
  dbUpload.AliasName := NomeAlias(cDiatecUp);
  dbUpload.Enabled := True;
  dbUpload.Active := True;

  dbDown.Enabled := False;
  dbDown.AliasPath := DownDir(dmBDServ.UltimoImp);
  dbDown.Enabled := True;
  dbDown.Active := True;
  tTec.Open;

  LI := TLogInfo.Create;
end;

procedure TkbmUp.kbmMWCustomServiceDestroy(Sender: TObject);
begin
  LI.Free;
end;

function ConflitoHorario(I1, T1, I2, T2: TDateTime): Boolean;
begin
  Result := (I1 < T2) and (I2 < T1);
end;

function TkbmUp.ConflitoOSID(Cliente, IDTecnico: String;
                             Dia, Inicio, Termino: TDateTime;
                             ID: Word): Boolean;
begin
  Result := ConflitoOSIDEx(tOS, Cliente, IDTecnico, Dia, Inicio, Termino, ID) or
            ConflitoOSIDEx(tUOS, Cliente, IDTecnico, Dia, Inicio, Termino, ID);
end;

function TkbmUp.ConflitoOSIDEx(T: TnxTable; Cliente, IDTecnico: String;
                              Dia, Inicio, Termino: TDateTime;
                              ID: Word): Boolean;
var DownOk: Boolean;                              
begin
  T.Active := True;
  T.CancelRange;
  if tParametroConflitoHoraTodosCli.Value then begin
    T.IndexName := 'ITecnico';
    T.SetRange([IDTecnico, Dia], [IDTecnico, Dia]);
  end else begin
    T.IndexName := 'IID';
    T.SetRange([Cliente, IDTecnico, Dia], [Cliente, IDTecnico, Dia]);
  end;

  T.Refresh;
  T.First;
  Result := True;
  while not T.Eof do begin
    DownOk := SameText('U', Copy(T.TableName, 1, 1)) and
              T.FieldByName('DownOk').AsBoolean;
              
    if not DownOk then
    if (not SameText('S', T.FieldByName('Apagar').AsString)) and 
       ConflitoHorario(T.FieldByName('Inicio').AsDateTime,
                       T.FieldByName('Termino').AsDateTime,
                       Inicio, Termino) then Exit;
    T.Next;
  end;

  Result := False;
end;


function TkbmUp.TemTranslado(Cliente, IDTecnico: String; Dia: TDateTime; ID: Word): Boolean;
begin
  Result := TemTransladoEx(tOS, Cliente, IDTecnico, Dia, ID) or
            TemTransladoEx(tUOS, Cliente, IDTecnico, Dia, ID);
end;

function TkbmUp.TemTransladoEx(T: TnxTable; Cliente, IDTecnico: String; Dia: TDateTime; ID: Word): Boolean;
var DownOk : Boolean;
begin
  T.Active := True;
  T.CancelRange;
  T.IndexName := 'IID';
  T.SetRange([Cliente, IDTecnico, Dia], [Cliente, IDTecnico, Dia]);
  T.Refresh;
  T.First;
  Result := True;
  while not T.Eof do begin
    DownOk := SameText('U', Copy(T.TableName, 1, 1)) and
              T.FieldByName('DownOk').AsBoolean;
              
    if not DownOk then
    if {(T.FieldByName('ID').AsInteger<>ID) and} (not SameText(T.FieldByName('Apagar').AsString, 'S')) and 
       (FormatDateTime('hh:mm', T.FieldByName('Translado').AsDateTime) > '00:00')
    then
      Exit;
    T.Next;
  end;  
  Result := False;  
end;

procedure TkbmUp.Debug(S: String);
begin
  TLogInfo.Debug(S, nil, nil, nxSession);
end;


procedure TkbmUp.ChecaOSRA(Cliente, IDTec: String; DataOS: TDateTime;
  IDOS: Word);
begin
{  tRAOS.Active := True;
  tRAOS.IndexName := 'IOS';
  if tRAOS.FindKey([IDTec, Cliente, DataOS, IDOS]) then 
    Raise Exception.Create('Já foi gerado um relatório de atendimento para a OS do Cliente ' +
                           Cliente + ' / Técnico ' + IDTec + ' Data ' + FormatDateTime('dd/mm/yyyy', DataOS) + 
                           ' ID-OS ' + IntToStr(IDOS));}
end;

end.
