program NexAdmin;

uses
  nxReplacementMemoryManager,
  Forms,
  ncaFrmPri in 'ncaFrmPri.pas' {FrmPri},
  ncaDM in 'ncaDM.pas' {Dados: TDataModule},
  ufmImagens in '..\..\FormMgr\ufmImagens.pas' {dmImagens: TDataModule},
  ufmFormBase in '..\..\FormMgr\ufmFormBase.pas' {FrmBase: TFrmBasePai},
  ncafbMaquinas in 'ncafbMaquinas.pas' {fbMaquinas: TFrmBasePai},
  ncaFrmLogin in 'ncaFrmLogin.pas' {FrmLogin},
  ncafbTran in 'ncafbTran.pas' {fbTran: TFrmBasePai},
  ncaFrmTipos in 'ncaFrmTipos.pas' {FrmTipos},
  ncafbPass in 'ncafbPass.pas' {fbPassaportes: TFrmBasePai},
  ncAuxPassaporte in '..\Comp\ncAuxPassaporte.pas',
  ncaFrmCliente in 'ncaFrmCliente.pas' {FrmCliente},
  ncafbPesqCli in 'ncafbPesqCli.pas' {fbPesqCli: TFrmBasePai},
  ncafbProdutos in 'ncafbProdutos.pas' {fbProdutos: TFrmBasePai},
  ncaFrmProduto in 'ncaFrmProduto.pas' {FrmProduto},
  ncafbMovEst in 'ncafbMovEst.pas' {fbMovEst: TFrmBasePai},
  ncaFrmUsuario in 'ncaFrmUsuario.pas' {FrmUsuario},
  ncaFrmSenha in 'ncaFrmSenha.pas' {FrmAlteraSenha},
  ncafbCaixa in 'ncafbCaixa.pas' {fbCaixa: TFrmBasePai},
  ncaFrmPass in 'ncaFrmPass.pas' {FrmPassaporte},
  ncafbCaixasA in 'ncafbCaixasA.pas' {fbCaixasA: TFrmBasePai},
  ncaFrmCaixa in 'ncaFrmCaixa.pas' {FrmCaixa},
  ncafbOpcoes in 'ncafbOpcoes.pas' {fbOpcoes: TFrmBasePai},
  ncafbTiposImp in 'ncafbTiposImp.pas' {fbTiposImp: TFrmBasePai},
  ncafbTipoPass in 'ncafbTipoPass.pas' {fbTiposPass: TFrmBasePai},
  ncafbTarBasica in 'ncafbTarBasica.pas' {fbTarBasica: TFrmBasePai},
  ncaFrmCorPreco in 'ncaFrmCorPreco.pas' {FrmCorPreco},
  ncafbTarifas in 'ncafbTarifas.pas' {fbTarifas: TFrmBasePai},
  ncaFrmTipoImp in 'ncaFrmTipoImp.pas' {FrmTipoImp},
  ncafbUsuarios in 'ncafbUsuarios.pas' {fbUsuarios: TFrmBasePai},
  ncafbImp in 'ncafbImp.pas' {fbImp: TFrmBasePai},
  ncaFrmDesliga in 'ncaFrmDesliga.pas' {FrmDesliga},
  ncaFrmCaptura in 'ncaFrmCaptura.pas' {FrmCapt},
  ncaFrmImpPrePago in 'ncaFrmImpPrePago.pas' {FrmImpPrePago},
  ncaFrmDebTempo in 'ncaFrmDebTempo.pas' {FrmDebTempo},
  ncaFrmContato in 'ncaFrmContato.pas' {FrmContato},
  ncaFrmHistVer in 'ncaFrmHistVer.pas' {FrmRTF},
  ncafbPacotes in 'ncafbPacotes.pas' {fbPacotes: TFrmBasePai},
  ncaFrmPatro in 'ncaFrmPatro.pas' {FrmPatro},
  ncafbPatrocinadores in 'ncafbPatrocinadores.pas' {fbPatrocinadores: TFrmBasePai},
  ncaFrmPacote in 'ncaFrmPacote.pas' {FrmPacote},
  ncClassesBase in '..\Comp\ncClassesBase.pas',
  ncaFrmZerarTempo in 'ncaFrmZerarTempo.pas' {FrmZeraTempo},
  ncIDRecursos in '..\Comp\ncIDRecursos.pas',
  ncaFrmFundo in 'ncaFrmFundo.pas' {FrmFundo},
  gifimage in 'C:\comp\gif\Sources\gifimage.pas',
  ncaColorConv in 'ncaColorConv.pas',
  ncaFrmEtapa in 'ncaFrmEtapa.pas' {FrmEtapa},
  ncFrmChat in '..\Comp\ncFrmChat.pas' {FrmBaseChat},
  ncaFrmTempo in 'ncaFrmTempo.pas' {FrmTempo},
  ncafbClientes in 'ncafbClientes.pas' {fbClientes: TFrmBasePai},
  ncaFrmOpcaoRelCaixa in 'ncaFrmOpcaoRelCaixa.pas' {FrmOpcaoRelCaixa},
  ncSessao in '..\Comp\ncSessao.pas',
  ncServRemoto in '..\Comp\ncServRemoto.pas',
  ncTarifador in '..\Comp\ncTarifador.pas',
  ncCompCliente in '..\Comp\ncCompCliente.pas',
  ncaFrmSessao in 'ncaFrmSessao.pas' {FrmSessao},
  ncCredTempo in '..\Comp\ncCredTempo.pas',
  ncDMServ in '..\Comp\ncDMServ.pas' {DM: TDataModule},
  ncImpressao in '..\Comp\ncImpressao.pas',
  ncTran in '..\Comp\ncTran.pas',
  ncPassaportes in '..\Comp\ncPassaportes.pas',
  ncaFrmVendaProd in 'ncaFrmVendaProd.pas' {FrmVendaProd},
  ncaFrmME in 'ncaFrmME.pas' {FrmME},
  ncMovEst in '..\Comp\ncMovEst.pas',
  ncaFrmDebito in 'ncaFrmDebito.pas' {FrmDebito},
  ncDebito in '..\Comp\ncDebito.pas',
  ncaFrmImp in 'ncaFrmImp.pas' {FrmImp},
  ncNetMsg in '..\Comp\ncNetMsg.pas',
  ncDMCaixa in '..\Comp\ncDMCaixa.pas' {dmCaixa: TDataModule},
  ncaDMComp in 'ncaDMComp.pas' {dmComp: TDataModule},
  ncafbFiltroWeb in 'ncafbFiltroWeb.pas' {fbFiltroWeb: TFrmBasePai},
  ncafbListaEspera in 'ncafbListaEspera.pas' {fbListaEspera: TFrmBasePai},
  ncListaEspera in '..\Comp\ncListaEspera.pas',
  ncaFrmEspera in 'ncaFrmEspera.pas' {FrmEspera},
  ncaFrmProcessos in 'ncaFrmProcessos.pas' {FrmProcessos},
  ncaFrmSite in 'ncaFrmSite.pas' {FrmSite},
  uDMEmail in '..\..\Email\uDMEmail.pas' {dmEmail: TDataModule},
  ncafbTiposAcesso in 'ncafbTiposAcesso.pas' {fbTiposAcesso: TFrmBasePai},
  ncaFrmTipoAcesso in 'ncaFrmTipoAcesso.pas' {FrmTipoAcesso},
  ncDebTempo in '..\Comp\ncDebTempo.pas',
  ncaFrmCorrigeDataCaixa in 'ncaFrmCorrigeDataCaixa.pas' {FrmCorrigeDataCaixa},
  ncLancExtra in '..\Comp\ncLancExtra.pas',
  ncaFrmLancExtra in 'ncaFrmLancExtra.pas' {FrmLancExtra},
  ncVersoes in '..\Comp\ncVersoes.pas',
  ncFrmSuporteRem in '..\Comp\ncFrmSuporteRem.pas' {FrmSuporte},
  ncaFrmMaq in 'ncaFrmMaq.pas' {FrmMaq},
  ncafbAvisos in 'ncafbAvisos.pas' {fbAvisos: TFrmBasePai},
  ncaFrmAviso in 'ncaFrmAviso.pas' {FrmAviso},
  udmLogmein in '..\Comp\udmLogmein.pas' {dmLogmein: TDataModule};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'NexCafé Admin';
  Application.CreateForm(TDados, Dados);
  Application.CreateForm(TdmImagens, dmImagens);
  Application.CreateForm(TFrmPri, FrmPri);
  Application.Run;
end.
