pageinfo = [[1183544353,1711],
	[1183543251,1743],
	[1183544287,1765],
	[1183543717,1772],
	[1183546845,1783],
	[1184202501,6496],
	[1183546989,1722],
	[1186104137,3716],
	[1183546817,1765],
	[1183546807,1777],
	[1183547029,1766],
	[1183545347,1768],
	[1183544231,1767],
	[1183544073,1773],
	[1183544343,1707],
	[1183543905,1762],
	[1183544151,1770],
	[1183545229,1750],
	[1184421035,6190],
	[1184520181,3157],
	[1184199261,3730],
	[1184463073,2054],
	[1184255045,4666],
	[1184517615,4389],
	[1184199233,8031],
	[1184523201,9299],
	[1186104969,4448],
	[1184199167,3919],
	[1186105097,1881],
	[1184518509,2837],
	[1184423895,2071],
	[1183544371,1747],
	[1183544267,1761],
	[1184616861,2515],
	[1185303431,7930],
	[1184461963,4829],
	[1184431385,7147],
	[1185301695,5475],
	[1183545513,1779],
	[1183546799,1773],
	[1183543233,1746],
	[1183543081,1751],
	[1183547045,1774],
	[1183546825,1751],
	[1184214605,2531],
	[1184118343,1777],
	[1183544857,1784],
	[1183543771,1764],
	[1183544251,1761],
	[1184592089,5347],
	[1183546557,1798],
	[1184254787,1974],
	[1185281679,2020],
	[1185281681,2164],
	[1183544359,1721],
	[1183543315,1745],
	[1183545265,1781],
	[1183546895,1769],
	[1183544089,1766],
	[1183560409,1771],
	[1183543737,1765],
	[1183894787,6939],
	[1184354525,24363],
	[1184424025,6332],
	[1183545455,1759],
	[1184424053,15816],
	[1184458175,6672],
	[1183546923,1719],
	[1184462939,2205],
	[1184462995,2216],
	[1184254053,2255],
	[1184523999,2500],
	[1184183583,5933],
	[1184254813,2321],
	[1183546055,3171],
	[1183543883,1719],
	[1184215557,2079],
	[1183543891,1727],
	[1185281633,2041],
	[1185280603,2311],
	[1184214695,18930],
	[1184592087,5775],
	[1183544215,1760],
	[1183545437,1775],
	[1184599565,4700],
	[1184462957,2003],
	[1184463009,2028],
	[1183545573,1787],
	[1183545651,1768],
	[1184591985,5167],
	[1183545319,1757],
	[1183545671,1745],
	[1183544135,1735],
	[1185281685,1912],
	[1184215371,1970],
	[1183544971,1719],
	[1183544541,1768],
	[1183543819,1737],
	[1183543845,1741],
	[1183545527,1780],
	[1183544005,1825],
	[1183543969,1851],
	[1183543957,1835],
	[1183544429,1834],
	[1183545751,1774],
	[1184460673,4717],
	[1183545679,1727],
	[1183737131,26288],
	[1183501649,24116],
	[1184354475,6114]];
pagedata = [ ["./abertura.htm","Abertura","﻿Abertura Topo Voltar Avançar Enter topic text here. ",""],
["./abrir_o_caixa.htm","Abrir o caixa","﻿Abrir o caixa Topo Voltar Avançar Enter topic text here. ",""],
["./analise_de_lucro.htm","Análise de Lucro","﻿Análise de Lucro Topo Voltar Avançar Enter topic text here. ",""],
["./atendimento_de_clientes2.htm","Atendimento de Clientes","﻿Atendimento de Clientes Topo Voltar Avançar Enter topic text here. ",""],
["./ativar_o_bloqueio_de_sites.htm","Ativar o bloqueio de sites","﻿Ativar o bloqueio de sites Topo Voltar Avançar Enter topic text here. ",""],
["./atualizar_para_uma_nova_versao.htm","Como atualizar para uma nova versão ?","﻿Como atualizar para uma nova versão ? Topo Voltar Avançar 1. Baixe do site os instaladores do servidor e do administrador. Não é necessário baixa...",""],
["./a__geral.htm","A. Geral","﻿A. Geral Topo Voltar Avançar Enter topic text here. ",""],
["./backup.htm","Backup - Cópia de Dados","﻿Backup - Cópia de Dados Topo Voltar Avançar É imprescindível realizar diariamente uma cópia dos arquivos do banco de dados do NexCafé. A qualquer...",""],
["./bloquear_um_site.htm","Bloquear um site","﻿Bloquear um site Topo Voltar Avançar Enter topic text here. ",""],
["./bloqueio_de_sites.htm","Bloqueio de Sites","﻿Bloqueio de Sites Topo Voltar Avançar Enter topic text here. ",""],
["./b__maquinas_clientes.htm","B. Máquinas Clientes","﻿B. Máquinas Clientes Topo Voltar Avançar Enter topic text here. ",""],
["./cadastrar_funcionario.htm","Cadastrar Funcionário","﻿Cadastrar Funcionário Topo Voltar Avançar Enter topic text here. ",""],
["./cadastrar_um_produto.htm","Cadastrar um Produto","﻿Cadastrar um Produto Topo Voltar Avançar Enter topic text here. ",""],
["./cadastro_de_clientes.htm","Cadastro de Clientes","﻿Cadastro de Clientes Topo Voltar Avançar Enter topic text here. ",""],
["./caixa.htm","Caixa","﻿Caixa Topo Voltar Avançar Enter topic text here. ",""],
["./cartoes_de_tempo.htm","Cartões de Tempo","﻿Cartões de Tempo Topo Voltar Avançar Enter topic text here. ",""],
["./clientes_com_debito.htm","Clientes com Débito","﻿Clientes com Débito Topo Voltar Avançar Enter topic text here. ",""],
["./cliente_gratis.htm","Cliente grátis","﻿Cliente grátis Topo Voltar Avançar Enter topic text here. ",""],
["./como_abrir_o_nexserv_.htm","Como abrir o NexServ ?","﻿Como abrir o NexServ ? Topo Voltar Avançar 1. Clique no ícone do NexServ que fica minimizado ao lado do relógio do Windows. 2. Se não estiver con...",""],
["./como_ativar_o_nexguard_.htm","Como abrir o NexGuard ?","﻿Como abrir o NexGuard ? Topo Voltar Avançar 1. Utilize o ícone do NexGuard da área de trabalho do Windows ou via Menu Iniciar -&#62; Programas -&#62; Nex...",""],
["./como_descubro_o_endereco_do_me.htm","Como descubro o endereço do meu servidor ?","﻿Como descubro o endereço do meu servidor ? Topo Voltar Avançar Vá até o computador onde está instalado o servidor do NexCafé ( NexServ) , e siga ...",""],
["./como_descubro_qual_e_o_meu_cod.htm","Como descubro qual é o meu código de loja ?","﻿Como descubro qual é o meu código de loja ? Topo Voltar Avançar O código de loja é exibido na tela do NexAdmin (no canto superior direito) ou na ...",""],
["./como_encerrar_o_nexserv_.htm","Como encerrar o NexServ ?","﻿Como encerrar o NexServ ? Topo Voltar Avançar 1. Clique no ícone do NexServ que fica minimizado ao lado do relógio do Windows. 2. Clique no botão...",""],
["./como_entrar_no_nexadmin_.htm","Como abrir o NexAdmin ?","﻿Como abrir o NexAdmin ? Topo Voltar Avançar 1. Utilize o ícone do NexAdmin da área de trabalho do Windows ou via Menu Iniciar -&#62; Programas -&#62; Nex...",""],
["./como_faco_para_desinstalar_o_c.htm","Como desinstalar o Cyber Manager CM-Guard das máquinas clientes ?","﻿Como desinstalar o Cyber Manager CM-Guard das máquinas clientes ? Topo Voltar Avançar 1. Entre no administrador do Cyber Manager e clique no botã...",""],
["./como_fechar_o_nexguard_.htm","Como fechar o NexGuard ?","﻿Como fechar o NexGuard ? Topo Voltar Avançar O NexGuard pode ser fechado de duas formas: A-diretamente na máquina cliente ou B-usando o NexAdmin ...",""],
["./como_gerar_uma_copia_dos_seus_.htm","Como gerar uma cópia dos seus dados","﻿Como gerar uma cópia dos seus dados Topo Voltar Avançar Abra a tela do servidor NexCafé e faça o seguinte: 1. Clique na aba \"3. Banco de Dados\" 2...",""],
["./como_importar_o_banco_de_dados.htm","Como importar o banco de dados do Cyber Manager para o NexCafé ?","﻿Como importar o banco de dados do Cyber Manager para o NexCafé ? Topo Voltar Avançar Abra a tela do servidor NexCafé e faça o seguinte: 1. Clique...",""],
["./como_restaurar_uma_copia_dos_s.htm","Como restaurar uma cópia dos seus dados","﻿Como restaurar uma cópia dos seus dados Topo Voltar Avançar Se for necessário recuperar os dados de uma cópia do banco de dados de vo ",""],
["./como_sair_do_nexadmin_.htm","Como fechar o NexAdmin ?","﻿Como fechar o NexAdmin ? Topo Voltar Avançar 1. Clique no botão \"Sair\" ou no botão de fechar janela do canto superior direito. ",""],
["./como_transferir_seu_registro_d.htm","Como transferir o registro do Cyber Manager para o NexCafé ?","﻿Como transferir o registro do Cyber Manager para o NexCafé ? Topo Voltar Avançar É o mesmo processo descrito no item \" Já sou cliente, como faço ...",""],
["./conferencia.htm","Conferência","﻿Conferência Topo Voltar Avançar Enter topic text here. ",""],
["./conferencia_de_estoque.htm","Conferência de Estoque","﻿Conferência de Estoque Topo Voltar Avançar Enter topic text here. ",""],
["./configure_seu_firewall_para_na.htm","Configure o firewall para não bloquear o NexCafé","﻿Configure o firewall para não bloquear o NexCafé Topo Voltar Avançar ",""],
["./confira_o_endereco_do_servidor.htm","Confira se o endereço do servidor está correto na máquina cliente","﻿Confira se o endereço do servidor está correto na máquina cliente Topo Voltar Avançar 1. Anote o endereço de servidor que foi configurado na máqu...",""],
["./confira_se_o_banco_de_dados_do.htm","Confira se o banco de dados do servidor está OK.","﻿Confira se o banco de dados do servidor está OK. Topo Voltar Avançar 1. Abra a tela do servidor NexCafé 2. No lugar da interrogação vai aparecer ...",""],
["./confira_se_o_registro_do_softw.htm","Confira se o registro do software está OK","﻿Confira se o registro do software está OK Topo Voltar Avançar 1. Abra a tela do servidor NexCafé 2. No lugar da interrogação vai aparecer uma ima...",""],
["./conhecer_a_interface.htm","Conhecer a interface","﻿Conhecer a interface Topo Voltar Avançar Conheça agora os conceitos básicos da interface do NexCafé. A-Veja abaixo os elementos mais importantes ...",""],
["./controle_de_impressoes.htm","Controle de Impressões","﻿Controle de Impressões Topo Voltar Avançar Enter topic text here. ",""],
["./criar_ou_alterar_senha_de_func.htm","Criar ou alterar senha","﻿Criar ou alterar senha Topo Voltar Avançar Enter topic text here. ",""],
["./criar_uma_tarifa.htm","Criar uma tarifa","﻿Criar uma tarifa Topo Voltar Avançar Enter topic text here. ",""],
["./cria_uma_senha.htm","Criar uma senha","﻿Criar uma senha Topo Voltar Avançar Enter topic text here. ",""],
["./c__restricoes_do_windows.htm","C. Restrições do Windows","﻿C. Restrições do Windows Topo Voltar Avançar Enter topic text here. ",""],
["./desbloquear_um_site.htm","Desbloquear um site","﻿Desbloquear um site Topo Voltar Avançar Enter topic text here. ",""],
["./desinstalacao.htm","Como faço para desinstalar o NexCafé ?","﻿Como faço para desinstalar o NexCafé ? Topo Voltar Avançar Assim como no processo de instalação, a remoção do NexCafé também é dividida em três p...",""],
["./duvidas_comerciais.htm","Dúvidas Comerciais","﻿Dúvidas Comerciais Topo Voltar Avançar Enter topic text here. ",""],
["./duvidas_tecnicas.htm","Dúvidas Técnicas","﻿Dúvidas Técnicas Topo Voltar Avançar Enter topic text here. ",""],
["./encerrar_um_acesso.htm","Encerrar um acesso","﻿Encerrar um acesso Topo Voltar Avançar Enter topic text here. ",""],
["./entrada_de_estoque.htm","Entrada de Estoque","﻿Entrada de Estoque Topo Voltar Avançar Enter topic text here. ",""],
["./entrar_e_sair_do_nexcafe.htm","Entrar e sair do NexCafé","﻿Entrar e sair do NexCafé Topo Voltar Avançar Antes de aprender a usar o NexCafé é preciso saber como entrar e sair do programa. O NexCafé é compo...",""],
["./envio_de_caixa_por_e_mail.htm","Envio de caixa por e-mail","﻿Envio de caixa por e-mail Topo Voltar Avançar Enter topic text here. ",""],
["./esqueci_minha_senha_de_registr.htm","Esqueci minha senha de registro, o que devo fazer ?","﻿Esqueci minha senha de registro, o que devo fazer ? Topo Voltar Avançar Entre em contato com a Nextar para obtê-la novamente. ",""],
["./e_necessario_desinstalar_o_nex.htm","É necessário desinstalar o NexCafé antes de atualizar para uma nova versão ?","﻿É necessário desinstalar o NexCafé antes de atualizar para uma nova versão ? Topo Voltar Avançar Não. Basta fechar o NexAdmin e o NexServ antes d...",""],
["./e_necessario_fazer_uma_copia_d.htm","É necessário fazer uma cópia dos dados antes de atualizar para uma nova versão ?","﻿É necessário fazer uma cópia dos dados antes de atualizar para uma nova versão ? Topo Voltar Avançar Não. A instalação de uma nova versão não mex...",""],
["./fechamento.htm","Fechamento","﻿Fechamento Topo Voltar Avançar Enter topic text here. ",""],
["./fechar_o_caixa.htm","Fechar o caixa","﻿Fechar o caixa Topo Voltar Avançar Enter topic text here. ",""],
["./funcionarios_e_senhas.htm","Funcionários e Senhas","﻿Funcionários e Senhas Topo Voltar Avançar Enter topic text here. ",""],
["./horarios_nao_permitidos.htm","Horários não permitidos","﻿Horários não permitidos Topo Voltar Avançar Enter topic text here. ",""],
["./incluir_um_novo_cliente.htm","Incluir um novo cliente","﻿Incluir um novo cliente Topo Voltar Avançar Enter topic text here. ",""],
["./iniciar_um_acesso.htm","Iniciar e encerrar um acesso","﻿Iniciar e encerrar um acesso Topo Voltar Avançar Enter topic text here. ",""],
["./iniciar_um_acesso2.htm","Iniciar um acesso","﻿Iniciar um acesso Topo Voltar Avançar Enter topic text here. ",""],
["./instalacao.htm","Instalação","﻿Instalação Topo Voltar Avançar O NexCafé é composto por 3 programas distintos: Servidor, Administrador e Cliente. O servidor é chamado de NexServ...",""],
["./instalar_a_primeira_vez.htm","Como instalar pela primeira vez ?","﻿Como instalar pela primeira vez ? Topo Voltar Avançar A instalação do NexCafé se resume basicamente em baixar do site os instaladores dos 3 progr...",""],
["./ja_sou_cliente_como_faco_para_.htm","Já sou cliente, como faço para digitar minhas informações de registro ?","﻿Já sou cliente, como faço para digitar minhas informações de registro ? Topo Voltar Avançar 1. Selecione a aba \"2. Registro\" e clique no botão \"D...",""],
["./melhores_clientes.htm","Melhores Clientes","﻿Melhores Clientes Topo Voltar Avançar Enter topic text here. ",""],
["./migrando_do_cyber_manager_para.htm","Como migrar do Cyber Manager para o NexCafé","﻿Como migrar do Cyber Manager para o NexCafé Topo Voltar Avançar A mudança se resume basicamente em instalar o NexCafé, importar o banco de dados ...",""],
["./minhas_maquinas_clientes_nao_c.htm","Porque minhas máquinas clientes não se conectam ao servidor ?","﻿Porque minhas máquinas clientes não se conectam ao servidor ? Topo Voltar Avançar Existem algumas causas possíveis para isso. É necessário checar...",""],
["./opcoes.htm","Opções","﻿Opções Topo Voltar Avançar Enter topic text here. ",""],
["./o_nexcafe_e_gratis_.htm","O NexCafé é grátis ?","﻿O NexCafé é grátis ? Topo Voltar Avançar Não. Mas você pode testa-lo gratuitamente por 7 dias. Depois desse prazo você deve decidir se deseja com...",""],
["./o_que_acontece_quando_vence_o_.htm","O que acontece quando vence o prazo de testes ?","﻿O que acontece quando vence o prazo de testes ? Topo Voltar Avançar O NexCafé passa a controlar apenas 2 computadores. Entre em contato conosco p...",""],
["./o_que_e_codigo_de_loja_.htm","O que é código de loja ?","﻿O que é código de loja ? Topo Voltar Avançar É um código que identifica cada loja usuária do NexCafé. Desde o momento que você faz o registro gra...",""],
["./o_que_e_firewall_.htm","O que é firewall ?","﻿O que é firewall ? Topo Voltar Avançar É o nome dado a sistemas que bloqueiam a comunicação de rede. Alguns programas ou vírus usam a comunicação...",""],
["./o_que_e_nexserv_nexadmin_e_nex.htm","O que é NexServ, NexAdmin e NexGuard ?","﻿O que é NexServ, NexAdmin e NexGuard ? Topo Voltar Avançar NexServ: Servidor NexCafé É o programa que guarda o banco de dados do NexCafé. Ele não...",""],
["./o_que_e_senha_de_registro_.htm","O que é senha de registro ?","﻿O que é senha de registro ? Topo Voltar Avançar É uma senha que você mesmo cria na hora de fazer o registro do NexCafé. Não se trata da senha usa...",""],
["./o_que_ha_de_novo_.htm","Novas Versões: O que há de novo ?","﻿Novas Versões: O que há de novo ? Topo Voltar Avançar Conheça nesse item as principais novidades introduzidas a cada grande versão do NexCafé. O ...",""],
["./pacotes.htm","Pacotes","﻿Pacotes Topo Voltar Avançar Enter topic text here. ",""],
["./pagar_novamente_ao_formatar.htm","Se eu formatar ou trocar meu computador vou ser obrigado a comprar o NexCafe novamente:","﻿Se eu formatar ou trocar meu computador vou ser obrigado a comprar o NexCafe novamente: Topo Voltar Avançar Não. Basta digitar suas informações d...",""],
["./passaportes.htm","Passaportes","﻿Passaportes Topo Voltar Avançar Enter topic text here. ",""],
["./porque_nao_o_nexadmin_nao_cons.htm","Porque o NexAdmin não consegue se conectar ao servidor ?","﻿Porque o NexAdmin não consegue se conectar ao servidor ? Topo Voltar Avançar São as mesmas razões que afetam as máquinas clientes, conforme descr...",""],
["./posso_atualizar_com_a_loja_em_.htm","Posso atualizar para uma nova versão do NexCafé com a loja em funcionamento ?","﻿Posso atualizar para uma nova versão do NexCafé com a loja em funcionamento ? Topo Voltar Avançar O NexCafé é feito de forma a permitir a atualiz...",""],
["./pre_requisitos.htm","Quais são os pré-requisitos para instalar o NexCafé ?","﻿Quais são os pré-requisitos para instalar o NexCafé ? Topo Voltar Avançar Confira as configurações necessárias para usar o NexCafé nos seus compu...",""],
["./primeiros_passos.htm","Primeiros Passos","﻿Primeiros Passos Topo Voltar Avançar Nessa seção você vai aprender a dar os primeiros passos dentro do NexCafé. Ela não tem a função de explicar ...",""],
["./produtos_e_estoque.htm","Produtos e Estoque","﻿Produtos e Estoque Topo Voltar Avançar Enter topic text here. ",""],
["./produtos_mais_vendidos.htm","Produtos mais vendidos","﻿Produtos mais vendidos Topo Voltar Avançar Enter topic text here. ",""],
["./proximos_passos.htm","Próximos passos","﻿Próximos passos Topo Voltar Avançar 1. Defina quais programas poderão e quais não poderão ser utilizados pelos clientes 2. Defina quais recursos ...",""],
["./quanto_custa_o_nexcafe_.htm","Quanto custa o NexCafé ?","﻿Quanto custa o NexCafé ? Topo Voltar Avançar Por favor, consulte as condições de comercialização em nosso site http://www.nextar.com.br/nexcafe/c...",""],
["./quero_comprar_o_nexcafe_como_d.htm","Quero comprar o NexCafé, como devo proceder ?","﻿Quero comprar o NexCafé, como devo proceder ? Topo Voltar Avançar Faça o registro do NexCafé e entre em contato com a Nextar para efetuar a compr...",""],
["./registrar_automaticamente.htm","Registrar Automaticamente","﻿Registrar Automaticamente Topo Voltar Avançar Enter topic text here. ",""],
["./registrar_manualmente.htm","Registrar Manualmente","﻿Registrar Manualmente Topo Voltar Avançar Enter topic text here. ",""],
["./registro.htm","Como faço para me registrar ?","﻿Como faço para me registrar ? Topo Voltar Avançar Abra a tela do servidor NexCafé e faça o seguinte: 1. Clique na aba \"2. Registro\" 2. Clique no ...",""],
["./restricoes.htm","Restrições","﻿Restrições Topo Voltar Avançar Enter topic text here. ",""],
["./saida_de_estoque.htm","Saída de Estoque","﻿Saída de Estoque Topo Voltar Avançar Enter topic text here. ",""],
["./senhas.htm","Senhas","﻿Senhas Topo Voltar Avançar Enter topic text here. ",""],
["./se_eu_instalar_uma_nova_versao.htm","Se eu instalar uma nova versão do NexCafé vou perder meus dados ?","﻿Se eu instalar uma nova versão do NexCafé vou perder meus dados ? Topo Voltar Avançar Não. ",""],
["./sou_obrigado_a_registrar_o_nex.htm","Sou obrigado a registrar o NexCafé para usá-lo ?","﻿Sou obrigado a registrar o NexCafé para usá-lo ? Topo Voltar Avançar Se você deseja controlar mais de 2 computadores ou obter suporte técnico é n...",""],
["./suporte_remoto_online.htm","Suporte Remoto Online","﻿Suporte Remoto Online Topo Voltar Enter topic text here. ",""],
["./suporte_tecnico.htm","Suporte Técnico","﻿Suporte Técnico Topo Voltar Avançar Enter topic text here. ",""],
["./tarifacao.htm","Tarifação","﻿Tarifação Topo Voltar Avançar Enter topic text here. ",""],
["./tarifacao_basica.htm","Tarifação Básica","﻿Tarifação Básica Topo Voltar Avançar Enter topic text here. ",""],
["./tarifas_de_impressao.htm","Tarifas de Impressão","﻿Tarifas de Impressão Topo Voltar Avançar Enter topic text here. ",""],
["./tarifas_diferentes_para_jogos_.htm","Tarifas diferentes para Jogos e Internet","﻿Tarifas diferentes para Jogos e Internet Topo Voltar Avançar Enter topic text here. ",""],
["./tarifas_especiais_para_determ2.htm","Tarifas especiais para determinados máquinas","﻿Tarifas especiais para determinados máquinas Topo Voltar Avançar Enter topic text here. ",""],
["./tarifas_especiais_para_determi.htm","Tarifas especiais para determinados clientes","﻿Tarifas especiais para determinados clientes Topo Voltar Avançar Enter topic text here. ",""],
["./totalizacao_por_periodo_mensal.htm","Totalização por período (Mensal, Semanal ...)","﻿Totalização por período (Mensal, Semanal ...) Topo Voltar Avançar Enter topic text here. ",""],
["./transferir_de_maquina.htm","Transferir de Máquina","﻿Transferir de Máquina Topo Voltar Avançar Enter topic text here. ",""],
["./trocar_de_maquina__re_instalar.htm","Como formatar o servidor ou transferir o NexCafé para outro computador ?","﻿Como formatar o servidor ou transferir o NexCafé para outro computador ? Topo Voltar Avançar 1. Faça uma cópia do seu banco de dados antes de for...",""],
["./vendas.htm","Vendas","﻿Vendas Topo Voltar Avançar Enter topic text here. ",""],
["./versao_2_0.htm","Versão 2.0","﻿Versão 2.0 Topo Voltar Avançar Além da troca de nome de Cyber Manager para NexCafé, essa versão trouxe muitas mudanças que facilitam o dia a dia ...",""],
["./versao_2_5.htm","Versão 2.5","﻿Versão 2.5 Topo Voltar Avançar Nessa versão alguns recursos muito solicitados por todas lojas foram incluídos: Lista de Espera, Chat, Bloqueio de...",""],
["./welcome_topic.htm","Bem vindo ao NexCafé","﻿Bem vindo ao NexCafé Topo Avançar O NexCafé é um software de gerenciamento de Cyber Café, Lan-House e outros locais que disponibilizam computador...",""]];
