unit ursCHAT;

// =========================================================================
// kbmMW - An advanced and extendable middleware framework.
// by Components4Developers (http://www.components4developers.com)
//
// Service generated by kbmMW service wizard.
//
// INSTRUCTIONS FOR REGISTRATION/USAGE
// -----------------------------------
// Please update the uses clause of the datamodule/form the TkbmMWServer is placed on by adding 
// kbmMWQueryService to it. Eg.
// 
//     uses ...,kbmMWServer,kbmMWQueryService;
// 
// Somewhere in your application, make sure to register the serviceclass to the TkbmMWServer instance. Eg.
// 
// var
//    sd:TkbmMWCustomServiceDefinition;
// ..
//    sd:=kbmMWServer1.RegisterService(yourserviceclassname,false);
// 
// Set the last parameter to true if this is the default service.
// 



{$I kbmMW.inc}

interface

uses
  SysUtils, {$ifdef LEVEL6}Variants,{$endif} Classes, Forms, kbmMWSecurity, kbmMWServer, kbmMWGlobal, kbmMWQueryService;

type
  TCHAT100 = class(TkbmMWQueryService)
  private
     { Private declarations }
  protected
     { Private declarations }
    function ProcessRequest(const Func:string; const ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant; override;
  public
     { Public declarations }
{$IFNDEF CPP}class{$ENDIF} function GetPrefServiceName:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetVersion:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetFlags:TkbmMWServiceFlags; override;
  end;

implementation

{$R *.dfm}


// Service definitions.
//---------------------

{$IFNDEF CPP}class{$ENDIF} function TCHAT100.GetPrefServiceName:string;
begin
     Result:='Chat';
end;

{$IFNDEF CPP}class{$ENDIF} function TCHAT100.GetVersion:string;
begin
     Result:='100';
end;

{$IFNDEF CPP}class{$ENDIF} function TCHAT100.GetFlags:TkbmMWServiceFlags;
begin
     Result:=[mwsfListed];
end;


end.