unit uRSQSAdmin100;

// =========================================================================
// kbmMW - An advanced and extendable middleware framework.
// by Components4Developers (http://www.components4developers.com)
//
// Service generated by kbmMW service wizard.
//
// INSTRUCTIONS FOR REGISTRATION/USAGE
// -----------------------------------
// Please update the uses clause of the datamodule/form the TkbmMWServer is placed on by adding 
// kbmMWQueryService to it. Eg.
// 
//     uses ...,kbmMWServer,kbmMWQueryService;
// 
// Somewhere in your application, make sure to register the serviceclass to the TkbmMWServer instance. Eg.
// 
// var
//    sd:TkbmMWCustomServiceDefinition;
// ..
//    sd:=kbmMWServer1.RegisterService(yourserviceclassname,false);
// 
// Set the last parameter to true if this is the default service.
// 



{$I kbmMW.inc}

interface

uses
  SysUtils, {$ifdef LEVEL6}Variants,{$endif} Classes, Forms, kbmMWSecurity, kbmMWServer, kbmMWGlobal, kbmMWQueryService, kbmMWNexusDB, kbmMWBinaryStreamFormat,
  kbmMemTable, kbmMWStreamFormat, DB, kbmMWCustomConnectionPool, SyncObjs, Windows,
  kbmMWCustomDataset, kbmMWResolvers, nxdb, nxllTransport, idTcpServer,
  nxptBasePooledTransport, nxtwWinsockTransport, nxllComponent,
  nxsdServerEngine, nxreRemoteServerEngine;

type
  TqsAdmin100 = class(TkbmMWQueryService)
    Resolver: TkbmMWNexusDBResolver;
    qCli: TkbmMWNexusDBQuery;
    BSF: TkbmMWBinaryStreamFormat;
    qTemplate: TkbmMWNexusDBQuery;
    nxRSE: TnxRemoteServerEngine;
    nxDB: TnxDatabase;
    nxSession: TnxSession;
    nxTCPIP: TnxWinsockTransport;
    tUsuario: TnxTable;
    tUsuarioUsername: TStringField;
    tUsuarioSenha: TStringField;
    tUsuarioNome: TStringField;
    tUsuarioAdmin: TBooleanField;
    tUsuarioDireitos: TMemoField;
    tUsuarioNomeCHAT: TStringField;
    tUsuarioStatusCHAT: TStringField;
    tUsuarioCHAT: TBooleanField;
    qStatus: TkbmMWNexusDBQuery;
    qStatusCodigo: TIntegerField;
    qStatusDescricao: TStringField;
    qStatusCorFonte: TIntegerField;
    qStatusCorFundo: TIntegerField;
    qCliCodigo: TIntegerField;
    qCliTipo: TWordField;
    qCliSenha: TStringField;
    qCliCadastroEm: TDateTimeField;
    qCliCadastroPor: TStringField;
    qCliAtualizadoEm: TDateTimeField;
    qCliAtualizadoPor: TStringField;
    qCliLoja: TStringField;
    qCliRazaoSocial: TStringField;
    qCliPais: TStringField;
    qCliCidade: TStringField;
    qCliUF: TStringField;
    qCliEndereco: TMemoField;
    qCliCEP: TStringField;
    qCliBairro: TStringField;
    qCliSerieHD: TStringField;
    qCliNumMaq: TWordField;
    qCliCNPJ: TStringField;
    qCliIE: TStringField;
    qCliObs: TMemoField;
    qCliTelefones: TMemoField;
    qCliEmailReg: TMemoField;
    qCliFormaPagto: TMemoField;
    qCliLicMaq: TWordField;
    qCliLicTipo: TWordField;
    qCliLicVenc: TDateField;
    qCliManInicio: TDateField;
    qCliManVenc: TDateField;
    qCliProprietarios: TMemoField;
    qCliGerente: TStringField;
    qCliTipoLoja: TWordField;
    qCliEmailTec: TMemoField;
    qCliValor: TCurrencyField;
    qCliValorRec: TCurrencyField;
    qCliEmitirNF: TBooleanField;
    qCliMessenger: TMemoField;
    qCliICQ: TMemoField;
    qCliUObtemLic: TDateTimeField;
    qCliUVersao: TStringField;
    qCliNegociacao: TWordField;
    qCliStatus: TIntegerField;
    qCliContatarEm: TDateTimeField;
    procedure ResolverInsert(Sender: TkbmMWCustomResolver; var Skip,
      Abort: Boolean);
    procedure kbmMWQueryServiceAuthenticate(Sender: TObject;
      ClientIdent: TkbmMWClientIdentity;
      var Perm: TkbmMWAccessPermissions);
    procedure kbmMWQueryServiceCreate(Sender: TObject);
    procedure kbmMWQueryServiceAuthenticateQuery(Sender: TObject;
      Query: TkbmMWCustomPooledCursor; ClientIdent: TkbmMWClientIdentity;
      var Permissions: TkbmMWAccessPermissions);
  private
     { Private declarations }
  protected
     { Private declarations }
    function ThreadID: Cardinal;
    procedure AlteraSenha(AUsername, ASenha: String);
    
    function ProcessRequest(const Func:string; const ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant; override;
  public
     { Public declarations }
{$IFNDEF CPP}class{$ENDIF} function GetPrefServiceName:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetFlags:TkbmMWServiceFlags; override;
{$IFNDEF CPP}class{$ENDIF} function GetVersion:string; override;
  end;

var contador: Integer;
  
implementation

uses uRSDM;

{$R *.dfm}


// Service definitions.
//---------------------

{$IFNDEF CPP}class{$ENDIF} function TqsAdmin100.GetPrefServiceName:string;
begin
     Result:='Admin';
end;

{$IFNDEF CPP}class{$ENDIF} function TqsAdmin100.GetFlags:TkbmMWServiceFlags;
begin
     Result:=[mwsfListed, mwsfRunRequireAuth];
end;


class function TqsAdmin100.GetVersion: string;
begin
     Result:='100';
end;

function TqsAdmin100.ProcessRequest(const Func: string;
  const ClientIdent: TkbmMWClientIdentity;
  const Args: array of Variant): Variant;
var AFunc: String;
begin
  AFunc := Trim(UpperCase(Func));
  if AFunc='GETNEXTAUTOINC' then
    Result := GetNextAutoInc(Args[0], Args[1], Args[2])
  else  
  if AFunc='LOGIN' then
    Result := Result
  else  
  if AFunc='ALTERASENHA' then
    AlteraSenha(Args[0], Args[1])
  else 
    Result:= inherited ProcessRequest(Func, ClientIdent, Args);
end;

procedure TqsAdmin100.ResolverInsert(Sender: TkbmMWCustomResolver;
  var Skip, Abort: Boolean);
begin
  Inc(Contador);
end;

procedure TqsAdmin100.kbmMWQueryServiceAuthenticate(Sender: TObject;
  ClientIdent: TkbmMWClientIdentity; var Perm: TkbmMWAccessPermissions);
const
  BoolSN : Array[Boolean] of Char = ('N', 'S');  
var
  ThID: Cardinal;
begin
  ThID := ThreadID;
  with ClientIdent do 
  if (Token>'') and (Copy(Token, 7, 20)=IntToStr(ThID)) then
    Perm := [mwapRead,mwapWrite,mwapDelete,mwapExecute]
  else begin
    tUsuario.Active := True;
    tUsuario.IndexName := 'IUsername';
    if not tUsuario.FindKey([Username]) then 
      Raise Exception.Create('O Nome de usuário '+Username+' não existe.');

    if tUsuarioSenha.Value <> Password then 
      Raise Exception.Create('Senha inválida');

    Token := 'ADMIN'+BoolSN[tUsuarioAdmin.Value]+IntToStr(ThID);
    Perm := [mwapRead,mwapWrite,mwapDelete,mwapExecute];
  end;
end;

function TqsAdmin100.ThreadID: Cardinal;
begin
//  Result := GetCurrentThreadID;
  Result := TidPeerThread(TkbmMWServerTransportInfo(RequestTransportStream.Info).Client).ThreadID;
end;

procedure TqsAdmin100.kbmMWQueryServiceCreate(Sender: TObject);
begin
  nxTCPIP.ServerName := DBServer;
  nxSession.Active := True;
  nxDB.Connected := True;
  tUsuario.Active := True;
end;

procedure TqsAdmin100.kbmMWQueryServiceAuthenticateQuery(Sender: TObject;
  Query: TkbmMWCustomPooledCursor; ClientIdent: TkbmMWClientIdentity;
  var Permissions: TkbmMWAccessPermissions);
begin
  Permissions := [mwapRead,mwapWrite,mwapDelete,mwapExecute];
end;

procedure TqsAdmin100.AlteraSenha(AUsername, ASenha: String);
begin
  if not tUsuario.FindKey([AUsername]) then
    Raise Exception.Create('O Nome de usuário ' + AUsername + 'não existe!');
  InitTran(nxDB, [tUsuario], True);
  try  
    tUsuario.Edit;
    tUsuarioSenha.Value := ASenha;
    tUsuario.Post;
    nxDB.Commit;
  except
    nxDB.Rollback;
    Raise;
  end;  
end;

end.
