unit uRSqsRegistro100;

// =========================================================================
// kbmMW - An advanced and extendable middleware framework.
// by Components4Developers (http://www.components4developers.com)
//
// Service generated by kbmMW service wizard.
//
// INSTRUCTIONS FOR REGISTRATION/USAGE
// -----------------------------------
// Please update the uses clause of the datamodule/form the TkbmMWServer is placed on by adding 
// kbmMWQueryService to it. Eg.
// 
//     uses ...,kbmMWServer,kbmMWQueryService;
// 
// Somewhere in your application, make sure to register the serviceclass to the TkbmMWServer instance. Eg.
// 
// var
//    sd:TkbmMWCustomServiceDefinition;
// ..
//    sd:=kbmMWServer1.RegisterService(yourserviceclassname,false);
// 
// Set the last parameter to true if this is the default service.
// 



{$I kbmMW.inc}

interface

uses
  SysUtils, {$ifdef LEVEL6}Variants,{$endif} Classes, Forms, kbmMWSecurity, kbmMWServer, kbmMWGlobal, kbmMWQueryService, kbmMWNexusDB, kbmMWBinaryStreamFormat,
  kbmMemTable, kbmMWStreamFormat, DB, kbmMWCustomConnectionPool,
  kbmMWCustomDataset, kbmMWResolvers, nxdb, nxllTransport,
  nxptBasePooledTransport, nxtwWinsockTransport, nxsdServerEngine,
  nxreRemoteServerEngine, nxllComponent, uLicenca, kbmMemBinaryStreamFormat, uRSLogInfo;

type
  TqsRegistro100 = class(TkbmMWQueryService)
    nxResolver: TkbmMWNexusDBResolver;
    qRegistro: TkbmMWNexusDBQuery;
    BSF: TkbmMWBinaryStreamFormat;
    nxDB: TnxDatabase;
    nxRSE: TnxRemoteServerEngine;
    nxTCPIP: TnxWinsockTransport;
    nxSession: TnxSession;
    tCli: TnxTable;
    MT: TkbmMemTable;
    MTCodigo: TIntegerField;
    MTSenha: TStringField;
    MTCadastroEm: TDateTimeField;
    MTCadastroPor: TStringField;
    MTAtualizadoEm: TDateTimeField;
    MTAtualizadoPor: TStringField;
    MTLoja: TStringField;
    MTRazaoSocial: TStringField;
    MTPais: TStringField;
    MTCidade: TStringField;
    MTUF: TStringField;
    MTEndereco: TMemoField;
    MTCEP: TStringField;
    MTBairro: TStringField;
    MTSerieHD: TStringField;
    MTNumMaq: TWordField;
    MTCNPJ: TStringField;
    MTIE: TStringField;
    MTObs: TMemoField;
    MTTelefones: TMemoField;
    MTEmailReg: TMemoField;
    MTFormaPagto: TMemoField;
    MTLicMaq: TWordField;
    MTLicVenc: TDateField;
    MTManInicio: TDateField;
    MTManVenc: TDateField;
    MTProprietarios: TMemoField;
    MTGerente: TStringField;
    MTTipoLoja: TWordField;
    MTEmailTec: TMemoField;
    MTBSF: TkbmBinaryStreamFormat;
    MTLicTipo: TWordField;
    tLog: TnxTable;
    tLogNum: TAutoIncField;
    tLogDataHora: TDateTimeField;
    tLogLoja: TIntegerField;
    tLogDetalhes: TMemoField;
    tLogIP: TStringField;
    tLogOperID: TWordField;
    tLogOK: TBooleanField;
    tLogSerieHD: TStringField;
    tCorpo: TnxTable;
    tCorpoID: TAutoIncField;
    tCorpoCorpo: TMemoField;
    tCorpoAssunto: TStringField;
    tCorpoInclusao: TDateTimeField;
    tCorpoTipo: TWordField;
    tCorpoEnviarEm: TDateTimeField;
    tCorpoProcessou: TBooleanField;
    tCorpoDestino: TMemoField;
    procedure kbmMWQueryServiceCreate(Sender: TObject);
    procedure kbmMWQueryServiceDestroy(Sender: TObject);
    procedure tCliAfterInsert(DataSet: TDataSet);
  private
    LI : TLogInfo;
     { Private declarations }
  protected
    procedure LeLicencaTab(var Lic: TLicenca);
  
     { Private declarations }
    function LogModoDemo(const Args:array of Variant):Variant; 
    function ObtemLicencaTeste(const Args:array of Variant):Variant; 
    function ObtemLicenca(const Args:array of Variant):Variant; 
    {Loja: Integer; Versao: String; SerieHD: String; EmDemo: Boolean}
    
    function TrocaHD(const Args:array of Variant):Variant; 
    function AtualizaCadastro(const Args:array of Variant):Variant; 
    function ObtemCadastro(const Args:array of Variant):Variant; 
    function ProcessRequest(const Func:string; const ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant; override;
  public
     { Public declarations }
{$IFNDEF CPP}class{$ENDIF} function GetPrefServiceName:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetVersion:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetAuthor:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetAssistance:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetDescriptionAbstract:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetFlags:TkbmMWServiceFlags; override;
  end;

const
  CamposReadOnly =
    '|CODIGO|CADASTROEM|CADASTROPOR|LICMAQ|LICVENC|LICTIPO|MANINICIO|MANVENC|MESSENGER|ICQ|';

  opObtemLicenca = 1;
  opObtemCadastro = 2;
  opModoDemo = 3;
  opTrocaHD = 4;
  opTesteGratis = 5;
  opAtualizaCadastro = 6;

  OpString : Array[opObtemLicenca..opAtualizaCadastro] of String = (
    'ObtemLicenca    ',
    'ObtemCadastro   ',
    'ModoDemo        ',
    'TrocaHD         ',
    'TesteGratis     ',
    'AtualizaCadastro');

var
  nRequests : Array[1..6] of Integer;  
    
implementation

uses uRSDM;

{$R *.dfm}


// Service definitions.
//---------------------

{$IFNDEF CPP}class{$ENDIF} function TqsRegistro100.GetPrefServiceName:string;
begin
     Result:='REGISTRO';
end;

{$IFNDEF CPP}class{$ENDIF} function TqsRegistro100.GetVersion:string;
begin
     Result:='1.00';
end;

{$IFNDEF CPP}class{$ENDIF} function TqsRegistro100.GetAuthor:string;
begin
     Result:='suporte@cybermgr.com';
end;

{$IFNDEF CPP}class{$ENDIF} function TqsRegistro100.GetAssistance:string;
begin
     Result:='suporte@cybermgr.com';
end;

{$IFNDEF CPP}class{$ENDIF} function TqsRegistro100.GetDescriptionAbstract:string;
begin
     Result:='CADASTRO DE CLIENTES';
end;

{$IFNDEF CPP}class{$ENDIF} function TqsRegistro100.GetFlags:TkbmMWServiceFlags;
begin
     Result:=[mwsfListed];
end;

procedure TqsRegistro100.LeLicencaTab(var Lic: TLicenca);
begin
  Lic.liCodLoja := tCli.FieldByName('Codigo').AsInteger;
  Lic.liSerialHD := tCli.FieldByName('SerieHD').AsString;
  Lic.liMaquinas := tCli.FieldByName('LicMaq').AsInteger;
  Lic.liVencimento := tCli.FieldByName('LicVenc').AsDateTime;
  Lic.liTipo  := tCli.FieldByname('LicTipo').AsInteger;
  Lic.liSenha := LimpaTraco(Lic.SenhaCorreta);
end;

function TqsRegistro100.ProcessRequest(const Func: string;
  const ClientIdent: TkbmMWClientIdentity;
  const Args: array of Variant): Variant;
var 
  uFunc : String;  
begin
  uFunc := UpperCase(Func);
  try
    try
      tLog.Active := True;
    except
    end;  
    if uFunc='OBTEMLICENCATESTE' then begin
      LI.Inicia(opTesteGratis, ClientIdent.RemoteLocation);
      Result := ObtemLicencaTeste(Args);
    end else
    if uFunc='MODODEMO' then begin
      LI.Inicia(opModoDemo, ClientIdent.RemoteLocation);
      Result := LogModoDemo(Args);
    end else
    if uFunc='OBTEMLICENCA' then begin
      LI.Inicia(opObtemLicenca, ClientIdent.RemoteLocation);
      Result := ObtemLicenca(Args);
    end else  
    if uFunc='TROCAHD' then begin
      LI.Inicia(opTrocaHD, ClientIdent.RemoteLocation);
      Result := TrocaHD(Args)
    end else  
    if uFunc='ATUALIZACADASTRO' then begin
      LI.Inicia(opAtualizaCadastro, ClientIdent.RemoteLocation);
      Result := AtualizaCadastro(Args);
    end else  
    if uFunc='OBTEMCADASTRO' then begin
      LI.Inicia(opObtemCadastro, ClientIdent.RemoteLocation);
      Result := ObtemCadastro(Args);
    end else  
      Result := inherited ProcessRequest(Func, ClientIdent, Args)
  except
    On E: Exception do
      Result := VarArrayOf(['Erro não esperado no servidor de registro: ' + E.Message]);
  end;  
  try 
    if Result[0] = 'OK' then
      LI.liOK := True
    else begin 
      LI.liOK := False;
      LI.liDetalhes.Add('RESULTADO = ' + Result[0]);
    end;  
  except
  end;
  if LI.liOper in [1..6] then
    Inc(nRequests[1]);
  
  if not (LI.liOper in [opModoDemo, opObtemLicenca]) then
    LI.SaveToDataset(tLog);  
end;

procedure TransfDados(O, D: TDataset; Tudo: Boolean);
var 
  I : Integer;
  F : TField;
begin
  for I := 0 to D.FieldCount-1 do with D.Fields[I] do 
  if Tudo or ((DataType<>ftAutoInc) and (Pos('|'+UpperCase(FieldName)+'|', CamposReadOnly)=0)) then 
  begin
    F := O.FindField(FieldName);
    if F<>nil then
      Value := F.Value;
  end;  
end;
    
function TqsRegistro100.ObtemLicencaTeste(
  const Args: array of Variant): Variant;
var 
  FLic : TLicenca;
  SIndex : String;
  SLE : TStrings;
  S : String;
  Dia : TDateTime;
begin
  MT.Active := False;
  MT.Active := True;
  MT.AllData := Args[0];
  LI.liHD := MT.FieldByName('SerieHD').AsString;
  SIndex := tLog.IndexName;
  tLog.IndexName := 'IHDOper';
  try
    if tLog.FindKey([LI.liHD, opTesteGratis]) then begin
      Result := VarArrayOf(['Já foi concedido anteriormente uma licença para teste para esse mesmo disco rígido. '+
                'Envie E-mail para suporte@cybermgr.com solicitando uma prorrogação do seu período de teste gratuito.']);
      Exit;
    end;                
      
    tCli.Active := False;
    tCli.Active := True;
    tCli.Insert;
    TransfDados(MT, tCli, False);
    tCli.FieldByName('LicMaq').AsInteger := tCli.FieldByName('NumMaq').AsInteger;
    tCli.FieldByName('LicTipo').AsInteger := tlTeste;
    Dia := Date + 7;
    while DayOfWeek(Dia) in [1, 7] do Dia := Dia + 1;
    tCli.FieldByName('LicVenc').AsDateTime := Dia;
    tCli.FieldByName('CadastroEm').AsDateTime := Now;
    tCli.FieldByName('CadastroPor').AsString := 'Cliente';
    tCli.FieldByName('AtualizadoEm').AsDateTime := Now;
    tCli.FieldByName('AtualizadoPor').AsString := 'Cliente';
    if DayOfWeek(tCli.FieldByName('LicVenc').AsDateTime) = 1 then
      tCli.FieldByName('LicVenc').AsDateTime := tCli.FieldByName('LicVenc').Value + 1;
      
    if DayOfWeek(tCli.FieldByName('LicVenc').AsDateTime) = 7 then
      tCli.FieldByName('LicVenc').AsDateTime := tCli.FieldByName('LicVenc').AsDateTime + 2;
  
    tCli.Post;
    LeLicencaTab(FLic);
    LI.liLoja := tCli.FieldByName('Codigo').AsInteger;
    LI.liHD := FLic.liSerialHD;
    Result := VarArrayOf(['OK', FLic.AsString]);
    SLE := TStringList.Create;
    try
      tCorpo.Active := True;
      tCorpo.Insert;
      tCorpoEnviarEm.Value := EncodeDate(2004, 1, 1);
      tCorpoInclusao.Value := Now;
      tCorpoProcessou.Value := False;
      tCorpoDestino.Value := Email_Cybermgr;
      tCorpoAssunto.Value := 'Cyber Manager - Novo Cadastro';
      SLE.Add('Nova loja testando o Cyber Manager em ' + FormatDateTime('dd/mm/yyyy hh:mm', Now));
      SLE.Add('');
      SLE.Add('Loja = ' + MT.FieldByName('Loja').AsString);
      SLE.Add('Maquinas = ' + IntToStr(FLic.liMaquinas));
      SLE.Add('Proprietario = ' + MT.FieldByName('Proprietarios').AsString);
      SLE.Add('Gerente = ' + MT.FieldByName('Gerente').AsString);
      SLE.Add('Cidade = ' + MT.FieldByName('Cidade').AsString + '/' + MT.FieldByName('UF').AsString);
      SLE.Add('Telefones = ' + MT.FieldByName('Telefones').AsString);
      SLE.Add('');
      SLE.Add('Email Registro = ' + MT.FieldByname('EmailReg').AsString);
      SLE.Add('');
      SLE.Add('Email Técnico = ' + MT.FieldByname('EmailTec').AsString);
      tCorpoCorpo.Value := SLE.Text;
      tCorpo.Post;

      S := Trim(MT.FieldByName('EmailReg').AsString);
      if Trim(MT.FieldByName('EmailTec').AsString)>'' then
      if S > '' then
        S := S + '; ' + Trim(MT.FieldByName('EmailTec').AsString)
      else
        S := Trim(MT.FieldByName('EmailTec').AsString); 
      
      if (S>'') and FileExists('c:\emailreg.txt') then begin
        SLE.LoadFromFile('c:\emailreg.txt');
        tCorpo.Insert;
        tCorpoEnviarEm.Value := EncodeDate(2004, 1, 1);
        tCorpoInclusao.Value := Now;
        tCorpoProcessou.Value := False;
        tCorpoDestino.Value := S;
        tCorpoAssunto.Value := 'Cyber Manager';
        tCorpoCorpo.Value := SLE.Text;
        tCorpo.Post;
      end;
    except
    end;
    SLE.Free;
    tCorpo.Active := False;
  finally
    tLog.IndexName := SIndex;
  end;    
end;

function TqsRegistro100.ObtemLicenca(
  const Args: array of Variant): Variant;
    {Loja: Integer; Versao: String; SerieHD: String; EmDemo: Boolean}
  
var 
  FLic : TLicenca;
begin
  tCli.Active := False;
  tCli.Active := True;
  LI.liLoja :=   Args[0];
  
  if High(Args)>1 then begin
    LI.liHD := Args[2];
    if Args[3]=True then 
      LI.liOper := opModoDemo
    else  
      LI.liOper := opObtemLicenca;
    LI.liDetalhes.Add('Versão CM-Server = ' + Args[1]);  
  end;
  
  if LI.liLoja>0 then begin
    if tCli.FindKey([LI.liLoja]) then begin
      LeLicencaTab(FLic);
      tCli.Edit;
      tCli.FieldByName('UObtemLic').AsDateTime := Now;
      if High(Args)>1 then 
        tCli.FieldByName('UVersao').AsString := Args[1]
      else  
        LI.liHD := FLic.liSerialHD;
      tCli.Post;
      Result := VarArrayOf(['OK', FLic.AsString]);
    end else
      Result := VarArrayOf(['Loja não cadastrada na Cybermgr.com']);
  end else
    Result := VarArrayOf(['OK', '']);
end;

function TqsRegistro100.TrocaHD(const Args: array of Variant): Variant;
var FLic : TLicenca;
begin
  tCli.Active := False;
  tCli.Active := True;
  LI.liLoja :=   Args[0];
  LI.liDetalhes.Add('Senha = ' + Args[1]);
  if (not tCli.FindKey([Args[0]])) then 
    Result := VarArrayOf(['Loja não cadastrada na Cybermgr.com'])
  else
  if tCli.FieldByName('Senha').AsString<>Args[1] then
    Result := VarArrayOf(['A senha da loja não está correta'])
  else begin
    LI.liDetalhes.Add('Serial HD anterior = ' + tCli.FieldByName('SerieHD').AsString);
    LI.liHD := Args[2];
    tCli.Edit;
    tCli.FieldByName('SerieHD').AsString := Args[2];
    tCli.Post;
    LeLicencaTab(FLic);
    Result := VarArrayOf(['OK', FLic.AsString]);
  end;  
end;

function TqsRegistro100.AtualizaCadastro(
  const Args: array of Variant): Variant;
begin
  MT.Active := False;
  MT.Active := True;
  MT.AllData := Args[2];
  tCli.Active := False;
  tCli.Active := True;
  LI.liLoja := Args[0];
  LI.liDetalhes.Add('Senha = ' + Args[1]);
  if (not tCli.FindKey([Args[0]])) then 
    Result := VarArrayOf(['Loja não cadastrada na Cybermgr.com'])
  else
  if tCli.FieldByName('Senha').AsString<>Args[1] then
    Result := VarArrayOf(['A senha da loja não está correta'])
  else begin
    tCli.Edit;
    TransfDados(MT, tCli, False);
    tCli.FieldByName('AtualizadoEm').AsDateTime := Now;
    tCli.FieldByName('AtualizadoPor').AsString := 'Cliente';
    
    tCli.Post;
    LI.liHD := tCli.FieldByName('SerieHD').AsString;
    Result := VarArrayOf(['OK']);
  end;  
end;

function TqsRegistro100.ObtemCadastro(
  const Args: array of Variant): Variant;
begin
  tCli.Active := True;
  LI.liLoja := Args[0];
  LI.liDetalhes.Add('Senha = ' + Args[1]);
  if (not tCli.FindKey([Args[0]])) then 
    Result := VarArrayOf(['Loja não cadastrada na Cybermgr.com'])
  else
  if tCli.FieldByName('Senha').AsString<>Args[1] then
    Result := VarArrayOf(['A senha da loja não está correta'])
  else begin
    MT.Active := True;
    MT.Insert;
    TransfDados(tCli, MT, True);
    MT.Post;
    LI.liHD := tCli.FieldByName('SerieHD').AsString;
    Result := VarArrayOf(['OK', MT.AllData]);
  end;  
end;

procedure TqsRegistro100.kbmMWQueryServiceCreate(Sender: TObject);
begin
  nxTCPIP.ServerName := DBServer;
  LI := TLogInfo.Create;
  tLog.Open;
end;

procedure TqsRegistro100.kbmMWQueryServiceDestroy(Sender: TObject);
begin
  LI.Free;
end;

function TqsRegistro100.LogModoDemo(const Args: array of Variant): Variant;
var S : String;
begin
  S := Args[0];
  LI.liHD := S;
  Result := VarArrayOf(['OK']);
end;

procedure TqsRegistro100.tCliAfterInsert(DataSet: TDataSet);
begin
  tCli.FieldByName('Codigo').AsInteger := GetNextAutoInc('cliente', 'Codigo', '');
end;

initialization
  FillChar(nRequests, SizeOf(nRequests), 0);

end.






                                            
