unit uDTSAdmin;

// =========================================================================
// kbmMW - An advanced and extendable middleware framework.
// by Components4Developers (http://www.components4developers.com)
//
// Service generated by kbmMW service wizard.
//


{$I kbmMW.inc}

interface

uses
  SysUtils, {$ifdef LEVEL6}Variants,{$endif} Classes, Forms, kbmMWSecurity, kbmMWServer, kbmMWGlobal,
  DB, kbmMemTable, kbmMWCustomConnectionPool, kbmMWCustomDataset,
  kbmMWNexusDB, nxdb, nxllComponent, kbmMWStreamFormat,
  kbmMWBinaryStreamFormat, kbmMemBinaryStreamFormat, uDTSrvBDServ;

type
  TkbmDown = class(TkbmMWCustomService)
    BSF: TkbmMWBinaryStreamFormat;
    qCli: TkbmMWNexusDBQuery;
    qOSFaseDesc: TkbmMWNexusDBQuery;
    qOSFase: TkbmMWNexusDBQuery;
    qOSCli: TkbmMWNexusDBQuery;
    qSolicita: TkbmMWNexusDBQuery;
    qFaseTec: TkbmMWNexusDBQuery;
    qSolicitaDesc: TkbmMWNexusDBQuery;
    qOS: TkbmMWNexusDBQuery;
    qAmarra: TkbmMWNexusDBQuery;
    qFase: TkbmMWNexusDBQuery;
    qPar: TkbmMWNexusDBQuery;
    qParMaxDiasUpload: TWordField;
    qParMaxDiasDown: TWordField;
    qParDataDown: TDateTimeField;
    qParNomeFranquia: TStringField;
    qParBitMap: TGraphicField;
    qParObedeceListaProj: TBooleanField;
    qParListaProjDefault: TStringField;
    qParRestringeDiurno: TBooleanField;
    qParTravarTranslado: TBooleanField;
    qParCampoLocalOS: TBooleanField;
    qParInicioDiurno: TDateTimeField;
    qParFimDiurno: TDateTimeField;
    qParUploadApontamentoSemOS: TBooleanField;
    qParPermitirRateio: TBooleanField;
    qParConflitoHoraTodosCli: TBooleanField;
    qParExigeAutorizadoPor: TBooleanField;
    qTec: TkbmMWNexusDBQuery;
    qTecID: TStringField;
    qTecNome: TStringField;
    qTecSenha: TStringField;
    qTecEmpresa: TStringField;
    qTecListaProj: TStringField;
    qMotivo: TkbmMWNexusDBQuery;
    qOcorrencia: TkbmMWNexusDBQuery;
    qTipoHora: TkbmMWNexusDBQuery;
    qProj: TkbmMWNexusDBQuery;
    cpDown: TkbmMWNexusDBConnectionPool;
    seDown: TkbmMWPooledSession;
    dbDown: TnxDatabase;
    nxSession: TnxSession;
    dbPar: TnxDatabase;
    psPar: TkbmMWPooledSession;
    cpPar: TkbmMWNexusDBConnectionPool;
    dbLog: TnxDatabase;
    tLog: TnxTable;
    MT: TkbmMemTable;
    tLogID: TAutoIncField;
    tLogTecnico: TStringField;
    tLogData: TDateTimeField;
    tLogDetalhes: TMemoField;
    tLogOper: TWordField;
    tLogOK: TBooleanField;
    tLogDuracao: TDateTimeField;
    tLogUUpload: TIntegerField;
    qCliT: TkbmMWNexusDBQuery;
    qParMostraReemb: TBooleanField;
    qParForcaTransladoProj: TBooleanField;
    qParTransladoUnicoPorCliente: TBooleanField;
    dbUP: TnxDatabase;
    qRA: TkbmMWNexusDBQuery;
    seUP: TkbmMWPooledSession;
    cpUP: TkbmMWNexusDBConnectionPool;
    qRAOS: TkbmMWNexusDBQuery;
    qRAItem: TkbmMWNexusDBQuery;
    procedure kbmMWCustomServiceCreate(Sender: TObject);
    procedure kbmMWCustomServiceDestroy(Sender: TObject);
  private
     { Private declarations }
     procedure ExecQueries;
     function ChecaLogin: String;
     function Etapa1: Variant;
     function Etapa2: Variant;
  protected
     { Private declarations }
     FListaProj : Char;
     FClientes, FProjetos,
     FUsuario,
     FSenha,
     FCliente,
     FProjeto  : String;
     FDias     : Integer;
     LI        : TLogInfo;
     function Download1(Usuario, Senha, Cliente, Projeto, VersaoCli: String; Dias: Integer): Variant;
     function Download2(Usuario, Senha, VersaoCli: String; Dias: Integer; Clientes, Projetos: String): Variant;
     function ProcessRequest(const Func:string; const ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant; override;
     function PerformDownload1(ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant; virtual;
     function PerformDownload2(ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant; virtual;
  public
     { Public declarations }
{$IFNDEF CPP}class{$ENDIF} function GetPrefServiceName:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetSyntaxAbstract:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetDescriptionAbstract:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetFlags:TkbmMWServiceFlags; override;
  end;

implementation

uses uDTSyncDef, uDTSrvProcessa, licClasses;

{$R *.dfm}


// Service definitions.
//---------------------

{$IFNDEF CPP}class{$ENDIF} function TkbmDown.GetPrefServiceName:string;
begin
     Result:='DOWNLOADSVC';
end;

{$IFNDEF CPP}class{$ENDIF} function TkbmDown.GetSyntaxAbstract:string;
begin
     Result:= 'Download1(Usuario, Senha, Cliente, Projeto, VersaoCli: String; Dias: Integer)'+
              'Download2(Usuario, Senha, VersaoCli: String; Dias: Integer; Clientes, Projetos: String)';
end;

{$IFNDEF CPP}class{$ENDIF} function TkbmDown.GetDescriptionAbstract:string;
begin
     Result:='Download Diatec';
end;

{$IFNDEF CPP}class{$ENDIF} function TkbmDown.GetFlags:TkbmMWServiceFlags;
begin
     Result:=[mwsfListed];
end;


// Master request processor.
//--------------------------

function TkbmDown.ProcessRequest(const Func:string; const ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant;
var
   AFunc:string;
begin
  LI.Inicia(iolDownload);
  LI.liDetalhes.Add('Etapa '+UpperCase(Func));
  try
    cpDown.Active := False;
    dbDown.Active := False;
    dbDown.AliasPath := DownDir(dmbdServ.UltimoImp);
    dbDown.Active := True;

     AFunc:=UpperCase(Func);
     if AFunc='DOWNLOAD1' then
        Result:=PerformDownload1(ClientIdent,Args)
     else 
     if AFunc='DOWNLOAD2' then
        Result:=PerformDownload2(ClientIdent,Args)
     else
       Result:=inherited ProcessRequest(Func,ClientIdent,Args);
  finally
    try
      LI.liSucesso := (VarType(Result) <> varString) and (VarType(Result)<>varOleStr);
      if not LI.liSucesso then begin
        LI.liDetalhes.Add('');
        LI.liDetalhes.Add('Erro = '+Result);
      end;  
    except
    end;  
    LI.Salva(nil, nil, nxSession);
  end;  
end;


// Functions published by the service.
//------------------------------------

function TkbmDown.PerformDownload1(ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant;
begin 
  Result:= Download1(Args[0], Args[1], Args[2], Args[3], Args[4], Args[5]);
end;

function TkbmDown.PerformDownload2(ClientIdent:TkbmMWClientIdentity; const Args:array of Variant):Variant;
begin                            
  Result:= Download2(Args[0], Args[1], Args[2], Args[3], Args[4], Args[5]);
end;

function TkbmDown.Download1(Usuario, Senha, Cliente, Projeto, VersaoCli: String;
  Dias: Integer): Variant;
begin
  try
    if VersaoCli <> cfgVersao then begin
      Result := 'Versão do seu Diatec Cliente ('+VersaoCli+
                ') é diferente da versão do servidor Diatec ('+cfgVersao+'). ' +
                'É necessário atualizar seu Diatec Cliente.';
      Exit;          
    end;
    FUsuario := Usuario;
    FSenha := Senha;
    FCliente := Cliente;
    FProjeto := Projeto;
    FDias    := Dias;
    FClientes := '';
    FProjetos := '';
    Result := ChecaLogin;
    if Result='' then 
      Result := Etapa1;
  except
    On E: Exception do
      Result := 'Exceção não tratada no servidor: ' + E.Message;
  end;    
end;

function TkbmDown.Download2(Usuario, Senha, VersaoCli: String;
  Dias: Integer; Clientes, Projetos: String): Variant;
begin
  try
    if VersaoCli <> cfgVersao then begin
      Result := 'Versão do seu Diatec Cliente ('+VersaoCli+
                ') é diferente da versão do servidor Diatec ('+cfgVersao+'). ' +
                'É necessário atualizar seu Diatec Cliente.';
      Exit;          
    end;
    FUsuario := Usuario;
    FSenha := Senha;
    FCliente := '';
    FProjeto := '';
    FClientes := Clientes;
    FProjetos := Projetos;
    FDias    := Dias;
    Result := ChecaLogin;
    if Result='' then 
      Result := Etapa2;
  except
    On E: Exception do
      Result := 'Exceção não tratada no servidor: ' + E.Message;
  end;    
end;


function TkbmDown.ChecaLogin: String;
begin
  if not LicencaGlobal.SenhaOk then begin
    Result := 'Diatec não licenciado';
    Exit;
  end;
    
  LI.liTecnico := FUsuario;
  LI.liDetalhes.Add('');
  LI.liDetalhes.Add('Tecnico = '+FUsuario);
  LI.liDetalhes.Add('Senha   = '+FSenha);
  LI.liDetalhes.Add('Cliente = '+FCliente);
  LI.liDetalhes.Add('Projeto = '+FProjeto);
  LI.liDetalhes.Add('');
  Result := '';
  cpDown.Active := True;
  cpPar.Active := True;
  
  qTec.SQL.Text := 'SELECT * FROM TECNICO WHERE (UPPER(ID) ='+
                   QuotedStr(UpperCase(FUsuario)) +') AND (UPPER(Senha) = ' +
                   QuotedStr(UpperCase(FSenha)) + ')';
  qTec.Active := False;                   
  qTec.Open;
  if qTec.RecordCount=0 then begin
    Result := 'Usuário ou Senha inválida';
    Exit;
  end;

  qPar.Active := False;
  qPar.Open;  

  with qTec.FieldByName('ListaProj') do
  if AsString > '' then
    FListaProj := AsString[1] 
  else
    FListaProj := #0;   

  if (FListaProj <> lpTotal) then begin
    if not qParObedeceListaProj.Value then
      FListaProj := lpTotal
    else 
    if not (FListaProj in lpValidos) then
    if qParListaProjDefault.Value > '' then
      FListaProj := qParListaProjDefault.Value[1]
    else
      FListaProj := lpDefault;

    if (FListaProj in lpClientes) and (FCliente='') then 
      Result := 'Cliente não informado!'
    else    
    if (FListaProj in lpProjetos) and ((FCliente='') or (FProjeto='')) then
      Result := 'Projeto ou Cliente não informado';
  end;     
end;

function TkbmDown.Etapa1: Variant;
var I : Integer;
begin
  qCli.SQL.Clear;
  qProj.SQL.Clear;
  if (FCliente='') and (FListaProj = lpTotal) then begin
    qCli.SQL.Text := 'select * from CLIENTE';
    qProj.SQL.Text := 'select * from PROJETO';
    qCli.Active := False;
    qCli.Open;

    qProj.Active := False;
    qProj.Open;
    I := qCli.RecordCount;
    Result := I;
    Result := VarArrayOf([qCli.AllData, qProj.AllData]);
    Exit;
  end else begin
    if FListaProj in [lpTotal..lpExigeProjeto] then begin
      qCLI.SQL.Add('SELECT * FROM CLIENTE');
      qCLI.SQL.Add('WHERE (ID = ' + QuotedStr(FCliente) + ')');
      
      qProj.SQL.Add('SELECT * FROM PROJETO');
      qProj.SQL.Add('WHERE (CLIENTE = ' + QuotedStr(FCliente)+')');
      if FProjeto>'' then
        qProj.SQL.Add(' AND (ID = ' + QuotedStr(FProjeto)+')');
    end else begin
      qCli.SQL.Add('SELECT C.* FROM CLIENTE C, FASETEC F');
      qCli.SQL.Add('WHERE (');
      qCli.SQL.Add('(ID = F.CLIENTE) AND');
      qCli.SQL.Add('(F.TECNICO = ' + QuotedStr(FUsuario)+')');
      if FCliente>'' then begin
        qCli.SQL.Add(' AND (F.CLIENTE=' + QuotedStr(FCliente) + ')');
        if FProjeto>'' then
          qCli.SQL.Add(' AND (F.PROJETO=' + QuotedStr(FProjeto) + ')');
      end;    
      qCli.SQL.Add(')');
      qProj.SQL.Add('SELECT P.* FROM PROJETO P, FASETEC F');
      qProj.SQL.Add('WHERE (ID = F.PROJETO) AND');
      qProj.SQL.Add('(F.TECNICO = ' + QuotedStr(FUsuario)+')');
      if (FCliente>'') then begin
        qProj.SQL.Add(' AND (F.CLIENTE=' + QuotedStr(FCliente) + ')');
        if FProjeto>'' then
          qProj.SQL.Add(' AND (F.PROJETO=' + QuotedStr(FProjeto) + ')');
      end;    
    end;
    qCli.Active := False;
    qCli.Open;

    qProj.Active := False;
    qProj.Open;

    qCliT.Active := False;
    qCliT.Open;

    if (qCli.RecordCount=0) or (qProj.RecordCount=0) then begin
      Result := 'Não existe projetos a serem baixados com os parâmetros informados!';
      Exit;
    end;

    if FCliente='' then
      Result := VarArrayOf([qCliT.AllData, qProj.AllData])
    else begin
      ExecQueries;
      
      qCliT.Active := False;
      qCliT.Open;

{      qOSCli.Active := True;
      qOSCli.First;
      while not qOSCli.Eof do begin
        if not qCli.Locate('ID', qOSCli.FieldByName('ID').AsString, []) then
          TransfDados(qOSCli, qCli);
        qOSCli.Next;
      end;}

      Result := VarArrayOf([qCliT.AllData,
                            qProj.AllData,
                            qTec.AllData,
                            qPar.AllData,
                            qOS.AllData,
                            qOSFase.AllData,
                            qFase.AllData,
                            qOSFaseDesc.AllData,
                            qAmarra.AllData,
                            qFaseTec.AllData,
                            qSolicita.AllData,
                            qSolicitaDesc.AllData,
                            qMotivo.AllData,
                            qOcorrencia.AllData,
                            qTipoHora.AllData,
                            qRA.AllData,
                            qRAOS.AllData,
                            qRAItem.AllData,
                            MT.AllData]);
    end;
  end; 
end;

function TkbmDown.Etapa2: Variant;
begin
  ExecQueries;
  Result := VarArrayOf([qOSCli.AllData, 
                        qTec.AllData, 
                        qPar.AllData,
                        qOS.AllData,
                        qOSFase.AllData,
                        qFase.AllData,
                        qOSFaseDesc.AllData,
                        qAmarra.AllData,
                        qFaseTec.AllData,
                        qSolicita.AllData,
                        qSolicitaDesc.AllData,
                        qMotivo.AllData,
                        qOcorrencia.AllData,
                        qTipoHora.AllData,
                        qRA.AllData,
                        qRAOS.AllData,
                        qRAItem.AllData,
                        MT.AllData]);
end;

procedure TkbmDown.ExecQueries;
var
  D : TDateTime;
  slCli, slProj, SL, slOS : TStringList;
  PrimeiroProj : Boolean;
  S : String;
  I : Integer;


procedure AddLine(St: String);
begin
  if SL.Count > 1 then
    St := 'OR ' + St;
  SL.Add(' '+St);  
end;

procedure AddLineOS(St: String);
begin
  if slOS.Count = 1 then
    slOS.Add('OR ((Tecnico='+QuotedStr(FUsuario)+') AND (');
    
  if slOS.Count > 2 then
    St := 'OR ' + St;
    
  slOS.Add(' '+St);  
end;


begin
  SL := TStringList.Create;
  slCli := TStringList.Create;
  slProj := TStringList.Create;
  slOS :=TStringList.Create;
  try
    qOSFase.SQL.Clear;
    qFase.SQL.Clear;
    qAmarra.SQL.Clear;
    qOSFaseDesc.SQL.Clear;
    qFaseTec.SQL.Clear;
    qSolicita.SQL.Clear;
    qSolicitaDesc.SQL.Clear;
    qOS.SQL.Clear;
    
    qRA.SQL.Text := 'SELECT * FROM RA WHERE';
    qRAOS.SQL.Text := 'SELECT * FROM RAOS WHERE';
    qRAItem.SQL.Text := 'SELECT * FROM RAITEM WHERE';
    S := '(Tecnico=' + QuotedStr(FUsuario) + ') AND ((DataI >= '+ 
         QuotedStr(FormatDateTime('yyyy-mm-dd', Date-FDias))+ 
         ') OR (DATAF >= '+
         QuotedStr(FormatDateTime('yyyy-mm-dd', Date-FDias))+'))';
         
    qRA.SQL.Add(S);
    qRAOS.SQL.Add(S);     
    qRAITEM.SQL.Add(S);     
    
    qOSCli.SQL.Clear;
    qOSCli.SQL.Add('SELECT DISTINCT(C.ID), C.* FROM CLIENTE C, OS O');
    qOSCli.SQL.Add('WHERE');
    qOSCli.SQL.Add('((Tecnico=' + QuotedStr(FUsuario) + ') AND (Data >= '+ 
                   QuotedStr(FormatDateTime('yyyy-mm-dd', Date-FDias))+ 
                   ') AND (O.CLIENTE=C.ID))');
    S := qOSCli.SQL.Text + ' ';
    qOSCli.SQL.Text := S;    

  
    if (FCliente='') and (FClientes>'') and (FProjetos>'') then begin
      SL.Add('(');
      slCli.Text := FClientes;
      for I := 0 to slCli.Count-1 do
        AddLineOS(slCli[I]);

      slProj.Text := FProjetos;
      for I := 0 to slProj.Count-1 do
        AddLine(slProj[I]);
        
      if slOS.Count > 2 then
        slOS.Add('))');
      SL.Add(')');
    end else begin
      if FProjeto>'' then
        SL.Add('((Cliente='+QuotedStr(FCliente)+') AND (Projeto=' + QuotedStr(FProjeto) + '))')
      else
        SL.Add('(Cliente='+QuotedStr(FCliente)+')');
      slOS.Add(' OR (Cliente='+QuotedStr(FCliente)+')');  
    end;    

    qOS.SQL.Text := 'select * from OS';
    qOS.SQL.Add('where ');
    qOS.SQL.AddStrings(slOS);

    qOSFase.SQL.Text := 'select * from OSFase';
    qOSFase.SQL.Add('where');
        
    qFase.SQL.Text := 'select * from Fase';
    qFase.SQL.Add('where');

    qAmarra.SQL.Text := 'select * from AmarraFase';
    qAmarra.SQL.Add('where');
    
    qOSFaseDesc.SQL.Text := 'select * from OSFaseDesc';
    qOSFaseDesc.SQL.Add('where');
    
    qFaseTec.SQL.Text := 'select * from FaseTec';
    qFaseTec.SQL.Add('where');
    
    qSolicita.SQL.Text := 'select * from Solicita';
    qSolicita.SQL.Add('where');
    
    qSolicitaDesc.SQL.Text := 'select * from SolicitaDesc';
    qSolicitaDesc.SQL.Add('where');

    if FListaProj in [lpAmarrados, lpAmarradosCli, lpAmarradosProj] then begin
      qOSFase.SQL[0] := 'select O.* from OSFase O, FaseTec F';
      qOSFase.SQL.Add('(Cliente = F.Cliente) AND (Projeto = F.Projeto) AND (Fase = F.Fase)');
      qOSFase.SQL.Add('AND (F.Tecnico = ' + QuotedStr(FUsuario) + ')');
      qOSFase.SQL.Add('AND');

      qOSFaseDesc.SQL[0] := 'select O.* from OSFaseDesc O, FaseTec F';
      qOSFaseDesc.SQL.Add('(Cliente = F.Cliente) AND (Projeto = F.Projeto) AND (Fase = F.Fase)');
      qOSFaseDesc.SQL.Add('AND (F.Tecnico = ' + QuotedStr(FUsuario) + ')');
      qOSFaseDesc.SQL.Add('AND');

      qFase.SQL[0] := 'select A.* from Fase A, FaseTec F';
      qFase.SQL.Add('((Sumario=True) or (Cliente = F.Cliente) AND (Projeto = F.Projeto) AND (ID = F.Fase))');
      qFase.SQL.Add('AND (F.Tecnico = ' + QuotedStr(FUsuario) + ')');
      qFase.SQL.Add('AND');
    end;
      
    qOSFase.SQL.AddStrings(SL);  
    qFase.SQL.AddStrings(SL);
    qAmarra.SQL.AddStrings(SL);
    qOSFaseDesc.SQL.AddStrings(SL);
    qFaseTec.SQL.AddStrings(SL);
    qSolicita.SQL.AddStrings(SL);
    qSolicitaDesc.SQL.AddStrings(SL);

    qOS.Active := False;
    qOS.Open;
    S := qOSFase.SQL.Text;
    qOSFase.SQL.Text := S + ' ';
    qOSFase.Active := False;
    qOSFase.Open;
    I := qOSFase.RecordCount;
    S := IntToStr(I);
    qFase.Active := False;
    qFase.Open;
    qOSFaseDesc.Active := False;
    qOSFaseDesc.Open;
    qAmarra.Active := False;
    qAmarra.Open;
    qFaseTec.Active := False;
    qFaseTec.Open;
    qSolicita.Active := False;
    qSolicita.Open;
    qSolicitaDesc.Active := False;
    qSolicitaDesc.Open;
    qOSCli.Active := False;
    qOSCli.Open;
    qTec.SQL.Text := 'Select * from Tecnico';
    qTec.Active := False;
    qTec.Open;
    qOcorrencia.Active := False;
    qOcorrencia.Open;
    qMotivo.Active := False;
    qMotivo.Open;
    qTipoHora.Active := False;
    qTipoHora.Open;

    tLog.Open;
    D := Date;
    tLog.SetRange([iolUpload, FUsuario, D-15], [iolUpload, FUsuario, D+15]);

    tLog.Refresh;
    MT.LoadFromDataSet(tLog, [mtcpoStructure]);
  finally
    SL.Free;
    slOS.Free;
    slCli.Free;
    slProj.Free;
  end;    
end;


procedure TkbmDown.kbmMWCustomServiceCreate(Sender: TObject);
begin
  LI := TLogInfo.Create;
  dbDown.Active := False;
  
  dbDown.AliasPath := DownDir(dmbdServ.UltimoImp);
  dbPar.AliasName := NomeAlias(cDiatecPar);
  dbLog.AliasName := NomeAlias(cDiatecLog);
  dbUP.AliasName := NomeAlias(cDiatecUP);
  dbDown.Open;
  dbLog.Open;
  dbUP.Open;

  qCli.AllDataFormat := BSF;
  qProj.AllDataFormat := BSF;
  qTec.AllDataFormat := BSF;
  qPar.AllDataFormat := BSF;
  qOS.AllDataFormat := BSF;
  qOSFase.AllDataFormat := BSF;
  qFase.AllDataFormat := BSF;
  qOSFaseDesc.AllDataFormat := BSF;
  qAmarra.AllDataFormat := BSF;
  qFaseTec.AllDataFormat := BSF;
  qSolicita.AllDataFormat := BSF;
  qSolicitaDesc.AllDataFormat := BSF;
  qMotivo.AllDataFormat := BSF;
  qOcorrencia.AllDataFormat := BSF;
  qTipoHora.AllDataFormat := BSF;
  qOSCli.AllDataFormat := BSF;
  qCliT.AllDataFormat := BSF;
  qRA.AllDataFormat := BSF;
  qRAOS.AllDataFormat := BSF;
  qRAItem.AllDataFormat := BSF;
  
  MT.AllDataFormat := BSF;
end;


procedure TkbmDown.kbmMWCustomServiceDestroy(Sender: TObject);
begin
  LI.Free;
end;

end.
